// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project fbc126bea31ebbe6 "Untitled", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { routes } from "./chunks/chunk-2F3PHDTH.js";

// virtual:big-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/Wbg1G82TaBdELH3hpTN6/ITxn11s0YvmTEEVWpu1L/ldVMmsUQg.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	cx,
	getLoadingLazyAtYPosition,
	Image,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var MotionDivWithFX = withFX(motion.div);
var enabledGestures = {
	uN1jAr_Fm: {
		hover: true,
	},
};
var serializationHash = "framer-n2w61";
var variantClassNames = {
	uN1jAr_Fm: "framer-v-y7c88t",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: -20,
	rotateY: 0,
	scale: 0.9,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 50,
};
var transition1 = {
	delay: 0,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "uN1jAr_Fm",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (gestureVariant === "uN1jAr_Fm-hover") return false;
		return true;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<MotionDivWithFX
						{...restProps}
						{...gestureHandlers}
						__framer__animate={{
							transition: transition1,
						}}
						__framer__animateOnce={true}
						__framer__enter={animation}
						__framer__styleAppearEffectEnabled={true}
						__framer__threshold={0.5}
						__perspectiveFX={false}
						__smartComponentFX={true}
						__targetOpacity={1}
						className={cx(
							scopingClassNames,
							"framer-y7c88t",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"uN1jAr_Fm"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								"uN1jAr_Fm-hover": {
									"data-framer-name": void 0,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-13lxgex"}
							data-framer-name={"Main Tile"}
							layoutDependency={layoutDependency}
							layoutId={"Owu6b1pUX"}
							style={{
								backgroundColor:
									"var(--token-06cbdf7a-4b04-4493-a020-8aa6e2439856, rgb(240, 240, 240))",
							}}
						>
							<motion.div
								className={"framer-1k4awsj"}
								layoutDependency={layoutDependency}
								layoutId={"sDYfEvDkF"}
							>
								<Image
									background={{
										alt: "",
										fit: "fill",
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) +
												40 +
												(((componentViewport?.height || 768) -
													56 -
													(Math.max(
														0,
														((componentViewport?.height || 768) - 56 - 237) / 1,
													) *
														1 +
														231 +
														6)) /
													2 +
													0 +
													0) +
												(0 +
													(Math.max(
														0,
														((componentViewport?.height || 768) - 56 - 237) / 1,
													) *
														1 -
														0 -
														(Math.max(
															0,
															((componentViewport?.height || 768) - 56 - 237) /
																1,
														) *
															1 -
															0) *
															1) /
														2) +
												(0 +
													((Math.max(
														0,
														((componentViewport?.height || 768) - 56 - 237) / 1,
													) *
														1 -
														0) *
														1 -
														0 -
														((Math.max(
															0,
															((componentViewport?.height || 768) - 56 - 237) /
																1,
														) *
															1 -
															0) *
															1 -
															0) *
															1) /
														2),
										),
										pixelHeight: 1536,
										pixelWidth: 2048,
										sizes: `max(${componentViewport?.width || "100vw"} - 258px, 1px)`,
										src: "https://framerusercontent.com/images/kYlvgXGRRGYDaDfgQQB3hAthoQ.png?width=2048&height=1536",
										srcSet:
											"https://framerusercontent.com/images/kYlvgXGRRGYDaDfgQQB3hAthoQ.png?scale-down-to=512&width=2048&height=1536 512w,https://framerusercontent.com/images/kYlvgXGRRGYDaDfgQQB3hAthoQ.png?scale-down-to=1024&width=2048&height=1536 1024w,https://framerusercontent.com/images/kYlvgXGRRGYDaDfgQQB3hAthoQ.png?width=2048&height=1536 2048w",
									}}
									className={"framer-441vqb"}
									layoutDependency={layoutDependency}
									layoutId={"Iz1kn2Byp"}
									style={{
										borderBottomLeftRadius: 16,
										borderBottomRightRadius: 16,
										borderTopLeftRadius: 16,
										borderTopRightRadius: 16,
									}}
									{...addPropertyOverrides(
										{
											"uN1jAr_Fm-hover": {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															40 +
															(((componentViewport?.height || 768) -
																56 -
																(Math.max(
																	0,
																	((componentViewport?.height || 768) -
																		56 -
																		0) /
																		1,
																) *
																	1 +
																	0)) /
																2 +
																0 +
																0) +
															(0 +
																(Math.max(
																	0,
																	((componentViewport?.height || 768) -
																		56 -
																		0) /
																		1,
																) *
																	1 -
																	0 -
																	(Math.max(
																		0,
																		((componentViewport?.height || 768) -
																			56 -
																			0) /
																			1,
																	) *
																		1 -
																		0) *
																		1) /
																	2) +
															(0 +
																((Math.max(
																	0,
																	((componentViewport?.height || 768) -
																		56 -
																		0) /
																		1,
																) *
																	1 -
																	0) *
																	1 -
																	0 -
																	((Math.max(
																		0,
																		((componentViewport?.height || 768) -
																			56 -
																			0) /
																			1,
																	) *
																		1 -
																		0) *
																		1 -
																		0) *
																		1) /
																	2),
													),
													pixelHeight: 1536,
													pixelWidth: 2048,
													sizes: `max(${componentViewport?.width || "100vw"}, 1px)`,
													src: "https://framerusercontent.com/images/kYlvgXGRRGYDaDfgQQB3hAthoQ.png?width=2048&height=1536",
													srcSet:
														"https://framerusercontent.com/images/kYlvgXGRRGYDaDfgQQB3hAthoQ.png?scale-down-to=512&width=2048&height=1536 512w,https://framerusercontent.com/images/kYlvgXGRRGYDaDfgQQB3hAthoQ.png?scale-down-to=1024&width=2048&height=1536 1024w,https://framerusercontent.com/images/kYlvgXGRRGYDaDfgQQB3hAthoQ.png?width=2048&height=1536 2048w",
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							</motion.div>
							{isDisplayed() && (
								<Image
									background={{
										alt: "",
										fit: "fill",
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) +
												40 +
												(((componentViewport?.height || 768) -
													56 -
													(Math.max(
														0,
														((componentViewport?.height || 768) - 56 - 237) / 1,
													) *
														1 +
														231 +
														6)) /
													2 +
													0 +
													0) +
												(0 +
													(Math.max(
														0,
														((componentViewport?.height || 768) - 56 - 237) / 1,
													) *
														1 -
														0 -
														(Math.max(
															0,
															((componentViewport?.height || 768) - 56 - 237) /
																1,
														) *
															1 -
															0) *
															1) /
														2),
										),
										pixelHeight: 1128,
										pixelWidth: 1504,
										sizes: "252px",
										src: "https://framerusercontent.com/images/sugL8yb4dn9xwrKK7ju2sSH2YT8.png?width=1504&height=1128",
										srcSet:
											"https://framerusercontent.com/images/sugL8yb4dn9xwrKK7ju2sSH2YT8.png?scale-down-to=512&width=1504&height=1128 512w,https://framerusercontent.com/images/sugL8yb4dn9xwrKK7ju2sSH2YT8.png?scale-down-to=1024&width=1504&height=1128 1024w,https://framerusercontent.com/images/sugL8yb4dn9xwrKK7ju2sSH2YT8.png?width=1504&height=1128 1504w",
									}}
									className={"framer-gpli2q"}
									layoutDependency={layoutDependency}
									layoutId={"IzBLr3pK0"}
									style={{
										borderBottomLeftRadius: 16,
										borderBottomRightRadius: 16,
										borderTopLeftRadius: 16,
										borderTopRightRadius: 16,
									}}
								/>
							)}
						</motion.div>
						{isDisplayed() && (
							<motion.div
								className={"framer-1qxzub2"}
								layoutDependency={layoutDependency}
								layoutId={"Ucm1VLTlg"}
							>
								<Image
									background={{
										alt: "",
										fit: "fill",
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) +
												40 +
												(((componentViewport?.height || 768) -
													56 -
													(Math.max(
														0,
														((componentViewport?.height || 768) - 56 - 237) / 1,
													) *
														1 +
														231 +
														6)) /
													2 +
													Math.max(
														0,
														((componentViewport?.height || 768) - 56 - 237) / 1,
													) *
														1 +
													6) +
												0,
										),
										pixelHeight: 1536,
										pixelWidth: 2048,
										positionX: "left",
										positionY: "top",
										sizes: `calc(${componentViewport?.width || "100vw"} * 0.2429)`,
										src: "https://framerusercontent.com/images/OPaUrsBXoIpzQ2UVbiaeIVEKm94.png?width=2048&height=1536",
										srcSet:
											"https://framerusercontent.com/images/OPaUrsBXoIpzQ2UVbiaeIVEKm94.png?scale-down-to=512&width=2048&height=1536 512w,https://framerusercontent.com/images/OPaUrsBXoIpzQ2UVbiaeIVEKm94.png?scale-down-to=1024&width=2048&height=1536 1024w,https://framerusercontent.com/images/OPaUrsBXoIpzQ2UVbiaeIVEKm94.png?width=2048&height=1536 2048w",
									}}
									className={"framer-dch1v0"}
									layoutDependency={layoutDependency}
									layoutId={"qz4jYg4zy"}
									style={{
										borderBottomLeftRadius: 16,
										borderBottomRightRadius: 16,
										borderTopLeftRadius: 16,
										borderTopRightRadius: 16,
									}}
								/>
								<Image
									background={{
										alt: "",
										fit: "fill",
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) +
												40 +
												(((componentViewport?.height || 768) -
													56 -
													(Math.max(
														0,
														((componentViewport?.height || 768) - 56 - 237) / 1,
													) *
														1 +
														231 +
														6)) /
													2 +
													Math.max(
														0,
														((componentViewport?.height || 768) - 56 - 237) / 1,
													) *
														1 +
													6) +
												0,
										),
										pixelHeight: 1e3,
										pixelWidth: 1504,
										positionX: "left",
										positionY: "top",
										sizes: `max((${componentViewport?.width || "100vw"} * 0.7571 - 12px) / 2, 1px)`,
										src: "https://framerusercontent.com/images/PbDTl3XSi3CZNFgnKV4XIE8ZQms.png?width=1504&height=1000",
										srcSet:
											"https://framerusercontent.com/images/PbDTl3XSi3CZNFgnKV4XIE8ZQms.png?scale-down-to=512&width=1504&height=1000 512w,https://framerusercontent.com/images/PbDTl3XSi3CZNFgnKV4XIE8ZQms.png?scale-down-to=1024&width=1504&height=1000 1024w,https://framerusercontent.com/images/PbDTl3XSi3CZNFgnKV4XIE8ZQms.png?width=1504&height=1000 1504w",
									}}
									className={"framer-1qq2a4p"}
									layoutDependency={layoutDependency}
									layoutId={"VgsJc32rp"}
									style={{
										borderBottomLeftRadius: 16,
										borderBottomRightRadius: 16,
										borderTopLeftRadius: 16,
										borderTopRightRadius: 16,
									}}
								/>
								<Image
									background={{
										alt: "",
										fit: "fill",
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) +
												40 +
												(((componentViewport?.height || 768) -
													56 -
													(Math.max(
														0,
														((componentViewport?.height || 768) - 56 - 237) / 1,
													) *
														1 +
														231 +
														6)) /
													2 +
													Math.max(
														0,
														((componentViewport?.height || 768) - 56 - 237) / 1,
													) *
														1 +
													6) +
												0,
										),
										pixelHeight: 1128,
										pixelWidth: 1504,
										sizes: `max((${componentViewport?.width || "100vw"} * 0.7571 - 12px) / 2, 1px)`,
										src: "https://framerusercontent.com/images/sugL8yb4dn9xwrKK7ju2sSH2YT8.png?width=1504&height=1128",
										srcSet:
											"https://framerusercontent.com/images/sugL8yb4dn9xwrKK7ju2sSH2YT8.png?scale-down-to=512&width=1504&height=1128 512w,https://framerusercontent.com/images/sugL8yb4dn9xwrKK7ju2sSH2YT8.png?scale-down-to=1024&width=1504&height=1128 1024w,https://framerusercontent.com/images/sugL8yb4dn9xwrKK7ju2sSH2YT8.png?width=1504&height=1128 1504w",
									}}
									className={"framer-2p5xea"}
									layoutDependency={layoutDependency}
									layoutId={"wAAogZpG6"}
									style={{
										borderBottomLeftRadius: 16,
										borderBottomRightRadius: 16,
										borderTopLeftRadius: 16,
										borderTopRightRadius: 16,
									}}
								/>
							</motion.div>
						)}
					</MotionDivWithFX>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-n2w61.framer-zbickd, .framer-n2w61 .framer-zbickd { display: block; }",
	".framer-n2w61.framer-y7c88t { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 6px; height: 768px; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 40px 0px 16px 0px; position: relative; width: 1021px; }",
	".framer-n2w61 .framer-13lxgex { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 6px; height: 1px; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; }",
	".framer-n2w61 .framer-1k4awsj { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 100%; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-n2w61 .framer-441vqb, .framer-n2w61 .framer-1qq2a4p, .framer-n2w61 .framer-2p5xea { flex: 1 0 0px; height: 100%; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 1px; will-change: var(--framer-will-change-override, transform); }",
	".framer-n2w61 .framer-gpli2q { flex: none; height: 100%; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 252px; will-change: var(--framer-will-change-override, transform); }",
	".framer-n2w61 .framer-1qxzub2 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 6px; height: 231px; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; }",
	".framer-n2w61 .framer-dch1v0 { flex: none; height: 100%; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 24%; will-change: var(--framer-will-change-override, transform); }",
];
var FramerldVMmsUQg = withCSS(Component, css, "framer-n2w61");
var stdin_default = FramerldVMmsUQg;
FramerldVMmsUQg.displayName = "BIG CARD";
FramerldVMmsUQg.defaultProps = {
	height: 768,
	width: 1021,
};
addFonts(
	FramerldVMmsUQg,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:big-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"fbc126bea31ebbe6cf64cc6db71380905aa865df749edb6fe0a120a118d79a8c"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders BigCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"fbc126bea31ebbe6cf64cc6db71380905aa865df749edb6fe0a120a118d79a8c"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var big_card_default = ComponentWithRoot;
export { big_card_default as default };
