// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project fbc126bea31ebbe6 "Untitled", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * images?: {src: string, srcSet?: string, alt?: string}[] // Images
 * slideWidth?: number // Slide Width
 * slideHeight?: number // Slide Height
 * gap?: number // Gap
 * parallax?: number // Parallax
 * dragRange?: number // Drag Range
 * background?: string // Background
 * radius?: number // Radius
}} Props

 */
import { routes } from "./chunks/chunk-2F3PHDTH.js";

// virtual:drag-parallax-slider
import { Fragment } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/DagF1VUP2osDpcOg3ZGv/3TlbuRFgGzFmgfivrwD7/DragParallaxSlider.js
import { jsx as _jsx } from "react/jsx-runtime";
import { useState, useRef, startTransition } from "react";
import { motion, useMotionValue, useTransform } from "unframer";
import { addPropertyControls, ControlType } from "unframer";
function DragParallaxSlider(props) {
	const {
		images = [
			{
				src: "https://framerusercontent.com/images/GfGkADagM4KEibNcIiRUWlfrR0.jpg",
				alt: "Gradient 1 - Blue",
			},
			{
				src: "https://framerusercontent.com/images/aNsAT3jCvt4zglbWCUoFe33Q.jpg",
				alt: "Gradient 2 - Purple",
			},
			{
				src: "https://framerusercontent.com/images/BYnxEV1zjYb9bhWh1IwBZ1ZoS60.jpg",
				alt: "Gradient 3 - Orange",
			},
		],
		slideWidth = 300,
		slideHeight = 400,
		gap = 20,
		parallaxStrength = 50,
		dragConstraints = 100,
		backgroundColor = "#000000",
		borderRadius = 16,
	} = props;
	const containerRef = useRef(null);
	const x = useMotionValue(0);
	const [isDragging, setIsDragging] = useState(false);
	const handleDragStart = () => {
		startTransition(() => setIsDragging(true));
	};
	const handleDragEnd = () => {
		startTransition(() => setIsDragging(false));
	};
	return (
		<div
			ref={containerRef}
			style={{
				width: "100%",
				height: "100%",
				overflow: "hidden",
				backgroundColor,
				borderRadius,
				position: "relative",
				cursor: isDragging ? "grabbing" : "grab",
			}}
		>
			<motion.div
				drag={"x"}
				dragConstraints={{
					left: -dragConstraints,
					right: dragConstraints,
				}}
				onDragStart={handleDragStart}
				onDragEnd={handleDragEnd}
				style={{
					display: "flex",
					gap,
					x,
					height: "100%",
					alignItems: "center",
					paddingLeft: "50%",
					paddingRight: "50%",
				}}
			>
				{images.map((image, index) => {
					const slideX = useTransform(
						x,
						[-dragConstraints * 2, 0, dragConstraints * 2],
						[parallaxStrength, 0, -parallaxStrength],
					);
					return (
						<motion.div
							style={{
								width: slideWidth,
								height: slideHeight,
								flexShrink: 0,
								borderRadius: borderRadius * 0.75,
								overflow: "hidden",
								x: slideX,
							}}
						>
							<img
								src={image.src}
								alt={image.alt}
								style={{
									width: "100%",
									height: "100%",
									objectFit: "cover",
									pointerEvents: "none",
									userSelect: "none",
								}}
								draggable={false}
							/>
						</motion.div>
					);
				})}
			</motion.div>
		</div>
	);
}
addPropertyControls(DragParallaxSlider, {
	images: {
		type: ControlType.Array,
		title: "Images",
		control: {
			type: ControlType.ResponsiveImage,
		},
		defaultValue: [
			{
				src: "https://framerusercontent.com/images/GfGkADagM4KEibNcIiRUWlfrR0.jpg",
				alt: "Gradient 1 - Blue",
			},
			{
				src: "https://framerusercontent.com/images/aNsAT3jCvt4zglbWCUoFe33Q.jpg",
				alt: "Gradient 2 - Purple",
			},
			{
				src: "https://framerusercontent.com/images/BYnxEV1zjYb9bhWh1IwBZ1ZoS60.jpg",
				alt: "Gradient 3 - Orange",
			},
		],
	},
	slideWidth: {
		type: ControlType.Number,
		title: "Slide Width",
		defaultValue: 300,
		min: 100,
		max: 800,
		step: 10,
		unit: "px",
	},
	slideHeight: {
		type: ControlType.Number,
		title: "Slide Height",
		defaultValue: 400,
		min: 100,
		max: 800,
		step: 10,
		unit: "px",
	},
	gap: {
		type: ControlType.Number,
		title: "Gap",
		defaultValue: 20,
		min: 0,
		max: 100,
		step: 5,
		unit: "px",
	},
	parallaxStrength: {
		type: ControlType.Number,
		title: "Parallax",
		defaultValue: 50,
		min: 0,
		max: 200,
		step: 10,
	},
	dragConstraints: {
		type: ControlType.Number,
		title: "Drag Range",
		defaultValue: 100,
		min: 50,
		max: 500,
		step: 10,
	},
	backgroundColor: {
		type: ControlType.Color,
		title: "Background",
		defaultValue: "#000000",
	},
	borderRadius: {
		type: ControlType.Number,
		title: "Radius",
		defaultValue: 16,
		min: 0,
		max: 50,
		step: 1,
		unit: "px",
	},
});

// virtual:drag-parallax-slider
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"fbc126bea31ebbe6cf64cc6db71380905aa865df749edb6fe0a120a118d79a8c"
			}
			locale={locale}
			locales={locales}
		>
			<DragParallaxSlider {...rest} />
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders DragParallaxSliderFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"fbc126bea31ebbe6cf64cc6db71380905aa865df749edb6fe0a120a118d79a8c"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={DragParallaxSlider}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, DragParallaxSlider);
var drag_parallax_slider_default = ComponentWithRoot;
export { drag_parallax_slider_default as default };
