// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project fbc126bea31ebbe6 "Untitled", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Variant 2' // Variant
 * companyName?: string // Company Name
 * onrQhjBRCxVCHange?: undefined // onrQhjBRCxVCHange
 * position?: string // Position
 * onTOT_Vs4aMCHange?: undefined // onTOT_Vs4aMCHange
 * year?: string // Year
 * onjILORsDZNCHange?: undefined // onjILORsDZNCHange
 * showLiveBadge?: boolean // Show Live Badge
 * onFZVO6gzbrChange?: undefined // onFZVO6gzbrChange
 * link?: string // Link
}} Props

 */
import { stdin_default as stdin_default2 } from "./chunks/chunk-DWOHXQGU.js";
import { stdin_default } from "./chunks/chunk-TVKCWW5D.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-7G5KBBVY.js";
import { className, css, fonts } from "./chunks/chunk-MCFUM3XF.js";
import { LiveDot } from "./chunks/chunk-FUZA3VPR.js";
import { routes } from "./chunks/chunk-2F3PHDTH.js";

// virtual:experience
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/Cbrf5gPbdFHBiXpDV0n8/MABDUXr0DslekIL7LntH/cx7WayR4m.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	forwardLoader,
	getFonts,
	getFontsFromSharedStyle,
	Link,
	RichText,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/qVPeC7deCj4BIFIItLfI/YpjJranclTcviYB2hTWw/BFyu0Sm3h.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"GF;IBM Plex Sans-regular",
	"GF;IBM Plex Sans-700",
	"GF;IBM Plex Sans-700italic",
	"GF;IBM Plex Sans-italic",
]);
var fonts3 = [
	{
		explicitInter: true,
		fonts: [
			{
				cssFamilyName: "IBM Plex Sans",
				openType: true,
				source: "google",
				style: "normal",
				uiFamilyName: "IBM Plex Sans",
				url: "https://fonts.gstatic.com/s/ibmplexsans/v23/zYXGKVElMYYaJe8bpLHnCwDKr932-G7dytD-Dmu1swZSAXcomDVmadSD6llzBaI5loa26g.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "IBM Plex Sans",
				openType: true,
				source: "google",
				style: "normal",
				uiFamilyName: "IBM Plex Sans",
				url: "https://fonts.gstatic.com/s/ibmplexsans/v23/zYXGKVElMYYaJe8bpLHnCwDKr932-G7dytD-Dmu1swZSAXcomDVmadSDDV5zBaI5loa26g.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "IBM Plex Sans",
				openType: true,
				source: "google",
				style: "italic",
				uiFamilyName: "IBM Plex Sans",
				url: "https://fonts.gstatic.com/s/ibmplexsans/v23/zYXEKVElMYYaJe8bpLHnCwDKhdTEG46kmUZQCX598fQbM4jw8V78x9OWIhp8RKg4tIOm6vje.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "IBM Plex Sans",
				openType: true,
				source: "google",
				style: "italic",
				uiFamilyName: "IBM Plex Sans",
				url: "https://fonts.gstatic.com/s/ibmplexsans/v23/zYXEKVElMYYaJe8bpLHnCwDKhdTEG46kmUZQCX598fQbM4jw8V78x9OWIhqbQ6g4tIOm6vje.woff2",
				weight: "400",
			},
		],
	},
];
var css3 = [
	`.framer-lmVrI .framer-styles-preset-kwafes:not(.rich-text-wrapper), .framer-lmVrI .framer-styles-preset-kwafes.rich-text-wrapper p { --framer-font-family: "IBM Plex Sans", "IBM Plex Sans Placeholder", sans-serif; --framer-font-family-bold: "IBM Plex Sans", "IBM Plex Sans Placeholder", sans-serif; --framer-font-family-bold-italic: "IBM Plex Sans", "IBM Plex Sans Placeholder", sans-serif; --framer-font-family-italic: "IBM Plex Sans", "IBM Plex Sans Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 20px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: 0em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-99df6449-e9f2-4797-8ee6-4b98273d37fc, #001b25); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }`,
	`@media (max-width: 1199px) and (min-width: 390px) { .framer-lmVrI .framer-styles-preset-kwafes:not(.rich-text-wrapper), .framer-lmVrI .framer-styles-preset-kwafes.rich-text-wrapper p { --framer-font-family: "IBM Plex Sans", "IBM Plex Sans Placeholder", sans-serif; --framer-font-family-bold: "IBM Plex Sans", "IBM Plex Sans Placeholder", sans-serif; --framer-font-family-bold-italic: "IBM Plex Sans", "IBM Plex Sans Placeholder", sans-serif; --framer-font-family-italic: "IBM Plex Sans", "IBM Plex Sans Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: 0em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-99df6449-e9f2-4797-8ee6-4b98273d37fc, #001b25); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }`,
	`@media (max-width: 389px) and (min-width: 0px) { .framer-lmVrI .framer-styles-preset-kwafes:not(.rich-text-wrapper), .framer-lmVrI .framer-styles-preset-kwafes.rich-text-wrapper p { --framer-font-family: "IBM Plex Sans", "IBM Plex Sans Placeholder", sans-serif; --framer-font-family-bold: "IBM Plex Sans", "IBM Plex Sans Placeholder", sans-serif; --framer-font-family-bold-italic: "IBM Plex Sans", "IBM Plex Sans Placeholder", sans-serif; --framer-font-family-italic: "IBM Plex Sans", "IBM Plex Sans Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 10px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: 0em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-99df6449-e9f2-4797-8ee6-4b98273d37fc, #001b25); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }`,
];
var className3 = "framer-lmVrI";

// /:https://framerusercontent.com/modules/3Flblm4Kd3FImOl0KgXu/0yumdd7LUKbDznZIQ57H/D9txnb0Wf.js
import { fontStore as fontStore2 } from "unframer";
fontStore2.loadFonts([
	"GF;IBM Plex Sans-300",
	"GF;IBM Plex Sans-regular",
	"GF;IBM Plex Sans-italic",
	"GF;IBM Plex Sans-300italic",
]);
var fonts4 = [
	{
		explicitInter: true,
		fonts: [
			{
				cssFamilyName: "IBM Plex Sans",
				openType: true,
				source: "google",
				style: "normal",
				uiFamilyName: "IBM Plex Sans",
				url: "https://fonts.gstatic.com/s/ibmplexsans/v23/zYXGKVElMYYaJe8bpLHnCwDKr932-G7dytD-Dmu1swZSAXcomDVmadSDtFlzBaI5loa26g.woff2",
				weight: "300",
			},
			{
				cssFamilyName: "IBM Plex Sans",
				openType: true,
				source: "google",
				style: "normal",
				uiFamilyName: "IBM Plex Sans",
				url: "https://fonts.gstatic.com/s/ibmplexsans/v23/zYXGKVElMYYaJe8bpLHnCwDKr932-G7dytD-Dmu1swZSAXcomDVmadSD6llzBaI5loa26g.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "IBM Plex Sans",
				openType: true,
				source: "google",
				style: "italic",
				uiFamilyName: "IBM Plex Sans",
				url: "https://fonts.gstatic.com/s/ibmplexsans/v23/zYXEKVElMYYaJe8bpLHnCwDKhdTEG46kmUZQCX598fQbM4jw8V78x9OWIhqbQ6g4tIOm6vje.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "IBM Plex Sans",
				openType: true,
				source: "google",
				style: "italic",
				uiFamilyName: "IBM Plex Sans",
				url: "https://fonts.gstatic.com/s/ibmplexsans/v23/zYXEKVElMYYaJe8bpLHnCwDKhdTEG46kmUZQCX598fQbM4jw8V78x9OWIhrFQ6g4tIOm6vje.woff2",
				weight: "300",
			},
		],
	},
];
var css4 = [
	`.framer-2MWYM .framer-styles-preset-vhm2im:not(.rich-text-wrapper), .framer-2MWYM .framer-styles-preset-vhm2im.rich-text-wrapper p { --framer-font-family: "IBM Plex Sans", "IBM Plex Sans Placeholder", sans-serif; --framer-font-family-bold: "IBM Plex Sans", "IBM Plex Sans Placeholder", sans-serif; --framer-font-family-bold-italic: "IBM Plex Sans", "IBM Plex Sans Placeholder", sans-serif; --framer-font-family-italic: "IBM Plex Sans", "IBM Plex Sans Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 20px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 300; --framer-font-weight-bold: 400; --framer-font-weight-bold-italic: 400; --framer-font-weight-italic: 300; --framer-letter-spacing: -0.02em; --framer-line-height: 1.4em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-99df6449-e9f2-4797-8ee6-4b98273d37fc, #001b25); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }`,
	`@media (max-width: 1199px) and (min-width: 390px) { .framer-2MWYM .framer-styles-preset-vhm2im:not(.rich-text-wrapper), .framer-2MWYM .framer-styles-preset-vhm2im.rich-text-wrapper p { --framer-font-family: "IBM Plex Sans", "IBM Plex Sans Placeholder", sans-serif; --framer-font-family-bold: "IBM Plex Sans", "IBM Plex Sans Placeholder", sans-serif; --framer-font-family-bold-italic: "IBM Plex Sans", "IBM Plex Sans Placeholder", sans-serif; --framer-font-family-italic: "IBM Plex Sans", "IBM Plex Sans Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 14px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 300; --framer-font-weight-bold: 400; --framer-font-weight-bold-italic: 400; --framer-font-weight-italic: 300; --framer-letter-spacing: -0.02em; --framer-line-height: 1.4em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-99df6449-e9f2-4797-8ee6-4b98273d37fc, #001b25); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }`,
	`@media (max-width: 389px) and (min-width: 0px) { .framer-2MWYM .framer-styles-preset-vhm2im:not(.rich-text-wrapper), .framer-2MWYM .framer-styles-preset-vhm2im.rich-text-wrapper p { --framer-font-family: "IBM Plex Sans", "IBM Plex Sans Placeholder", sans-serif; --framer-font-family-bold: "IBM Plex Sans", "IBM Plex Sans Placeholder", sans-serif; --framer-font-family-bold-italic: "IBM Plex Sans", "IBM Plex Sans Placeholder", sans-serif; --framer-font-family-italic: "IBM Plex Sans", "IBM Plex Sans Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 14px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 300; --framer-font-weight-bold: 400; --framer-font-weight-bold-italic: 400; --framer-font-weight-italic: 300; --framer-letter-spacing: -0.02em; --framer-line-height: 1.4em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-99df6449-e9f2-4797-8ee6-4b98273d37fc, #001b25); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }`,
];
var className4 = "framer-2MWYM";

// /:https://framerusercontent.com/modules/eHBQSXDPGTuFzsV1cVYg/kPzrWJZvsBgJdoY8ehex/iYwQaI7eX.js
import { fontStore as fontStore3 } from "unframer";
fontStore3.loadFonts([]);
var fonts5 = [
	{
		explicitInter: true,
		fonts: [],
	},
];
var css5 = [
	".framer-4PWK6 .framer-styles-preset-164fi7s:not(.rich-text-wrapper), .framer-4PWK6 .framer-styles-preset-164fi7s.rich-text-wrapper a { --framer-link-text-color: var(--token-99df6449-e9f2-4797-8ee6-4b98273d37fc, #001b25); }",
];
var className5 = "framer-4PWK6";

// /:https://framerusercontent.com/modules/Cbrf5gPbdFHBiXpDV0n8/MABDUXr0DslekIL7LntH/cx7WayR4m.js
var ArrowUpRightFonts = getFonts(stdin_default);
var CaptionsFonts = getFonts(stdin_default2);
var LiveDotFonts = getFonts(LiveDot);
var enabledGestures = {
	bEMSO5yPY: {
		hover: true,
	},
};
var cycleOrder = ["bEMSO5yPY", "QHtLySL9G"];
var serializationHash = "framer-PxCqC";
var variantClassNames = {
	bEMSO5yPY: "framer-v-npkxw3",
	QHtLySL9G: "framer-v-c6w1zd",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.3,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"Variant 1": "bEMSO5yPY",
	"Variant 2": "QHtLySL9G",
};
var Variants = motion.create(React.Fragment);
var getProps = ({
	companyName,
	height,
	id,
	link,
	position,
	showLiveBadge,
	width,
	year,
	...props
}) => {
	return {
		...props,
		FZVO6gzbr: showLiveBadge ?? props.FZVO6gzbr ?? true,
		jILoRsDZN: year ?? props.jILoRsDZN ?? "Feb 2025 \u2014 Present",
		LutAqaxi8: link ?? props.LutAqaxi8,
		rQhjBRcxV: companyName ?? props.rQhjBRcxV ?? "Portkey",
		TOt_Vs4aM: position ?? props.TOt_Vs4aM ?? "Director of design",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "bEMSO5yPY",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className6,
		layoutId,
		variant,
		rQhjBRcxV: rQhjBRcxV2,
		TOt_Vs4aM: TOt_Vs4aM2,
		jILoRsDZN: jILoRsDZN2,
		FZVO6gzbr: FZVO6gzbr2,
		LutAqaxi8: LutAqaxi82,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "bEMSO5yPY",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTaph48vuq = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("QHtLySL9G");
	});
	const onTapkpx2h1 = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("bEMSO5yPY");
	});
	const sharedStyleClassNames = [
		className3,
		className5,
		className4,
		className,
		className2,
	];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "QHtLySL9G") return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (gestureVariant === "bEMSO5yPY-hover") return true;
		return false;
	};
	const isDisplayed2 = () => {
		if (baseVariant === "QHtLySL9G") return true;
		return false;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-npkxw3",
							className6,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Variant 1"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"bEMSO5yPY"}
						onTap={onTaph48vuq}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-c1b219e1-f175-48e0-870c-d1ed2360074b, rgb(237, 237, 237))",
							"--border-left-width": "0px",
							"--border-right-width": "0px",
							"--border-style": "solid",
							"--border-top-width": "0px",
							...style,
						}}
						{...addPropertyOverrides(
							{
								"bEMSO5yPY-hover": {
									"data-framer-name": void 0,
								},
								QHtLySL9G: {
									"data-framer-name": "Variant 2",
									onTap: onTapkpx2h1,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						{isDisplayed() && (
							<Transition value={transition1}>
								<motion.div
									className={"framer-8uaukc"}
									layoutDependency={layoutDependency}
									layoutId={"DCtgyhYgz"}
								>
									<Transition value={transition1}>
										<motion.div
											className={"framer-p1rzrc"}
											layoutDependency={layoutDependency}
											layoutId={"DFbLds5x7"}
										>
											<motion.div
												className={"framer-wsv0nt"}
												layoutDependency={layoutDependency}
												layoutId={"WEXhTsWKS"}
											>
												<Transition value={transition1}>
													<motion.div
														className={"framer-1ogmnnc"}
														layoutDependency={layoutDependency}
														layoutId={"gGgTVMbnW"}
													>
														<motion.div
															className={"framer-v64ovi"}
															layoutDependency={layoutDependency}
															layoutId={"RTbmJ_BpY"}
														>
															<Transition value={transition1}>
																<RichText
																	__fromCanvasComponent={true}
																	className={"framer-1pkcj5p"}
																	fonts={["Inter"]}
																	layoutDependency={layoutDependency}
																	layoutId={"naHvEtuU9"}
																	text={rQhjBRcxV2}
																	verticalAlignment={"top"}
																	withExternalLayout={true}
																>
																	<React.Fragment>
																		<motion.p
																			className={"framer-styles-preset-kwafes"}
																			data-styles-preset={"BFyu0Sm3h"}
																			dir={"auto"}
																		>
																			<Link
																				href={"https://portkey.ai/"}
																				motionChild={true}
																				nodeId={"naHvEtuU9"}
																				openInNewTab={true}
																				relValues={[]}
																				scopeId={"cx7WayR4m"}
																				smoothScroll={false}
																			>
																				<motion.a
																					className={
																						"framer-styles-preset-164fi7s"
																					}
																					data-styles-preset={"iYwQaI7eX"}
																				>
																					{"Portkey"}
																				</motion.a>
																			</Link>
																		</motion.p>
																	</React.Fragment>
																</RichText>
															</Transition>
															{isDisplayed1() && (
																<Link
																	href={LutAqaxi82}
																	motionChild={true}
																	nodeId={"JuA_fbavN"}
																	openInNewTab={true}
																	scopeId={"cx7WayR4m"}
																>
																	<motion.a
																		className={"framer-1ee46hj framer-6fu9tx"}
																		layoutDependency={layoutDependency}
																		layoutId={"JuA_fbavN"}
																	>
																		{isDisplayed1() &&
																			_jsx(stdin_default, {
																				animated: true,
																				className: "framer-1g0395",
																				layoutDependency,
																				layoutId: "XA28f0YuC",
																				style: {
																					"--43q7um":
																						"var(--token-c7046da6-529c-4bf7-84f8-82aca30594c1, rgb(0, 0, 0))",
																				},
																			})}
																	</motion.a>
																</Link>
															)}
														</motion.div>
														<Transition value={transition1}>
															<RichText
																__fromCanvasComponent={true}
																className={"framer-1o999rd"}
																fonts={["GF;Bricolage Grotesque-300"]}
																layoutDependency={layoutDependency}
																layoutId={"WtHaNFe4g"}
																style={{
																	"--extracted-r6o4lv": "rgb(99, 99, 99)",
																	"--framer-link-text-color":
																		"rgb(0, 153, 255)",
																	"--framer-link-text-decoration": "underline",
																}}
																text={TOt_Vs4aM2}
																verticalAlignment={"top"}
																withExternalLayout={true}
															>
																<React.Fragment>
																	<motion.p
																		dir={"auto"}
																		style={{
																			"--font-selector":
																				"R0Y7QnJpY29sYWdlIEdyb3Rlc3F1ZS0zMDA=",
																			"--framer-font-family":
																				'"Bricolage Grotesque", "Bricolage Grotesque Placeholder", sans-serif',
																			"--framer-font-open-type-features":
																				"'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on",
																			"--framer-font-size": "18px",
																			"--framer-font-weight": "300",
																			"--framer-letter-spacing": "-0.02em",
																			"--framer-line-height": "1.4em",
																			"--framer-text-color":
																				"var(--extracted-r6o4lv, rgb(99, 99, 99))",
																		}}
																	>
																		{"Director of design"}
																	</motion.p>
																</React.Fragment>
															</RichText>
														</Transition>
													</motion.div>
												</Transition>
											</motion.div>
											<Transition value={transition1}>
												<RichText
													__fromCanvasComponent={true}
													className={"framer-zowapo"}
													fonts={["GF;Bricolage Grotesque-300"]}
													layoutDependency={layoutDependency}
													layoutId={"aq_Ys3bFi"}
													style={{
														"--extracted-r6o4lv": "rgb(99, 99, 99)",
														"--framer-link-text-color": "rgb(0, 153, 255)",
														"--framer-link-text-decoration": "underline",
													}}
													text={jILoRsDZN2}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React.Fragment>
														<motion.p
															dir={"auto"}
															style={{
																"--font-selector":
																	"R0Y7QnJpY29sYWdlIEdyb3Rlc3F1ZS0zMDA=",
																"--framer-font-family":
																	'"Bricolage Grotesque", "Bricolage Grotesque Placeholder", sans-serif',
																"--framer-font-open-type-features":
																	"'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on",
																"--framer-font-size": "18px",
																"--framer-font-weight": "300",
																"--framer-letter-spacing": "-0.02em",
																"--framer-line-height": "1.4em",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, rgb(99, 99, 99))",
															}}
														>
															{"Feb 2025 \u2014 Present"}
														</motion.p>
													</React.Fragment>
												</RichText>
											</Transition>
										</motion.div>
									</Transition>
								</motion.div>
							</Transition>
						)}
						{isDisplayed2() && (
							<motion.div
								className={"framer-1bqievh"}
								layoutDependency={layoutDependency}
								layoutId={"nzNGS1i8e"}
							>
								<Transition value={transition1}>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-aubzk1"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"bRQokzRnJ"}
										style={{
											"--extracted-r6o4lv": "rgb(99, 99, 99)",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-vhm2im"}
												data-styles-preset={"D9txnb0Wf"}
												dir={"auto"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgb(99, 99, 99))",
												}}
											>
												{
													"Design leadership drove massive results for a generative AI platform: 1,000+ organizations adopted it, contributing to $5M in revenue. I boosted conversion by 32%, delivered 70% faster workflows and 45% higher retention, and cut design-to-dev time by 50%. Show More"
												}
											</motion.p>
										</React.Fragment>
									</RichText>
								</Transition>
								{isDisplayed2() && (
									<motion.div
										className={"framer-15rz35u"}
										layoutDependency={layoutDependency}
										layoutId={"Zrh5nl52t"}
									>
										{isDisplayed2() && (
											<ComponentViewportProvider
												{...addPropertyOverrides(
													{
														QHtLySL9G: {
															height: 23,
															y:
																(componentViewport?.y || 0) +
																24 +
																((componentViewport?.height || 200) -
																	84 -
																	671 +
																	156 +
																	32) +
																0 +
																156 +
																0,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<SmartComponentScopedContainer
													className={"framer-mia3x4-container"}
													layoutDependency={layoutDependency}
													layoutId={"SuGqUIFib-container"}
													nodeId={"SuGqUIFib"}
													rendersWithMotion={true}
													scopeId={"cx7WayR4m"}
												>
													{_jsx(stdin_default2, {
														height: "100%",
														id: "SuGqUIFib",
														jsZKsn85x: "UX STRATEGY",
														layoutId: "SuGqUIFib",
														width: "100%",
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										)}
										{isDisplayed2() && (
											<ComponentViewportProvider
												{...addPropertyOverrides(
													{
														QHtLySL9G: {
															height: 23,
															y:
																(componentViewport?.y || 0) +
																24 +
																((componentViewport?.height || 200) -
																	84 -
																	671 +
																	156 +
																	32) +
																0 +
																156 +
																0,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<SmartComponentScopedContainer
													className={"framer-1wr2k9x-container"}
													layoutDependency={layoutDependency}
													layoutId={"xdLuam637-container"}
													nodeId={"xdLuam637"}
													rendersWithMotion={true}
													scopeId={"cx7WayR4m"}
												>
													{_jsx(stdin_default2, {
														height: "100%",
														id: "xdLuam637",
														jsZKsn85x: "UX STRATEGY",
														layoutId: "xdLuam637",
														width: "100%",
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										)}
										<ComponentViewportProvider
											height={23}
											{...addPropertyOverrides(
												{
													QHtLySL9G: {
														y:
															(componentViewport?.y || 0) +
															24 +
															((componentViewport?.height || 200) -
																84 -
																671 +
																156 +
																32) +
															0 +
															156 +
															0,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainer
												className={"framer-kws4xp-container"}
												layoutDependency={layoutDependency}
												layoutId={"nB43StJDm-container"}
												nodeId={"nB43StJDm"}
												rendersWithMotion={true}
												scopeId={"cx7WayR4m"}
											>
												{_jsx(stdin_default2, {
													height: "100%",
													id: "nB43StJDm",
													jsZKsn85x: "UX STRATEGY",
													layoutId: "nB43StJDm",
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
										<ComponentViewportProvider
											height={23}
											{...addPropertyOverrides(
												{
													QHtLySL9G: {
														y:
															(componentViewport?.y || 0) +
															24 +
															((componentViewport?.height || 200) -
																84 -
																671 +
																156 +
																32) +
															0 +
															156 +
															0,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainer
												className={"framer-sdk4mg-container"}
												layoutDependency={layoutDependency}
												layoutId={"IGWMJBYGQ-container"}
												nodeId={"IGWMJBYGQ"}
												rendersWithMotion={true}
												scopeId={"cx7WayR4m"}
											>
												{_jsx(stdin_default2, {
													height: "100%",
													id: "IGWMJBYGQ",
													jsZKsn85x: "UX STRATEGY",
													layoutId: "IGWMJBYGQ",
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
										<ComponentViewportProvider
											height={23}
											{...addPropertyOverrides(
												{
													QHtLySL9G: {
														y:
															(componentViewport?.y || 0) +
															24 +
															((componentViewport?.height || 200) -
																84 -
																671 +
																156 +
																32) +
															0 +
															156 +
															0,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainer
												className={"framer-1uuxalr-container"}
												layoutDependency={layoutDependency}
												layoutId={"zQxn1qB8t-container"}
												nodeId={"zQxn1qB8t"}
												rendersWithMotion={true}
												scopeId={"cx7WayR4m"}
											>
												{_jsx(stdin_default2, {
													height: "100%",
													id: "zQxn1qB8t",
													jsZKsn85x: "UX STRATEGY",
													layoutId: "zQxn1qB8t",
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
									</motion.div>
								)}
							</motion.div>
						)}
						{isDisplayed2() && (
							<Transition value={transition1}>
								<motion.div
									className={"framer-1426ui0"}
									layoutDependency={layoutDependency}
									layoutId={"FEjb68hOr"}
								>
									<Transition value={transition1}>
										<motion.div
											className={"framer-18hbhq"}
											layoutDependency={layoutDependency}
											layoutId={"GhIkWImw3"}
										>
											<Transition value={transition1}>
												<RichText
													__fromCanvasComponent={true}
													className={"framer-1az22h1"}
													fonts={["GF;Bricolage Grotesque-300"]}
													layoutDependency={layoutDependency}
													layoutId={"nnbTgFaKp"}
													style={{
														"--extracted-r6o4lv": "rgb(99, 99, 99)",
														"--framer-link-text-color": "rgb(0, 153, 255)",
														"--framer-link-text-decoration": "underline",
													}}
													text={jILoRsDZN2}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React.Fragment>
														<motion.p
															dir={"auto"}
															style={{
																"--font-selector":
																	"R0Y7QnJpY29sYWdlIEdyb3Rlc3F1ZS0zMDA=",
																"--framer-font-family":
																	'"Bricolage Grotesque", "Bricolage Grotesque Placeholder", sans-serif',
																"--framer-font-open-type-features":
																	"'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on",
																"--framer-font-size": "18px",
																"--framer-font-weight": "300",
																"--framer-letter-spacing": "-0.02em",
																"--framer-line-height": "1.4em",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, rgb(99, 99, 99))",
															}}
														>
															{"Feb 2025 \u2014 Present"}
														</motion.p>
													</React.Fragment>
												</RichText>
											</Transition>
											<motion.div
												className={"framer-1d2ujs5"}
												layoutDependency={layoutDependency}
												layoutId={"HrW1uEpRn"}
											>
												<motion.div
													className={"framer-fn9evr"}
													data-border={true}
													layoutDependency={layoutDependency}
													layoutId={"FVUdoWCrr"}
													style={{
														"--border-bottom-width": "1px",
														"--border-color":
															"var(--token-c1b219e1-f175-48e0-870c-d1ed2360074b, rgb(237, 237, 237))",
														"--border-left-width": "1px",
														"--border-right-width": "1px",
														"--border-style": "solid",
														"--border-top-width": "1px",
														backgroundColor:
															"var(--token-06cbdf7a-4b04-4493-a020-8aa6e2439856, rgb(245, 245, 245))",
														borderBottomLeftRadius: 12,
														borderBottomRightRadius: 12,
														borderTopLeftRadius: 12,
														borderTopRightRadius: 12,
													}}
												/>
												<Transition value={transition1}>
													<motion.div
														className={"framer-1g5nws3"}
														layoutDependency={layoutDependency}
														layoutId={"dfMKt5zbX"}
													>
														<motion.div
															className={"framer-126wvdk"}
															layoutDependency={layoutDependency}
															layoutId={"hBN1Rlx2i"}
														>
															<Transition value={transition1}>
																<RichText
																	__fromCanvasComponent={true}
																	className={"framer-tfmfh"}
																	fonts={["Inter"]}
																	layoutDependency={layoutDependency}
																	layoutId={"XtWak9m6H"}
																	text={rQhjBRcxV2}
																	verticalAlignment={"top"}
																	withExternalLayout={true}
																>
																	<React.Fragment>
																		<motion.p
																			className={"framer-styles-preset-kwafes"}
																			data-styles-preset={"BFyu0Sm3h"}
																			dir={"auto"}
																		>
																			<Link
																				href={"https://portkey.ai/"}
																				motionChild={true}
																				nodeId={"XtWak9m6H"}
																				openInNewTab={true}
																				relValues={[]}
																				scopeId={"cx7WayR4m"}
																				smoothScroll={false}
																			>
																				<motion.a
																					className={
																						"framer-styles-preset-164fi7s"
																					}
																					data-styles-preset={"iYwQaI7eX"}
																				>
																					{"Portkey"}
																				</motion.a>
																			</Link>
																		</motion.p>
																	</React.Fragment>
																</RichText>
															</Transition>
															<Link
																href={LutAqaxi82}
																motionChild={true}
																nodeId={"YyrKADkBv"}
																openInNewTab={true}
																scopeId={"cx7WayR4m"}
															>
																<motion.a
																	className={"framer-1cywmxq framer-6fu9tx"}
																	layoutDependency={layoutDependency}
																	layoutId={"YyrKADkBv"}
																>
																	{_jsx(stdin_default, {
																		animated: true,
																		className: "framer-1gdbpkl",
																		layoutDependency,
																		layoutId: "At3MNnsWW",
																		style: {
																			"--43q7um":
																				"var(--token-c7046da6-529c-4bf7-84f8-82aca30594c1, rgb(0, 0, 0))",
																		},
																	})}
																</motion.a>
															</Link>
															{FZVO6gzbr2 !== false && (
																<ComponentViewportProvider>
																	<SmartComponentScopedContainer
																		className={"framer-1tonsho-container"}
																		data-code-component-plugin-id={"84d4c1"}
																		isAuthoredByUser={true}
																		layoutDependency={layoutDependency}
																		layoutId={"pWK1OkkTY-container"}
																		nodeId={"pWK1OkkTY"}
																		rendersWithMotion={true}
																		scopeId={"cx7WayR4m"}
																	>
																		<LiveDot
																			animationSpeed={3}
																			dotColor={"rgb(34, 204, 102)"}
																			height={"100%"}
																			id={"pWK1OkkTY"}
																			layoutId={"pWK1OkkTY"}
																			pulseColor={"rgb(34, 204, 102)"}
																			showOnCanvas={true}
																			size={12}
																			style={{
																				height: "100%",
																				width: "100%",
																			}}
																			width={"100%"}
																		/>
																	</SmartComponentScopedContainer>
																</ComponentViewportProvider>
															)}
														</motion.div>
														<Transition value={transition1}>
															<RichText
																__fromCanvasComponent={true}
																className={"framer-ettbzw"}
																fonts={["GF;Bricolage Grotesque-300"]}
																layoutDependency={layoutDependency}
																layoutId={"ucN95fkJw"}
																style={{
																	"--extracted-r6o4lv": "rgb(99, 99, 99)",
																	"--framer-link-text-color":
																		"rgb(0, 153, 255)",
																	"--framer-link-text-decoration": "underline",
																}}
																text={TOt_Vs4aM2}
																verticalAlignment={"top"}
																withExternalLayout={true}
															>
																<React.Fragment>
																	<motion.p
																		dir={"auto"}
																		style={{
																			"--font-selector":
																				"R0Y7QnJpY29sYWdlIEdyb3Rlc3F1ZS0zMDA=",
																			"--framer-font-family":
																				'"Bricolage Grotesque", "Bricolage Grotesque Placeholder", sans-serif',
																			"--framer-font-open-type-features":
																				"'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on",
																			"--framer-font-size": "18px",
																			"--framer-font-weight": "300",
																			"--framer-letter-spacing": "-0.02em",
																			"--framer-line-height": "1.4em",
																			"--framer-text-color":
																				"var(--extracted-r6o4lv, rgb(99, 99, 99))",
																		}}
																	>
																		{"Director of design"}
																	</motion.p>
																</React.Fragment>
															</RichText>
														</Transition>
													</motion.div>
												</Transition>
											</motion.div>
										</motion.div>
									</Transition>
								</motion.div>
							</Transition>
						)}
						{isDisplayed2() && (
							<motion.div
								className={"framer-1oc1x75"}
								layoutDependency={layoutDependency}
								layoutId={"GhbXAScIj"}
							>
								{isDisplayed2() && (
									<Transition value={transition1}>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-9bc2jl"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"y2Qe79fpv"}
											style={{
												"--extracted-r6o4lv": "rgb(99, 99, 99)",
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-1vpqesh"}
													data-styles-preset={"eO0w7qcNn"}
													dir={"auto"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, rgb(99, 99, 99))",
													}}
												>
													{"Impact"}
												</motion.p>
											</React.Fragment>
										</RichText>
									</Transition>
								)}
								{isDisplayed2() && (
									<motion.div
										className={"framer-8lh7el"}
										layoutDependency={layoutDependency}
										layoutId={"plV89ort7"}
									>
										{isDisplayed2() && (
											<motion.div
												className={"framer-vo4qhm"}
												layoutDependency={layoutDependency}
												layoutId={"JyJCLHwuo"}
											>
												{isDisplayed2() && (
													<Transition value={transition1}>
														<RichText
															__fromCanvasComponent={true}
															className={"framer-zkix4x"}
															fonts={["GF;IBM Plex Mono-500"]}
															layoutDependency={layoutDependency}
															layoutId={"oTgv8Lrcd"}
															style={{
																"--extracted-r6o4lv":
																	"var(--token-17586cc6-b205-4368-ade3-9f0f26d38021, rgb(255, 85, 24))",
																"--framer-link-text-color": "rgb(0, 153, 255)",
																"--framer-link-text-decoration": "underline",
															}}
															verticalAlignment={"top"}
															withExternalLayout={true}
														>
															<React.Fragment>
																<motion.p
																	dir={"auto"}
																	style={{
																		"--font-selector":
																			"R0Y7SUJNIFBsZXggTW9uby01MDA=",
																		"--framer-font-family":
																			'"IBM Plex Mono", monospace',
																		"--framer-font-open-type-features":
																			"'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on",
																		"--framer-font-size": "20px",
																		"--framer-font-weight": "500",
																		"--framer-letter-spacing": "-0.02em",
																		"--framer-line-height": "1.4em",
																		"--framer-text-color":
																			"var(--extracted-r6o4lv, var(--token-17586cc6-b205-4368-ade3-9f0f26d38021, rgb(255, 85, 24)))",
																	}}
																>
																	{"149%"}
																</motion.p>
															</React.Fragment>
														</RichText>
													</Transition>
												)}
												{isDisplayed2() && (
													<Transition value={transition1}>
														<RichText
															__fromCanvasComponent={true}
															className={"framer-i2xxen"}
															fonts={["Inter"]}
															layoutDependency={layoutDependency}
															layoutId={"Kwle4VhHf"}
															style={{
																"--extracted-r6o4lv": "rgb(99, 99, 99)",
																"--framer-link-text-color": "rgb(0, 153, 255)",
																"--framer-link-text-decoration": "underline",
															}}
															verticalAlignment={"top"}
															withExternalLayout={true}
														>
															<React.Fragment>
																<motion.p
																	className={"framer-styles-preset-fjetpu"}
																	data-styles-preset={"FIucEdDai"}
																	dir={"auto"}
																	style={{
																		"--framer-text-color":
																			"var(--extracted-r6o4lv, rgb(99, 99, 99))",
																	}}
																>
																	{"Impact"}
																</motion.p>
															</React.Fragment>
														</RichText>
													</Transition>
												)}
											</motion.div>
										)}
										{isDisplayed2() && (
											<motion.div
												className={"framer-gcusux"}
												layoutDependency={layoutDependency}
												layoutId={"KKjTkdxqU"}
											>
												<Transition value={transition1}>
													<RichText
														__fromCanvasComponent={true}
														className={"framer-1orue0z"}
														fonts={["GF;IBM Plex Mono-500"]}
														layoutDependency={layoutDependency}
														layoutId={"IvSQTAhoS"}
														style={{
															"--extracted-r6o4lv":
																"var(--token-17586cc6-b205-4368-ade3-9f0f26d38021, rgb(255, 85, 24))",
															"--framer-link-text-color": "rgb(0, 153, 255)",
															"--framer-link-text-decoration": "underline",
														}}
														verticalAlignment={"top"}
														withExternalLayout={true}
													>
														<React.Fragment>
															<motion.p
																dir={"auto"}
																style={{
																	"--font-selector":
																		"R0Y7SUJNIFBsZXggTW9uby01MDA=",
																	"--framer-font-family":
																		'"IBM Plex Mono", monospace',
																	"--framer-font-open-type-features":
																		"'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on",
																	"--framer-font-size": "20px",
																	"--framer-font-weight": "500",
																	"--framer-letter-spacing": "-0.02em",
																	"--framer-line-height": "1.4em",
																	"--framer-text-color":
																		"var(--extracted-r6o4lv, var(--token-17586cc6-b205-4368-ade3-9f0f26d38021, rgb(255, 85, 24)))",
																}}
															>
																{"149%"}
															</motion.p>
														</React.Fragment>
													</RichText>
												</Transition>
												<Transition value={transition1}>
													<RichText
														__fromCanvasComponent={true}
														className={"framer-usq0vh"}
														fonts={["Inter"]}
														layoutDependency={layoutDependency}
														layoutId={"yjyzI4NLL"}
														style={{
															"--extracted-r6o4lv": "rgb(99, 99, 99)",
															"--framer-link-text-color": "rgb(0, 153, 255)",
															"--framer-link-text-decoration": "underline",
														}}
														verticalAlignment={"top"}
														withExternalLayout={true}
													>
														<React.Fragment>
															<motion.p
																className={"framer-styles-preset-fjetpu"}
																data-styles-preset={"FIucEdDai"}
																dir={"auto"}
																style={{
																	"--framer-text-color":
																		"var(--extracted-r6o4lv, rgb(99, 99, 99))",
																}}
															>
																{"Impact"}
															</motion.p>
														</React.Fragment>
													</RichText>
												</Transition>
											</motion.div>
										)}
										{isDisplayed2() && (
											<motion.div
												className={"framer-12fhcx2"}
												layoutDependency={layoutDependency}
												layoutId={"OE07KnAaa"}
											>
												<Transition value={transition1}>
													<RichText
														__fromCanvasComponent={true}
														className={"framer-1oqd9ov"}
														fonts={["GF;IBM Plex Mono-500"]}
														layoutDependency={layoutDependency}
														layoutId={"tuOadtKvA"}
														style={{
															"--extracted-r6o4lv":
																"var(--token-17586cc6-b205-4368-ade3-9f0f26d38021, rgb(255, 85, 24))",
															"--framer-link-text-color": "rgb(0, 153, 255)",
															"--framer-link-text-decoration": "underline",
														}}
														verticalAlignment={"top"}
														withExternalLayout={true}
													>
														<React.Fragment>
															<motion.p
																dir={"auto"}
																style={{
																	"--font-selector":
																		"R0Y7SUJNIFBsZXggTW9uby01MDA=",
																	"--framer-font-family":
																		'"IBM Plex Mono", monospace',
																	"--framer-font-open-type-features":
																		"'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on",
																	"--framer-font-size": "20px",
																	"--framer-font-weight": "500",
																	"--framer-letter-spacing": "-0.02em",
																	"--framer-line-height": "1.4em",
																	"--framer-text-color":
																		"var(--extracted-r6o4lv, var(--token-17586cc6-b205-4368-ade3-9f0f26d38021, rgb(255, 85, 24)))",
																}}
															>
																{"149%"}
															</motion.p>
														</React.Fragment>
													</RichText>
												</Transition>
												<Transition value={transition1}>
													<RichText
														__fromCanvasComponent={true}
														className={"framer-110j35n"}
														fonts={["Inter"]}
														layoutDependency={layoutDependency}
														layoutId={"YXKdhjdL_"}
														style={{
															"--extracted-r6o4lv": "rgb(99, 99, 99)",
															"--framer-link-text-color": "rgb(0, 153, 255)",
															"--framer-link-text-decoration": "underline",
														}}
														verticalAlignment={"top"}
														withExternalLayout={true}
													>
														<React.Fragment>
															<motion.p
																className={"framer-styles-preset-fjetpu"}
																data-styles-preset={"FIucEdDai"}
																dir={"auto"}
																style={{
																	"--framer-text-color":
																		"var(--extracted-r6o4lv, rgb(99, 99, 99))",
																}}
															>
																{"Impact"}
															</motion.p>
														</React.Fragment>
													</RichText>
												</Transition>
											</motion.div>
										)}
										<motion.div
											className={"framer-63ftob"}
											layoutDependency={layoutDependency}
											layoutId={"OvNrYbges"}
										>
											<Transition value={transition1}>
												<RichText
													__fromCanvasComponent={true}
													className={"framer-bupwuw"}
													fonts={["GF;IBM Plex Mono-500"]}
													layoutDependency={layoutDependency}
													layoutId={"FZwycZ7nc"}
													style={{
														"--extracted-r6o4lv":
															"var(--token-17586cc6-b205-4368-ade3-9f0f26d38021, rgb(255, 85, 24))",
														"--framer-link-text-color": "rgb(0, 153, 255)",
														"--framer-link-text-decoration": "underline",
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React.Fragment>
														<motion.p
															dir={"auto"}
															style={{
																"--font-selector":
																	"R0Y7SUJNIFBsZXggTW9uby01MDA=",
																"--framer-font-family":
																	'"IBM Plex Mono", monospace',
																"--framer-font-open-type-features":
																	"'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on",
																"--framer-font-size": "20px",
																"--framer-font-weight": "500",
																"--framer-letter-spacing": "-0.02em",
																"--framer-line-height": "1.4em",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-17586cc6-b205-4368-ade3-9f0f26d38021, rgb(255, 85, 24)))",
															}}
														>
															{"149%"}
														</motion.p>
													</React.Fragment>
												</RichText>
											</Transition>
											<Transition value={transition1}>
												<RichText
													__fromCanvasComponent={true}
													className={"framer-13kp0um"}
													fonts={["Inter"]}
													layoutDependency={layoutDependency}
													layoutId={"OZDlY6n7H"}
													style={{
														"--extracted-r6o4lv": "rgb(99, 99, 99)",
														"--framer-link-text-color": "rgb(0, 153, 255)",
														"--framer-link-text-decoration": "underline",
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-fjetpu"}
															data-styles-preset={"FIucEdDai"}
															dir={"auto"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, rgb(99, 99, 99))",
															}}
														>
															{"Impact"}
														</motion.p>
													</React.Fragment>
												</RichText>
											</Transition>
										</motion.div>
									</motion.div>
								)}
							</motion.div>
						)}
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css6 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-PxCqC.framer-6fu9tx, .framer-PxCqC .framer-6fu9tx { display: block; }",
	".framer-PxCqC.framer-npkxw3 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-end; overflow: visible; padding: 24px 10px 24px 0px; position: relative; width: 1000px; }",
	".framer-PxCqC .framer-8uaukc, .framer-PxCqC .framer-1426ui0 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-PxCqC .framer-p1rzrc { align-content: flex-end; align-items: flex-end; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 56px; height: min-content; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 1px; }",
	".framer-PxCqC .framer-wsv0nt { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 729px; }",
	".framer-PxCqC .framer-1ogmnnc { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 6px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-PxCqC .framer-v64ovi, .framer-PxCqC .framer-126wvdk { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-PxCqC .framer-1pkcj5p { flex: 1 0 0px; height: auto; max-width: 75%; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-PxCqC .framer-1ee46hj { flex: none; height: 16px; overflow: visible; position: relative; text-decoration: none; width: 16px; }",
	".framer-PxCqC .framer-1g0395, .framer-PxCqC .framer-1gdbpkl { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 16px); left: 0px; position: absolute; right: 0px; top: 0px; width: calc(100% - 0px); }",
	".framer-PxCqC .framer-1o999rd, .framer-PxCqC .framer-aubzk1 { flex: none; height: auto; max-width: 100%; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-PxCqC .framer-zowapo, .framer-PxCqC .framer-1az22h1, .framer-PxCqC .framer-tfmfh, .framer-PxCqC .framer-zkix4x, .framer-PxCqC .framer-1orue0z, .framer-PxCqC .framer-1oqd9ov, .framer-PxCqC .framer-bupwuw { flex: none; height: auto; max-width: 75%; position: relative; white-space: pre-wrap; width: auto; word-break: break-word; word-wrap: break-word; }",
	".framer-PxCqC .framer-1bqievh { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-PxCqC .framer-15rz35u { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-PxCqC .framer-mia3x4-container, .framer-PxCqC .framer-1wr2k9x-container, .framer-PxCqC .framer-kws4xp-container, .framer-PxCqC .framer-sdk4mg-container, .framer-PxCqC .framer-1uuxalr-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-PxCqC .framer-18hbhq { align-content: flex-end; align-items: flex-end; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 1px; }",
	".framer-PxCqC .framer-1d2ujs5 { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-PxCqC .framer-fn9evr { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 49px); overflow: visible; position: relative; width: 48px; }",
	".framer-PxCqC .framer-1g5nws3 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 6px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 665px; }",
	".framer-PxCqC .framer-1cywmxq { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 16px); overflow: visible; position: relative; text-decoration: none; width: 16px; }",
	".framer-PxCqC .framer-1tonsho-container { flex: none; height: 24px; position: relative; width: 24px; }",
	".framer-PxCqC .framer-ettbzw { flex: none; height: auto; max-width: 75%; position: relative; white-space: pre-wrap; width: 189px; word-break: break-word; word-wrap: break-word; }",
	".framer-PxCqC .framer-1oc1x75 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; min-height: 112px; min-width: 980px; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-PxCqC .framer-9bc2jl, .framer-PxCqC .framer-i2xxen, .framer-PxCqC .framer-usq0vh, .framer-PxCqC .framer-110j35n, .framer-PxCqC .framer-13kp0um { flex: none; height: auto; max-width: 100%; position: relative; white-space: pre-wrap; width: 980px; word-break: break-word; word-wrap: break-word; }",
	".framer-PxCqC .framer-8lh7el { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 980px; }",
	".framer-PxCqC .framer-vo4qhm { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: flex-start; min-height: 60px; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-PxCqC .framer-gcusux, .framer-PxCqC .framer-12fhcx2, .framer-PxCqC .framer-63ftob { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-PxCqC.framer-v-c6w1zd.framer-npkxw3 { align-content: flex-start; align-items: flex-start; flex-direction: column; gap: 32px; padding: 24px 10px 60px 0px; }",
	".framer-PxCqC.framer-v-c6w1zd .framer-1bqievh { flex: none; order: 2; width: 100%; }",
	".framer-PxCqC.framer-v-c6w1zd .framer-aubzk1, .framer-PxCqC.framer-v-c6w1zd .framer-1d2ujs5 { order: 0; }",
	".framer-PxCqC.framer-v-c6w1zd .framer-15rz35u, .framer-PxCqC.framer-v-c6w1zd .framer-1az22h1 { order: 1; }",
	".framer-PxCqC.framer-v-c6w1zd .framer-1426ui0 { flex: none; order: 1; width: 100%; }",
	".framer-PxCqC.framer-v-c6w1zd .framer-1oc1x75 { min-height: unset; min-width: unset; order: 3; width: 980px; }",
	".framer-PxCqC.framer-v-c6w1zd .framer-vo4qhm { min-height: unset; }",
	".framer-PxCqC.framer-v-npkxw3.hover .framer-1ee46hj { aspect-ratio: 1 / 1; height: var(--framer-aspect-ratio-supported, 16px); }",
	...css3,
	...css5,
	...css4,
	...css,
	...css2,
	'.framer-PxCqC[data-border="true"]::after, .framer-PxCqC [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var Framercx7WayR4m = withCSS(Component, css6, "framer-PxCqC");
var stdin_default3 = Framercx7WayR4m;
Framercx7WayR4m.displayName = "Experience";
Framercx7WayR4m.defaultProps = {
	height: 99,
	width: 1e3,
};
addPropertyControls(Framercx7WayR4m, {
	variant: {
		options: ["bEMSO5yPY", "QHtLySL9G"],
		optionTitles: ["Variant 1", "Variant 2"],
		title: "Variant",
		type: ControlType.Enum,
	},
	rQhjBRcxV: {
		defaultValue: "Portkey",
		displayTextArea: false,
		title: "Company Name",
		type: ControlType.String,
	},
	onrQhjBRcxVChange: {
		changes: "rQhjBRcxV",
		type: ControlType.ChangeHandler,
	},
	TOt_Vs4aM: {
		defaultValue: "Director of design",
		displayTextArea: false,
		title: "Position",
		type: ControlType.String,
	},
	onTOt_Vs4aMChange: {
		changes: "TOt_Vs4aM",
		type: ControlType.ChangeHandler,
	},
	jILoRsDZN: {
		defaultValue: "Feb 2025 \u2014 Present",
		displayTextArea: false,
		title: "Year",
		type: ControlType.String,
	},
	onjILoRsDZNChange: {
		changes: "jILoRsDZN",
		type: ControlType.ChangeHandler,
	},
	FZVO6gzbr: {
		defaultValue: true,
		title: "Show Live Badge",
		type: ControlType.Boolean,
	},
	onFZVO6gzbrChange: {
		changes: "FZVO6gzbr",
		type: ControlType.ChangeHandler,
	},
	LutAqaxi8: {
		title: "Link",
		type: ControlType.Link,
	},
});
addFonts(
	Framercx7WayR4m,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Bricolage Grotesque",
					openType: true,
					source: "google",
					style: "normal",
					uiFamilyName: "Bricolage Grotesque",
					url: "https://fonts.gstatic.com/s/bricolagegrotesque/v9/3y9U6as8bTXq_nANBjzKo3IeZx8z6up5BeSl5jBNz_19PpbpMXuECpwUxJBOm_OJWiaaD30YfKfjZZoLvUXiyMgvs-wJDtw.woff2",
					weight: "300",
				},
				{
					cssFamilyName: "IBM Plex Mono",
					openType: true,
					source: "google",
					style: "normal",
					uiFamilyName: "IBM Plex Mono",
					url: "https://fonts.gstatic.com/s/ibmplexmono/v20/-F6qfjptAgt5VM-kVkqdyU8n3twJ8lJPg-IUDNg.woff2",
					weight: "500",
				},
			],
		},
		...ArrowUpRightFonts,
		...CaptionsFonts,
		...LiveDotFonts,
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts5),
		...getFontsFromSharedStyle(fonts4),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
Framercx7WayR4m.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([forwardLoader(stdin_default2, {}, context)]);
	},
};

// virtual:experience
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"fbc126bea31ebbe6cf64cc6db71380905aa865df749edb6fe0a120a118d79a8c"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ExperienceFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"fbc126bea31ebbe6cf64cc6db71380905aa865df749edb6fe0a120a118d79a8c"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var experience_default = ComponentWithRoot;
export { experience_default as default };
