// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project fbc126bea31ebbe6 "Untitled", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Light' // Variant
 * title?: string // Title
 * onvVwiebfTtChange?: undefined // onvVwiebfTtChange
 * color?: string // Color
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-4KFXLS6S.js";
import { routes } from "./chunks/chunk-2F3PHDTH.js";

// virtual:h-eading-big
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/eWflPxWkVfxdsRoBq0Ri/ChMJFmQn6hjPkkqQuFcB/z6gyV1lHJ.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["wKlgDTIj5", "VlfzGQsk1"];
var serializationHash = "framer-WDLNP";
var variantClassNames = {
	VlfzGQsk1: "framer-v-fj657j",
	wKlgDTIj5: "framer-v-wkccdb",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"Variant 1": "wKlgDTIj5",
	Light: "VlfzGQsk1",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ color, height, id, title, width, ...props }) => {
	return {
		...props,
		UgEqrKjlJ:
			color ??
			props.UgEqrKjlJ ??
			"var(--token-99df6449-e9f2-4797-8ee6-4b98273d37fc, rgb(64, 64, 64))",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "wKlgDTIj5",
		vVwiebfTt: title ?? props.vVwiebfTt ?? "Saff+",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		vVwiebfTt: vVwiebfTt2,
		UgEqrKjlJ: UgEqrKjlJ2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "wKlgDTIj5",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-wkccdb",
							className2,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"wKlgDTIj5"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								VlfzGQsk1: {
									"data-framer-name": "Light",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-oc09er"}
							layoutDependency={layoutDependency}
							layoutId={"iuBdfwIEk"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-3f5dvl"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"R8gbCd2k6"}
								style={{
									"--extracted-r6o4lv":
										"var(--variable-reference-UgEqrKjlJ-z6gyV1lHJ)",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
									"--variable-reference-UgEqrKjlJ-z6gyV1lHJ": UgEqrKjlJ2,
								}}
								text={vVwiebfTt2}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										VlfzGQsk1: {
											children: (
												<React.Fragment>
													<motion.p
														dir={"auto"}
														style={{
															"--font-selector": "R0Y7SUJNIFBsZXggU2Fucy0zMDA=",
															"--framer-font-family":
																'"IBM Plex Sans", "IBM Plex Sans Placeholder", sans-serif',
															"--framer-font-open-type-features":
																"'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on",
															"--framer-font-size": "24px",
															"--framer-font-weight": "300",
															"--framer-letter-spacing": "-0.02em",
															"--framer-text-alignment": "left",
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--variable-reference-UgEqrKjlJ-z6gyV1lHJ))",
														}}
													>
														{"Saff+"}
													</motion.p>
												</React.Fragment>
											),
											fonts: ["GF;IBM Plex Sans-300"],
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1muwkq9"}
										data-styles-preset={"G8z5IMrxF"}
										dir={"auto"}
										style={{
											"--framer-text-alignment": "left",
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--variable-reference-UgEqrKjlJ-z6gyV1lHJ))",
										}}
									>
										{"Saff+"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-WDLNP.framer-1ffr7mx, .framer-WDLNP .framer-1ffr7mx { display: block; }",
	".framer-WDLNP.framer-wkccdb { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 56px; }",
	".framer-WDLNP .framer-oc09er { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-WDLNP .framer-3f5dvl { --framer-text-wrap-override: balance; flex: none; height: auto; position: relative; width: auto; }",
	".framer-WDLNP.framer-v-fj657j.framer-wkccdb { align-content: flex-start; align-items: flex-start; justify-content: flex-start; }",
	".framer-WDLNP.framer-v-fj657j .framer-oc09er { width: min-content; }",
	".framer-WDLNP.framer-v-fj657j .framer-3f5dvl { --framer-text-wrap: balance; white-space: pre; }",
	...css,
];
var Framerz6gyV1lHJ = withCSS(Component, css2, "framer-WDLNP");
var stdin_default = Framerz6gyV1lHJ;
Framerz6gyV1lHJ.displayName = "HEading Big";
Framerz6gyV1lHJ.defaultProps = {
	height: 29,
	width: 56,
};
addPropertyControls(Framerz6gyV1lHJ, {
	variant: {
		options: ["wKlgDTIj5", "VlfzGQsk1"],
		optionTitles: ["Variant 1", "Light"],
		title: "Variant",
		type: ControlType.Enum,
	},
	vVwiebfTt: {
		defaultValue: "Saff+",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	onvVwiebfTtChange: {
		changes: "vVwiebfTt",
		type: ControlType.ChangeHandler,
	},
	UgEqrKjlJ: {
		defaultValue:
			"var(--token-99df6449-e9f2-4797-8ee6-4b98273d37fc, rgb(64, 64, 64))",
		title: "Color",
		type: ControlType.Color,
	},
});
addFonts(
	Framerz6gyV1lHJ,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "IBM Plex Sans",
					openType: true,
					source: "google",
					style: "normal",
					uiFamilyName: "IBM Plex Sans",
					url: "https://fonts.gstatic.com/s/ibmplexsans/v23/zYXGKVElMYYaJe8bpLHnCwDKr932-G7dytD-Dmu1swZSAXcomDVmadSDtFlzBaI5loa26g.woff2",
					weight: "300",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:h-eading-big
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"fbc126bea31ebbe6cf64cc6db71380905aa865df749edb6fe0a120a118d79a8c"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders HEadingBigFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"fbc126bea31ebbe6cf64cc6db71380905aa865df749edb6fe0a120a118d79a8c"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var h_eading_big_default = ComponentWithRoot;
export { h_eading_big_default as default };
