// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project fbc126bea31ebbe6 "Untitled", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * title?: string // Title
 * onQ2rDjKaJLCHange?: undefined // onQ2rDjKaJLCHange
 * viewAll?: string // View All
 * onrFPKKGIyzChange?: undefined // onrFPKKGIyzChange
}} Props

 */
import { stdin_default as stdin_default2 } from "./chunks/chunk-F7NBLVJ7.js";
import "./chunks/chunk-AFHFKQAQ.js";
import { stdin_default } from "./chunks/chunk-6QV5WJNV.js";
import { routes } from "./chunks/chunk-2F3PHDTH.js";

// virtual:heading-with-cta
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/UAcgMFy68TgPVhkMmDYx/KWQcx7cw7gWh4wpz7BG2/O9dKa58ux.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	forwardLoader,
	getFonts,
	ResolveLinks,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useRouter,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var SectionHeadingFonts = getFonts(stdin_default);
var FuseButtonFonts = getFonts(stdin_default2);
var serializationHash = "framer-rz0IM";
var variantClassNames = {
	bp8XJPGP8: "framer-v-14nncek",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var useStateVariable = (externalState, setExternalState) => {
	const [internalState, setInternalState] = React.useState(externalState);
	const [previousExternalState, setPreviousExternalState] =
		React.useState(externalState);
	if (setExternalState) {
		return [externalState, setExternalState];
	}
	if (externalState !== previousExternalState) {
		setInternalState(externalState);
		setPreviousExternalState(externalState);
	}
	return [internalState, setInternalState];
};
var getProps = ({ height, id, title, viewAll, width, ...props }) => {
	return {
		...props,
		Q2rDjKaJL: title ?? props.Q2rDjKaJL ?? "Highlighted Work_",
		rFPKKgIyz: viewAll ?? props.rFPKKgIyz ?? "View All",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		Q2rDjKaJL: externalQ2rDjKaJL,
		onQ2rDjKaJLChange: setExternalQ2rDjKaJL,
		rFPKKgIyz: externalrFPKKgIyz,
		onrFPKKgIyzChange: setExternalrFPKKgIyz,
		...restProps
	} = getProps(props);
	const [Q2rDjKaJL2, setQ2rDjKaJL2] = useStateVariable(
		externalQ2rDjKaJL,
		setExternalQ2rDjKaJL,
	);
	const [rFPKKgIyz2, setrFPKKgIyz2] = useStateVariable(
		externalrFPKKgIyz,
		setExternalrFPKKgIyz,
	);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "bp8XJPGP8",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const router = useRouter();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-14nncek",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"bp8XJPGP8"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						<ComponentViewportProvider
							height={48}
							y={
								(componentViewport?.y || 0) +
								0 +
								((componentViewport?.height || 48) - 0 - 48)
							}
						>
							<SmartComponentScopedContainer
								className={"framer-38nr27-container"}
								layoutDependency={layoutDependency}
								layoutId={"gMyV1HRJA-container"}
								nodeId={"gMyV1HRJA"}
								rendersWithMotion={true}
								scopeId={"O9dKa58ux"}
							>
								{_jsx(stdin_default, {
									height: "100%",
									id: "gMyV1HRJA",
									layoutId: "gMyV1HRJA",
									ofI8VCy_j: Q2rDjKaJL2,
									onofI8VCy_jChange: setQ2rDjKaJL2,
									style: {
										height: "100%",
										maxWidth: "100%",
										width: "100%",
									},
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ResolveLinks
							links={[
								{
									href: {
										webPageId: "Iv9dQrpBz",
									},
									implicitPathVariables: void 0,
								},
							]}
						>
							{(resolvedLinks) => (
								<ComponentViewportProvider
									height={40}
									y={
										(componentViewport?.y || 0) +
										0 +
										((componentViewport?.height || 48) - 0 - 40)
									}
								>
									<SmartComponentScopedContainer
										className={"framer-6920g9-container"}
										layoutDependency={layoutDependency}
										layoutId={"N9oZlUQa1-container"}
										nodeId={"N9oZlUQa1"}
										rendersWithMotion={true}
										scopeId={"O9dKa58ux"}
									>
										{_jsx(stdin_default2, {
											DFimAXFbj: false,
											height: "100%",
											id: "N9oZlUQa1",
											layoutId: "N9oZlUQa1",
											lfpMYu1dO:
												"var(--token-17586cc6-b205-4368-ade3-9f0f26d38021, rgb(255, 85, 24))",
											onT110aqXleChange: setrFPKKgIyz2,
											qRKaxLb6w: resolvedLinks[0],
											T110aqXle: rFPKKgIyz2,
											variant: matchVariant("dCVHwIVHD"),
											width: "100%",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							)}
						</ResolveLinks>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-rz0IM.framer-b1o3xl, .framer-rz0IM .framer-b1o3xl { display: block; }",
	".framer-rz0IM.framer-14nncek { align-content: flex-end; align-items: flex-end; display: flex; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: 1201px; }",
	".framer-rz0IM .framer-38nr27-container { flex: 1 0 0px; height: 48px; max-width: 100%; position: relative; width: 1px; }",
	".framer-rz0IM .framer-6920g9-container { flex: none; height: auto; position: relative; width: auto; }",
];
var FramerO9dKa58ux = withCSS(Component, css, "framer-rz0IM");
var stdin_default3 = FramerO9dKa58ux;
FramerO9dKa58ux.displayName = "Heading with CTA";
FramerO9dKa58ux.defaultProps = {
	height: 48,
	width: 1201,
};
addPropertyControls(FramerO9dKa58ux, {
	Q2rDjKaJL: {
		defaultValue: "Highlighted Work_",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	onQ2rDjKaJLChange: {
		changes: "Q2rDjKaJL",
		type: ControlType.ChangeHandler,
	},
	rFPKKgIyz: {
		defaultValue: "View All",
		displayTextArea: false,
		title: "View All",
		type: ControlType.String,
	},
	onrFPKKgIyzChange: {
		changes: "rFPKKgIyz",
		type: ControlType.ChangeHandler,
	},
});
addFonts(
	FramerO9dKa58ux,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...SectionHeadingFonts,
		...FuseButtonFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
FramerO9dKa58ux.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([
			forwardLoader(stdin_default, {}, context),
			forwardLoader(stdin_default2, {}, context),
		]);
	},
};

// virtual:heading-with-cta
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"fbc126bea31ebbe6cf64cc6db71380905aa865df749edb6fe0a120a118d79a8c"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders HeadingWithCtaFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"fbc126bea31ebbe6cf64cc6db71380905aa865df749edb6fe0a120a118d79a8c"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var heading_with_cta_default = ComponentWithRoot;
export { heading_with_cta_default as default };
