// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project fbc126bea31ebbe6 "Untitled", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'For Anyone' | 'CEOs' | 'Recuiters' | 'Product Managers' | 'Engineers' | 'Product Designer' // Variant
}} Props

 */
import { stdin_default } from "./chunks/chunk-GZWT3HHK.js";
import "./chunks/chunk-MCFUM3XF.js";
import "./chunks/chunk-MJX6QVBH.js";
import "./chunks/chunk-RF3VFDRB.js";
import "./chunks/chunk-NULYBL27.js";
import { routes } from "./chunks/chunk-2F3PHDTH.js";

// virtual:hero-tabs
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/KqtffnJ7ahWtDGB4VK4G/zPOjMAf8AqNTZqKMtBJT/rL1b3ztA9.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	forwardLoader,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/upNVZru9gXxBzrsFOP92/skS7LpmkebWn7JvXa4MV/nfu3LVlF6.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"FS;Epilogue-regular",
	"FS;Epilogue-bold",
	"FS;Epilogue-bold italic",
	"FS;Epilogue-italic",
]);
var fonts = [
	{
		explicitInter: true,
		fonts: [
			{
				cssFamilyName: "Epilogue",
				source: "fontshare",
				style: "normal",
				uiFamilyName: "Epilogue",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/TBAM3F2B3Q62J3EFZZOFBKD7FY2D2ABJ/UXFRFNKWVYOJXQY4ZT3GUSK23QFKNFJY/FXFHMD66ZLUDCPUIIIVS5BUZ2MFAWPYU.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Epilogue",
				source: "fontshare",
				style: "normal",
				uiFamilyName: "Epilogue",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/Q6PBDKMW3ILHZCUUHJUL7Z5CAEUYIYJT/ACU6JUVISLUN5YPIBAVSNVQX7TIXK7LY/XVEXE7YCBGUS6ROKRHQHPQAR7KODNVQ3.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Epilogue",
				source: "fontshare",
				style: "italic",
				uiFamilyName: "Epilogue",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/ONZH6ZASWZCELVW4GZ5FS2DD4KV34DZY/IWL64III3URHKBZSTXXZCIKPZUGZBYJJ/KVA3QGLTXVRAZQOOPC6T3N7AGN5JIOM5.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Epilogue",
				source: "fontshare",
				style: "italic",
				uiFamilyName: "Epilogue",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/KWLZTFPEA4723LEVLYZXLKTL4WVDOH2O/IWOTC5SPMRT64SBDFF2NYBGUX2REAZU5/T7T65M73WIMKNLHBHJ7Z4UDNIFBBEYY6.woff2",
				weight: "400",
			},
		],
	},
];
var css = [
	`.framer-UHrxD .framer-styles-preset-1gmh0ci:not(.rich-text-wrapper), .framer-UHrxD .framer-styles-preset-1gmh0ci.rich-text-wrapper p { --framer-font-family: "Epilogue", "Epilogue Placeholder", sans-serif; --framer-font-family-bold: "Epilogue", "Epilogue Placeholder", sans-serif; --framer-font-family-bold-italic: "Epilogue", "Epilogue Placeholder", sans-serif; --framer-font-family-italic: "Epilogue", "Epilogue Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 80px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.02em; --framer-line-height: 1.1em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-99df6449-e9f2-4797-8ee6-4b98273d37fc, #001b25); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }`,
	`@media (max-width: 1199px) and (min-width: 810px) { .framer-UHrxD .framer-styles-preset-1gmh0ci:not(.rich-text-wrapper), .framer-UHrxD .framer-styles-preset-1gmh0ci.rich-text-wrapper p { --framer-font-family: "Epilogue", "Epilogue Placeholder", sans-serif; --framer-font-family-bold: "Epilogue", "Epilogue Placeholder", sans-serif; --framer-font-family-bold-italic: "Epilogue", "Epilogue Placeholder", sans-serif; --framer-font-family-italic: "Epilogue", "Epilogue Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 60px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.02em; --framer-line-height: 1.1em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-99df6449-e9f2-4797-8ee6-4b98273d37fc, #001b25); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }`,
	`@media (max-width: 809px) and (min-width: 390px) { .framer-UHrxD .framer-styles-preset-1gmh0ci:not(.rich-text-wrapper), .framer-UHrxD .framer-styles-preset-1gmh0ci.rich-text-wrapper p { --framer-font-family: "Epilogue", "Epilogue Placeholder", sans-serif; --framer-font-family-bold: "Epilogue", "Epilogue Placeholder", sans-serif; --framer-font-family-bold-italic: "Epilogue", "Epilogue Placeholder", sans-serif; --framer-font-family-italic: "Epilogue", "Epilogue Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 37px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.02em; --framer-line-height: 1.1em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-99df6449-e9f2-4797-8ee6-4b98273d37fc, #001b25); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }`,
	`@media (max-width: 389px) and (min-width: 0px) { .framer-UHrxD .framer-styles-preset-1gmh0ci:not(.rich-text-wrapper), .framer-UHrxD .framer-styles-preset-1gmh0ci.rich-text-wrapper p { --framer-font-family: "Epilogue", "Epilogue Placeholder", sans-serif; --framer-font-family-bold: "Epilogue", "Epilogue Placeholder", sans-serif; --framer-font-family-bold-italic: "Epilogue", "Epilogue Placeholder", sans-serif; --framer-font-family-italic: "Epilogue", "Epilogue Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 40px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.02em; --framer-line-height: 1.1em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-99df6449-e9f2-4797-8ee6-4b98273d37fc, #001b25); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }`,
];
var className = "framer-UHrxD";

// /:https://framerusercontent.com/modules/KqtffnJ7ahWtDGB4VK4G/zPOjMAf8AqNTZqKMtBJT/rL1b3ztA9.js
var HeroIntroButtonFonts = getFonts(stdin_default);
var cycleOrder = [
	"b05VwCQz7",
	"vILQExAxN",
	"phhv55jEJ",
	"UUEJAZ0PX",
	"YOUln6dlw",
	"GgtqxzktU",
];
var serializationHash = "framer-gvPgR";
var variantClassNames = {
	b05VwCQz7: "framer-v-5048f8",
	GgtqxzktU: "framer-v-lay4u7",
	phhv55jEJ: "framer-v-14cabhc",
	UUEJAZ0PX: "framer-v-1hoj4pw",
	vILQExAxN: "framer-v-67sd0j",
	YOUln6dlw: "framer-v-d6edej",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"For Anyone": "b05VwCQz7",
	"Product Designer": "GgtqxzktU",
	"Product Managers": "UUEJAZ0PX",
	CEOs: "vILQExAxN",
	Engineers: "YOUln6dlw",
	Recuiters: "phhv55jEJ",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "b05VwCQz7",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "b05VwCQz7",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const WmbVuj2G61g2geou = activeVariantCallback(async (...args) => {
		setVariant("b05VwCQz7");
	});
	const WmbVuj2G6hh29c = activeVariantCallback(async (...args) => {
		setVariant("vILQExAxN");
	});
	const WmbVuj2G6scbw6c = activeVariantCallback(async (...args) => {
		setVariant("phhv55jEJ");
	});
	const WmbVuj2G6bl1bos = activeVariantCallback(async (...args) => {
		setVariant("UUEJAZ0PX");
	});
	const WmbVuj2G618ch068 = activeVariantCallback(async (...args) => {
		setVariant("YOUln6dlw");
	});
	const WmbVuj2G6ir0onh = activeVariantCallback(async (...args) => {
		setVariant("GgtqxzktU");
	});
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-5048f8",
							className2,
							classNames,
						)}
						data-framer-name={"For Anyone"}
						layoutDependency={layoutDependency}
						layoutId={"b05VwCQz7"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								GgtqxzktU: {
									"data-framer-name": "Product Designer",
								},
								phhv55jEJ: {
									"data-framer-name": "Recuiters",
								},
								UUEJAZ0PX: {
									"data-framer-name": "Product Managers",
								},
								vILQExAxN: {
									"data-framer-name": "CEOs",
								},
								YOUln6dlw: {
									"data-framer-name": "Engineers",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-13rz5i1"}
							layoutDependency={layoutDependency}
							layoutId={"lc6tUBVSh"}
						>
							<ComponentViewportProvider
								height={22}
								width={"83px"}
								y={
									(componentViewport?.y || 0) +
									0 +
									(((componentViewport?.height || 200) - 0 - 140) / 2 + 0 + 0) +
									0
								}
							>
								<SmartComponentScopedContainer
									className={"framer-lodqrp-container"}
									layoutDependency={layoutDependency}
									layoutId={"XVSw7VfEy-container"}
									nodeId={"XVSw7VfEy"}
									rendersWithMotion={true}
									scopeId={"rL1b3ztA9"}
								>
									{_jsx(stdin_default, {
										Be06fKMwq: "Coin",
										height: "100%",
										id: "XVSw7VfEy",
										layoutId: "XVSw7VfEy",
										LYjvy2FF1: false,
										s5L4R_EBn: "Coin",
										s9BUzLDEa:
											"var(--token-1680a61f-616b-4800-b66d-bfa16b2c9fa1, rgb(82, 95, 99))",
										style: {
											height: "100%",
											width: "100%",
										},
										u2QU6c55_: "For Anyone",
										variant: matchVariant("ifpDWzfpP"),
										width: "100%",
										XtLdX4t3u: false,
										...addPropertyOverrides(
											{
												GgtqxzktU: {
													variant: matchVariant("TlMvae5wi"),
													WmbVuj2G6: WmbVuj2G61g2geou,
												},
												phhv55jEJ: {
													variant: matchVariant("TlMvae5wi"),
													WmbVuj2G6: WmbVuj2G61g2geou,
												},
												UUEJAZ0PX: {
													variant: matchVariant("TlMvae5wi"),
													WmbVuj2G6: WmbVuj2G61g2geou,
												},
												vILQExAxN: {
													variant: matchVariant("TlMvae5wi"),
													WmbVuj2G6: WmbVuj2G61g2geou,
												},
												YOUln6dlw: {
													variant: matchVariant("TlMvae5wi"),
													WmbVuj2G6: WmbVuj2G61g2geou,
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
							<ComponentViewportProvider
								height={22}
								width={"125px"}
								y={
									(componentViewport?.y || 0) +
									0 +
									(((componentViewport?.height || 200) - 0 - 140) / 2 + 0 + 0) +
									0
								}
							>
								<SmartComponentScopedContainer
									className={"framer-93uojw-container"}
									layoutDependency={layoutDependency}
									layoutId={"awM0GnLYW-container"}
									nodeId={"awM0GnLYW"}
									rendersWithMotion={true}
									scopeId={"rL1b3ztA9"}
								>
									{_jsx(stdin_default, {
										Be06fKMwq: "Coin",
										height: "100%",
										id: "awM0GnLYW",
										layoutId: "awM0GnLYW",
										LYjvy2FF1: false,
										s5L4R_EBn: "Coin",
										s9BUzLDEa:
											"var(--token-df79e38c-c9e1-4fba-9890-9323ccb725c1, rgb(102, 102, 102))",
										style: {
											height: "100%",
											width: "100%",
										},
										u2QU6c55_: "CEOs & Founders",
										variant: matchVariant("TlMvae5wi"),
										width: "100%",
										WmbVuj2G6: WmbVuj2G6hh29c,
										XtLdX4t3u: false,
										...addPropertyOverrides(
											{
												vILQExAxN: {
													variant: matchVariant("ifpDWzfpP"),
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
							<ComponentViewportProvider
								height={22}
								width={"76px"}
								y={
									(componentViewport?.y || 0) +
									0 +
									(((componentViewport?.height || 200) - 0 - 140) / 2 + 0 + 0) +
									0
								}
							>
								<SmartComponentScopedContainer
									className={"framer-1a3o89q-container"}
									layoutDependency={layoutDependency}
									layoutId={"yZqaFGNqp-container"}
									nodeId={"yZqaFGNqp"}
									rendersWithMotion={true}
									scopeId={"rL1b3ztA9"}
								>
									{_jsx(stdin_default, {
										Be06fKMwq: "Coin",
										height: "100%",
										id: "yZqaFGNqp",
										layoutId: "yZqaFGNqp",
										LYjvy2FF1: false,
										s5L4R_EBn: "Coin",
										s9BUzLDEa:
											"var(--token-df79e38c-c9e1-4fba-9890-9323ccb725c1, rgb(102, 102, 102))",
										style: {
											height: "100%",
											width: "100%",
										},
										u2QU6c55_: "Recruiter",
										variant: matchVariant("TlMvae5wi"),
										width: "100%",
										WmbVuj2G6: WmbVuj2G6scbw6c,
										XtLdX4t3u: false,
										...addPropertyOverrides(
											{
												phhv55jEJ: {
													variant: matchVariant("ifpDWzfpP"),
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
							<ComponentViewportProvider
								height={22}
								width={"131px"}
								y={
									(componentViewport?.y || 0) +
									0 +
									(((componentViewport?.height || 200) - 0 - 140) / 2 + 0 + 0) +
									0
								}
							>
								<SmartComponentScopedContainer
									className={"framer-3bpbdv-container"}
									layoutDependency={layoutDependency}
									layoutId={"ka8LSqxMK-container"}
									nodeId={"ka8LSqxMK"}
									rendersWithMotion={true}
									scopeId={"rL1b3ztA9"}
								>
									{_jsx(stdin_default, {
										Be06fKMwq: "Coin",
										height: "100%",
										id: "ka8LSqxMK",
										layoutId: "ka8LSqxMK",
										LYjvy2FF1: false,
										s5L4R_EBn: "Coin",
										s9BUzLDEa:
											"var(--token-df79e38c-c9e1-4fba-9890-9323ccb725c1, rgb(102, 102, 102))",
										style: {
											height: "100%",
											width: "100%",
										},
										u2QU6c55_: "Product Managers",
										variant: matchVariant("TlMvae5wi"),
										width: "100%",
										WmbVuj2G6: WmbVuj2G6bl1bos,
										XtLdX4t3u: false,
										...addPropertyOverrides(
											{
												UUEJAZ0PX: {
													variant: matchVariant("ifpDWzfpP"),
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
							<ComponentViewportProvider
								height={22}
								width={"75px"}
								y={
									(componentViewport?.y || 0) +
									0 +
									(((componentViewport?.height || 200) - 0 - 140) / 2 + 0 + 0) +
									0
								}
							>
								<SmartComponentScopedContainer
									className={"framer-4u7kkd-container"}
									layoutDependency={layoutDependency}
									layoutId={"m1UuuKfTs-container"}
									nodeId={"m1UuuKfTs"}
									rendersWithMotion={true}
									scopeId={"rL1b3ztA9"}
								>
									{_jsx(stdin_default, {
										Be06fKMwq: "Coin",
										height: "100%",
										id: "m1UuuKfTs",
										layoutId: "m1UuuKfTs",
										LYjvy2FF1: false,
										s5L4R_EBn: "Coin",
										s9BUzLDEa:
											"var(--token-df79e38c-c9e1-4fba-9890-9323ccb725c1, rgb(102, 102, 102))",
										style: {
											height: "100%",
											width: "100%",
										},
										u2QU6c55_: "Engineers",
										variant: matchVariant("TlMvae5wi"),
										width: "100%",
										WmbVuj2G6: WmbVuj2G618ch068,
										XtLdX4t3u: false,
										...addPropertyOverrides(
											{
												YOUln6dlw: {
													variant: matchVariant("ifpDWzfpP"),
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
							<ComponentViewportProvider
								height={22}
								width={"148px"}
								y={
									(componentViewport?.y || 0) +
									0 +
									(((componentViewport?.height || 200) - 0 - 140) / 2 + 0 + 0) +
									0
								}
							>
								<SmartComponentScopedContainer
									className={"framer-s4rcwv-container"}
									layoutDependency={layoutDependency}
									layoutId={"JFburf79a-container"}
									nodeId={"JFburf79a"}
									rendersWithMotion={true}
									scopeId={"rL1b3ztA9"}
								>
									{_jsx(stdin_default, {
										Be06fKMwq: "Coin",
										height: "100%",
										id: "JFburf79a",
										layoutId: "JFburf79a",
										LYjvy2FF1: false,
										s5L4R_EBn: "Coin",
										s9BUzLDEa:
											"var(--token-df79e38c-c9e1-4fba-9890-9323ccb725c1, rgb(102, 102, 102))",
										style: {
											height: "100%",
											width: "100%",
										},
										u2QU6c55_: "Product Designers",
										variant: matchVariant("TlMvae5wi"),
										width: "100%",
										WmbVuj2G6: WmbVuj2G6ir0onh,
										XtLdX4t3u: false,
										...addPropertyOverrides(
											{
												GgtqxzktU: {
													variant: matchVariant("ifpDWzfpP"),
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						</motion.div>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1x1scfu"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"pmFE9IN3E"}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
							{...addPropertyOverrides(
								{
									GgtqxzktU: {
										children: (
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-1gmh0ci"}
													data-styles-preset={"nfu3LVlF6"}
												>
													{
														"Mentor helping designers think in systems and grow their craft."
													}
												</motion.p>
											</React.Fragment>
										),
									},
									phhv55jEJ: {
										children: (
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-1gmh0ci"}
													data-styles-preset={"nfu3LVlF6"}
												>
													{
														"Director\u2011level design leader across AI, SaaS, and B2B tools."
													}
												</motion.p>
											</React.Fragment>
										),
									},
									UUEJAZ0PX: {
										children: (
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-1gmh0ci"}
													data-styles-preset={"nfu3LVlF6"}
												>
													{
														"Design partner who thinks in systems and ships outcomes."
													}
												</motion.p>
											</React.Fragment>
										),
									},
									vILQExAxN: {
										children: (
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-1gmh0ci"}
													data-styles-preset={"nfu3LVlF6"}
													dir={"auto"}
												>
													{
														"I turn complex AI/SaaS ideas into clear, shippable products."
													}
												</motion.p>
											</React.Fragment>
										),
									},
									YOUln6dlw: {
										children: (
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-1gmh0ci"}
													data-styles-preset={"nfu3LVlF6"}
												>
													{
														"Clean tokens, clear specs, and patterns that are buildable."
													}
												</motion.p>
											</React.Fragment>
										),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-1gmh0ci"}
									data-styles-preset={"nfu3LVlF6"}
									dir={"auto"}
								>
									{
										"I\u2019m Nikhil Kanda 'Nix', Design Principal & Director, shipping systems."
									}
								</motion.p>
							</React.Fragment>
						</RichText>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-gvPgR.framer-ojzq3i, .framer-gvPgR .framer-ojzq3i { display: block; }",
	".framer-gvPgR.framer-5048f8 { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 1152px; }",
	".framer-gvPgR .framer-13rz5i1 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: auto; padding: 0px; position: relative; width: 100%; }",
	".framer-gvPgR .framer-lodqrp-container { flex: none; height: 22px; position: relative; width: 83px; }",
	".framer-gvPgR .framer-93uojw-container { flex: none; height: 22px; position: relative; width: 125px; }",
	".framer-gvPgR .framer-1a3o89q-container { flex: none; height: 22px; position: relative; width: 76px; }",
	".framer-gvPgR .framer-3bpbdv-container { flex: none; height: 22px; position: relative; width: 131px; }",
	".framer-gvPgR .framer-4u7kkd-container { flex: none; height: 22px; position: relative; width: 75px; }",
	".framer-gvPgR .framer-s4rcwv-container { flex: none; height: 22px; position: relative; width: 148px; }",
	".framer-gvPgR .framer-1x1scfu { flex: none; height: auto; max-width: 100%; position: relative; white-space: pre-wrap; width: auto; word-break: break-word; word-wrap: break-word; }",
	...css,
];
var FramerrL1b3ztA9 = withCSS(Component, css2, "framer-gvPgR");
var stdin_default2 = FramerrL1b3ztA9;
FramerrL1b3ztA9.displayName = "Hero Tabs";
FramerrL1b3ztA9.defaultProps = {
	height: 316,
	width: 1152,
};
addPropertyControls(FramerrL1b3ztA9, {
	variant: {
		options: [
			"b05VwCQz7",
			"vILQExAxN",
			"phhv55jEJ",
			"UUEJAZ0PX",
			"YOUln6dlw",
			"GgtqxzktU",
		],
		optionTitles: [
			"For Anyone",
			"CEOs",
			"Recuiters",
			"Product Managers",
			"Engineers",
			"Product Designer",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerrL1b3ztA9,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...HeroIntroButtonFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
FramerrL1b3ztA9.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([forwardLoader(stdin_default, {}, context)]);
	},
};

// virtual:hero-tabs
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "b05VwCQz7",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"fbc126bea31ebbe6cf64cc6db71380905aa865df749edb6fe0a120a118d79a8c"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders HeroTabsFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"fbc126bea31ebbe6cf64cc6db71380905aa865df749edb6fe0a120a118d79a8c"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var hero_tabs_default = ComponentWithRoot;
export { hero_tabs_default as default };
