// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project fbc126bea31ebbe6 "Untitled", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * timelineItems?: {year: string, title: string, description: string[] // Timeline Items
 * background?: string // Background
 * cardBackground?: string // Card Background
 * activeCard?: string // Active Card
 * textColor?: string // Text Color
 * activeText?: string // Active Text
 * yearColor?: string // Year Color
 * activeYear?: string // Active Year
 * lineColor?: string // Line Color
 * dotColor?: string // Dot Color
 * activeDot?: string // Active Dot
 * titleFont?: undefined // Title Font
 * descriptionFont?: undefined // Description Font
 * yearFont?: undefined // Year Font
 * cardRadius?: number // Card Radius
}} Props

 */
import { routes } from "./chunks/chunk-2F3PHDTH.js";

// virtual:horizontal-timeline-1
import { Fragment } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/QJePwJmbpr8itFR4x7Ec/NsZbsqs16NTz2ykxLVYK/HorizontalTimeline_1.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState, useRef, useEffect, startTransition } from "react";
import { addPropertyControls, ControlType } from "unframer";
function HorizontalTimeline(props) {
	const {
		items,
		backgroundColor,
		cardBackground,
		activeCardBackground,
		textColor,
		activeTextColor,
		yearColor,
		activeYearColor,
		lineColor,
		dotColor,
		activeDotColor,
		titleFont,
		descriptionFont,
		yearFont,
		cardBorderRadius,
	} = props;
	const [activeIndex, setActiveIndex] = useState(0);
	const scrollContainerRef = useRef(null);
	const cardRefs = useRef([]);
	const scrollToCard = (index) => {
		if (scrollContainerRef.current && cardRefs.current[index]) {
			const container = scrollContainerRef.current;
			const card = cardRefs.current[index];
			const containerWidth = container.offsetWidth;
			const cardLeft = card.offsetLeft;
			const cardWidth = card.offsetWidth;
			const scrollPosition = cardLeft - containerWidth / 2 + cardWidth / 2;
			container.scrollTo({
				left: scrollPosition,
				behavior: "smooth",
			});
		}
	};
	const handleScroll = () => {
		if (!scrollContainerRef.current) return;
		const container = scrollContainerRef.current;
		const containerCenter = container.scrollLeft + container.offsetWidth / 2;
		let closestIndex = 0;
		let closestDistance = Number.MAX_VALUE;
		cardRefs.current.forEach((card, index) => {
			if (!card) return;
			const cardCenter = card.offsetLeft + card.offsetWidth / 2;
			const distance = Math.abs(containerCenter - cardCenter);
			if (distance < closestDistance) {
				closestDistance = distance;
				closestIndex = index;
			}
		});
		if (closestIndex !== activeIndex) {
			startTransition(() => setActiveIndex(closestIndex));
		}
	};
	useEffect(() => {
		scrollToCard(activeIndex);
	}, [activeIndex]);
	const handleWheel = (e) => {
		if (!scrollContainerRef.current) return;
		e.preventDefault();
		scrollContainerRef.current.scrollLeft += e.deltaY;
	};
	return (
		<div
			style={{
				width: "100%",
				height: "100%",
				backgroundColor,
				padding: "40px 0",
				overflow: "hidden",
				position: "relative",
			}}
		>
			<div
				ref={scrollContainerRef}
				onScroll={handleScroll}
				onWheel={handleWheel}
				style={{
					width: "100%",
					height: "100%",
					overflowX: "auto",
					overflowY: "hidden",
					scrollbarWidth: "none",
					msOverflowStyle: "none",
					WebkitOverflowScrolling: "touch",
					scrollSnapType: "x mandatory",
				}}
			>
				<style>{`
                        div::-webkit-scrollbar {
                            display: none;
                        }
                    `}</style>
				<div
					style={{
						display: "flex",
						alignItems: "center",
						gap: "60px",
						padding: "0 50%",
						height: "100%",
						position: "relative",
					}}
				>
					<div
						style={{
							position: "absolute",
							top: "50%",
							left: 0,
							right: 0,
							height: "2px",
							backgroundColor: lineColor,
							transform: "translateY(-50%)",
							zIndex: 0,
						}}
					/>
					{items.map((item, index) => {
						const isActive = index === activeIndex;
						return (
							<div
								ref={(el) => {
									cardRefs.current[index] = el;
								}}
								onClick={() => {
									startTransition(() => setActiveIndex(index));
									scrollToCard(index);
								}}
								style={{
									minWidth: "320px",
									maxWidth: "320px",
									display: "flex",
									flexDirection: "column",
									alignItems: "center",
									gap: "20px",
									cursor: "pointer",
									transition: "all 0.3s ease",
									position: "relative",
									zIndex: 1,
									scrollSnapAlign: "center",
								}}
							>
								<div
									style={{
										...yearFont,
										color: isActive ? activeYearColor : yearColor,
										transition: "color 0.3s ease",
										marginBottom: "10px",
									}}
								>
									{item.year}
								</div>
								<div
									style={{
										width: isActive ? "16px" : "12px",
										height: isActive ? "16px" : "12px",
										borderRadius: "50%",
										backgroundColor: isActive ? activeDotColor : dotColor,
										transition: "all 0.3s ease",
										boxShadow: isActive
											? "0 0 0 4px rgba(0, 0, 0, 0.1)"
											: "none",
									}}
								/>
								<div
									style={{
										width: "100%",
										backgroundColor: isActive
											? activeCardBackground
											: cardBackground,
										borderRadius: cardBorderRadius,
										padding: "24px",
										boxShadow: isActive
											? "0 8px 24px rgba(0, 0, 0, 0.12)"
											: "0 2px 8px rgba(0, 0, 0, 0.08)",
										transition: "all 0.3s ease",
										transform: isActive ? "scale(1.05)" : "scale(1)",
									}}
								>
									<h3
										style={{
											...titleFont,
											color: isActive ? activeTextColor : textColor,
											margin: "0 0 12px 0",
											transition: "color 0.3s ease",
										}}
									>
										{item.title}
									</h3>
									<p
										style={{
											...descriptionFont,
											color: isActive ? activeTextColor : textColor,
											margin: 0,
											opacity: isActive ? 1 : 0.7,
											transition: "all 0.3s ease",
										}}
									>
										{item.description}
									</p>
								</div>
							</div>
						);
					})}
				</div>
			</div>
		</div>
	);
}
addPropertyControls(HorizontalTimeline, {
	items: {
		type: ControlType.Array,
		title: "Timeline Items",
		control: {
			type: ControlType.Object,
			controls: {
				year: {
					type: ControlType.String,
					title: "Year",
					defaultValue: "2024",
				},
				title: {
					type: ControlType.String,
					title: "Title",
					defaultValue: "Milestone Title",
				},
				description: {
					type: ControlType.String,
					title: "Description",
					defaultValue:
						"Description of this milestone and what happened during this period.",
					displayTextArea: true,
				},
			},
		},
		defaultValue: [
			{
				year: "2020",
				title: "Foundation",
				description:
					"The beginning of our journey with a clear vision and ambitious goals.",
			},
			{
				year: "2021",
				title: "Growth",
				description:
					"Rapid expansion and development of core features and capabilities.",
			},
			{
				year: "2022",
				title: "Innovation",
				description:
					"Introduction of groundbreaking features that changed the industry.",
			},
			{
				year: "2023",
				title: "Excellence",
				description:
					"Recognition and awards for outstanding achievements and impact.",
			},
		],
	},
	backgroundColor: {
		type: ControlType.Color,
		title: "Background",
		defaultValue: "#F5F5F5",
	},
	cardBackground: {
		type: ControlType.Color,
		title: "Card Background",
		defaultValue: "#FFFFFF",
	},
	activeCardBackground: {
		type: ControlType.Color,
		title: "Active Card",
		defaultValue: "#FFFFFF",
	},
	textColor: {
		type: ControlType.Color,
		title: "Text Color",
		defaultValue: "#000000",
	},
	activeTextColor: {
		type: ControlType.Color,
		title: "Active Text",
		defaultValue: "#000000",
	},
	yearColor: {
		type: ControlType.Color,
		title: "Year Color",
		defaultValue: "#CCCCCC",
	},
	activeYearColor: {
		type: ControlType.Color,
		title: "Active Year",
		defaultValue: "#000000",
	},
	lineColor: {
		type: ControlType.Color,
		title: "Line Color",
		defaultValue: "#EEEEEE",
	},
	dotColor: {
		type: ControlType.Color,
		title: "Dot Color",
		defaultValue: "#CCCCCC",
	},
	activeDotColor: {
		type: ControlType.Color,
		title: "Active Dot",
		defaultValue: "#000000",
	},
	titleFont: {
		type: ControlType.Font,
		title: "Title Font",
		controls: "extended",
		defaultFontType: "sans-serif",
		defaultValue: {
			fontSize: "22px",
			variant: "Semibold",
			letterSpacing: "-0.01em",
			lineHeight: "1.2em",
		},
	},
	descriptionFont: {
		type: ControlType.Font,
		title: "Description Font",
		controls: "extended",
		defaultFontType: "sans-serif",
		defaultValue: {
			fontSize: "15px",
			variant: "Medium",
			letterSpacing: "-0.01em",
			lineHeight: "1.3em",
		},
	},
	yearFont: {
		type: ControlType.Font,
		title: "Year Font",
		controls: "extended",
		defaultFontType: "sans-serif",
		defaultValue: {
			fontSize: "32px",
			variant: "Bold",
			letterSpacing: "-0.03em",
			lineHeight: "1em",
		},
	},
	cardBorderRadius: {
		type: ControlType.Number,
		title: "Card Radius",
		defaultValue: 8,
		min: 0,
		max: 32,
		step: 1,
	},
});

// virtual:horizontal-timeline-1
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"fbc126bea31ebbe6cf64cc6db71380905aa865df749edb6fe0a120a118d79a8c"
			}
			locale={locale}
			locales={locales}
		>
			<HorizontalTimeline {...rest} />
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders HorizontalTimeline1FramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"fbc126bea31ebbe6cf64cc6db71380905aa865df749edb6fe0a120a118d79a8c"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={HorizontalTimeline}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, HorizontalTimeline);
var horizontal_timeline_1_default = ComponentWithRoot;
export { horizontal_timeline_1_default as default };
