// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project fbc126bea31ebbe6 "Untitled", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * timelineItems?: {year: string, image: {src: string, srcSet?: string, alt?: string}, company: string, title: string, dateRange: string, description: string[] // Timeline Items
 * yearColor?: string // Year Color
 * yearFont?: undefined // Year Font
 * cardBackground?: string // Card Background
 * cardRadius?: number // Card Radius
 * cardShadow?: boolean // Card Shadow
 * lineColor?: string // Line Color
 * lineHeight?: number // Line Height
 * dotColor?: string // Dot Color
 * dotSize?: number // Dot Size
 * itemSpacing?: number // Item Spacing
}} Props

 */
import { routes } from "./chunks/chunk-2F3PHDTH.js";

// virtual:horizontal-timeline
import { Fragment } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/qNv1JWeTnUGAAjzhjJDL/X8bJKUZdm7GCxMuOnXYi/HorizontalTimeline.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { addPropertyControls, ControlType } from "unframer";
import { useRef, useEffect } from "react";
function HorizontalTimeline(props) {
	const {
		items = [],
		yearColor,
		yearFont,
		cardBackground,
		cardBorderRadius,
		cardShadow,
		lineColor,
		lineHeight,
		dotColor,
		dotSize,
		spacing,
	} = props;
	const scrollContainerRef = useRef(null);
	useEffect(() => {
		const container = scrollContainerRef.current;
		if (!container) return;
		const handleWheel = (e) => {
			e.preventDefault();
			container.scrollLeft += e.deltaY;
		};
		container.addEventListener("wheel", handleWheel, {
			passive: false,
		});
		return () => {
			container.removeEventListener("wheel", handleWheel);
		};
	}, []);
	return (
		<div
			ref={scrollContainerRef}
			style={{
				width: "100%",
				height: "100%",
				overflow: "auto",
				position: "relative",
				scrollSnapType: "x mandatory",
				scrollBehavior: "smooth",
			}}
		>
			<div
				style={{
					display: "flex",
					alignItems: "flex-end",
					padding: "40px 20px",
					minWidth: "max-content",
					height: "100%",
					gap: `${spacing}px`,
				}}
			>
				{items.map((item, index) => (
					<div
						style={{
							display: "flex",
							flexDirection: "column",
							alignItems: "flex-start",
							gap: "40px",
							position: "relative",
							scrollSnapAlign: "center",
							scrollSnapStop: "always",
							minWidth: "600px",
						}}
					>
						<div
							style={{
								width: "100%",
								minHeight: "350px",
								backgroundColor: cardBackground,
								borderRadius: `${cardBorderRadius}px`,
								overflow: "hidden",
								boxShadow: cardShadow ? "0 4px 10px rgba(0,0,0,0.08)" : "none",
								display: "flex",
								gap: "40px",
								padding: "40px",
							}}
						>
							<div
								style={{
									width: "350px",
									height: "350px",
									flexShrink: 0,
									backgroundColor: "#D3D3D3",
									borderRadius: "12px",
									overflow: "hidden",
								}}
							>
								<img
									src={
										item.image?.src ||
										"https://framerusercontent.com/images/GfGkADagM4KEibNcIiRUWlfrR0.jpg"
									}
									alt={item.image?.alt || "Timeline image"}
									style={{
										width: "100%",
										height: "100%",
										objectFit: "cover",
									}}
								/>
							</div>
							<div
								style={{
									display: "flex",
									flexDirection: "column",
									gap: "16px",
									flex: 1,
								}}
							>
								<div
									style={{
										fontSize: "18px",
										fontWeight: 500,
									}}
								>
									{item.company}
								</div>
								<div
									style={{
										fontSize: "32px",
										fontWeight: 600,
										lineHeight: "1.2",
									}}
								>
									{item.title}
								</div>
								<div
									style={{
										fontSize: "16px",
										fontWeight: 400,
									}}
								>
									{item.dateRange}
								</div>
								<div
									style={{
										fontSize: "16px",
										fontWeight: 400,
										lineHeight: "1.5",
										marginTop: "8px",
									}}
								>
									{item.description}
								</div>
							</div>
						</div>
						<div
							style={{
								display: "flex",
								flexDirection: "column",
								alignItems: "center",
								gap: "16px",
								width: "100%",
							}}
						>
							<div
								style={{
									display: "flex",
									alignItems: "center",
									gap: "0px",
									width: "100%",
								}}
							>
								<div
									style={{
										width: `${dotSize}px`,
										height: `${dotSize}px`,
										borderRadius: "50%",
										backgroundColor: dotColor,
										flexShrink: 0,
										zIndex: 2,
									}}
								/>
								{index < items.length - 1 && (
									<div
										style={{
											height: `${lineHeight}px`,
											width: `${spacing}px`,
											backgroundColor: lineColor,
											flexShrink: 0,
										}}
									/>
								)}
							</div>
							<div
								style={{
									...yearFont,
									color: yearColor,
									whiteSpace: "nowrap",
								}}
							>
								{item.year}
							</div>
						</div>
					</div>
				))}
			</div>
		</div>
	);
}
addPropertyControls(HorizontalTimeline, {
	items: {
		type: ControlType.Array,
		title: "Timeline Items",
		control: {
			type: ControlType.Object,
			controls: {
				year: {
					type: ControlType.String,
					title: "Year",
					defaultValue: "2024",
				},
				image: {
					type: ControlType.ResponsiveImage,
					title: "Image",
				},
				company: {
					type: ControlType.String,
					title: "Company",
					defaultValue: "Company Name",
				},
				title: {
					type: ControlType.String,
					title: "Job Title",
					defaultValue: "Job Title",
				},
				dateRange: {
					type: ControlType.String,
					title: "Date Range",
					defaultValue: "2023-Present Vancouver",
				},
				description: {
					type: ControlType.String,
					title: "Description",
					defaultValue: "Job description and achievements",
					displayTextArea: true,
				},
			},
		},
		defaultValue: [
			{
				year: "2025-Present",
				image: {
					src: "https://framerusercontent.com/images/GfGkADagM4KEibNcIiRUWlfrR0.jpg",
					alt: "Timeline 2025",
				},
				company: "Portkey.ai",
				title: "Director of design",
				dateRange: "2023-Present Vancouver",
				description:
					"Finding product-market fit: CR visitors \u2192 downloads 2021 = 18.2%, freemium \u2192 paid 2021 = 30.3%, Yearly churn movement",
			},
			{
				year: "2024",
				image: {
					src: "https://framerusercontent.com/images/aNsAT3jCvt4zglbWCUoFe33Q.jpg",
					alt: "Timeline 2024",
				},
				company: "Previous Company",
				title: "Senior Designer",
				dateRange: "2022-2023 Remote",
				description:
					"Led design initiatives and improved user experience across multiple products.",
			},
		],
	},
	yearColor: {
		type: ControlType.Color,
		title: "Year Color",
		defaultValue: "#000000",
	},
	yearFont: {
		type: ControlType.Font,
		title: "Year Font",
		controls: "extended",
		defaultFontType: "sans-serif",
		defaultValue: {
			fontSize: "22px",
			variant: "Semibold",
			letterSpacing: "-0.01em",
			lineHeight: "1.2em",
		},
	},
	cardBackground: {
		type: ControlType.Color,
		title: "Card Background",
		defaultValue: "#FFFFFF",
	},
	cardBorderRadius: {
		type: ControlType.Number,
		title: "Card Radius",
		defaultValue: 8,
		min: 0,
		max: 32,
		step: 1,
		unit: "px",
	},
	cardShadow: {
		type: ControlType.Boolean,
		title: "Card Shadow",
		defaultValue: true,
		enabledTitle: "On",
		disabledTitle: "Off",
	},
	lineColor: {
		type: ControlType.Color,
		title: "Line Color",
		defaultValue: "#EEEEEE",
	},
	lineHeight: {
		type: ControlType.Number,
		title: "Line Height",
		defaultValue: 2,
		min: 1,
		max: 10,
		step: 1,
		unit: "px",
	},
	dotColor: {
		type: ControlType.Color,
		title: "Dot Color",
		defaultValue: "#000000",
	},
	dotSize: {
		type: ControlType.Number,
		title: "Dot Size",
		defaultValue: 12,
		min: 6,
		max: 24,
		step: 1,
		unit: "px",
	},
	spacing: {
		type: ControlType.Number,
		title: "Item Spacing",
		defaultValue: 100,
		min: 50,
		max: 300,
		step: 10,
		unit: "px",
	},
});

// virtual:horizontal-timeline
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"fbc126bea31ebbe6cf64cc6db71380905aa865df749edb6fe0a120a118d79a8c"
			}
			locale={locale}
			locales={locales}
		>
			<HorizontalTimeline {...rest} />
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders HorizontalTimelineFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"fbc126bea31ebbe6cf64cc6db71380905aa865df749edb6fe0a120a118d79a8c"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={HorizontalTimeline}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, HorizontalTimeline);
var horizontal_timeline_default = ComponentWithRoot;
export { horizontal_timeline_default as default };
