// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project fbc126bea31ebbe6 "Untitled", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * layout?: 'Desktop' | 'Mobile' // Layout
 * cards?: {image: {src: string, srcSet?: string, alt?: string}, caption: string, rotation: number, x: number, y: number[] // Cards
 * cardPlacement?: 'Start' | 'Center' | 'End' | 'Space Between' | 'Space Around' // Card Placement
 * cardWidth?: number // Card Width
 * cardSpacing?: number // Card Spacing
 * background?: string // Background
 * captionBG?: string // Caption BG
 * captionText?: string // Caption Text
 * captionFont?: undefined // Caption Font
 * hoverScale?: number // Hover Scale
 * hoverRotation?: number // Hover Rotation
 * hoverMove?: number // Hover Move
 * borderRadius?: number // Border Radius
 * overflow?: 'Visible' | 'Hidden' // Overflow
 * shadow?: boolean // Shadow
}} Props

 */
import { routes } from "./chunks/chunk-2F3PHDTH.js";

// virtual:hover-cards
import { Fragment } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/zczMBU8JFtdXqDYnSXKu/SHPlfkNfvXQuAmTquSF8/HoverCards.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from "unframer";
import { addPropertyControls, ControlType } from "unframer";
import { useState, useMemo } from "react";
function HoverCards(props) {
	const {
		cards = [
			{
				image: {
					src: "https://framerusercontent.com/images/GfGkADagM4KEibNcIiRUWlfrR0.jpg",
					alt: "Card 1",
				},
				caption: "girls just wanna have fun!",
				rotation: -8,
				x: 0,
				y: 0,
			},
			{
				image: {
					src: "https://framerusercontent.com/images/aNsAT3jCvt4zglbWCUoFe33Q.jpg",
					alt: "Card 2",
				},
				caption: "mainstream is not a dirty word",
				rotation: 5,
				x: 0,
				y: 0,
			},
			{
				image: {
					src: "https://framerusercontent.com/images/BYnxEV1zjYb9bhWh1IwBZ1ZoS60.jpg",
					alt: "Card 3",
				},
				caption: "",
				rotation: -3,
				x: 0,
				y: 0,
			},
			{
				image: {
					src: "https://framerusercontent.com/images/2uTNEj5aTl2K3NJaEFWMbnrA.jpg",
					alt: "Card 4",
				},
				caption: "arrogance = old fashioned",
				rotation: 7,
				x: 0,
				y: 0,
			},
			{
				image: {
					src: "https://framerusercontent.com/images/f9RiWoNpmlCMqVRIHz8l8wYfeI.jpg",
					alt: "Card 5",
				},
				caption: "new card",
				rotation: -5,
				x: 0,
				y: 0,
			},
			{
				image: {
					src: "https://framerusercontent.com/images/GfGkADagM4KEibNcIiRUWlfrR0.jpg",
					alt: "Card 6",
				},
				caption: "another card",
				rotation: 4,
				x: 0,
				y: 0,
			},
		],
		layout = "desktop",
		backgroundColor,
		captionBackgroundColor,
		captionTextColor,
		captionFont,
		hoverScale,
		hoverRotation,
		cardWidth = 250,
		cardSpacing = 40,
		hoverMove = 10,
		borderRadius = 16,
		overflow = "hidden",
		showShadow = true,
		cardAlignment = "center",
		style,
	} = props;
	const [hoveredIndex, setHoveredIndex] = useState(null);
	const randomMovements = useMemo(() => {
		return cards.map(() => ({
			x: (Math.random() - 0.5) * 2,
			y: (Math.random() - 0.5) * 2,
		}));
	}, [cards.length]);
	return (
		<div
			style={{
				...style,
				width: "100%",
				height: "100%",
				backgroundColor,
				display: "flex",
				flexDirection: layout === "mobile" ? "column" : "row",
				alignItems: "center",
				justifyContent: cardAlignment,
				overflow,
				position: "relative",
				gap: `${cardSpacing}px`,
				padding: "40px",
			}}
		>
			{cards.map((card, index) => {
				const cardImage = card.image || {
					src: "https://framerusercontent.com/images/GfGkADagM4KEibNcIiRUWlfrR0.jpg",
					alt: "Default image",
				};
				return (
					<motion.div
						style={{
							position: "relative",
							width: `${cardWidth}px`,
							height: `${cardWidth * 1.4}px`,
							cursor: "pointer",
							flexShrink: 0,
							zIndex: hoveredIndex === index ? 10 : 1,
						}}
						initial={{
							rotate: card.rotation,
						}}
						animate={{
							rotate:
								hoveredIndex === index
									? card.rotation + hoverRotation
									: card.rotation,
							scale: hoveredIndex === index ? hoverScale : 1,
							x:
								hoveredIndex === index
									? (card.x || 0) + randomMovements[index].x * hoverMove
									: card.x || 0,
							y:
								hoveredIndex === index
									? (card.y || 0) + randomMovements[index].y * hoverMove
									: card.y || 0,
						}}
						transition={{
							type: "spring",
							stiffness: 300,
							damping: 20,
						}}
						onHoverStart={() => setHoveredIndex(index)}
						onHoverEnd={() => setHoveredIndex(null)}
					>
						<div
							style={{
								width: "100%",
								height: "100%",
								borderRadius: `${borderRadius}px`,
								overflow: "hidden",
								boxShadow: showShadow
									? "0 10px 30px rgba(0, 0, 0, 0.2)"
									: "none",
								position: "relative",
							}}
						>
							<img
								src={cardImage.src}
								alt={cardImage.alt}
								style={{
									width: "100%",
									height: "100%",
									objectFit: "cover",
								}}
							/>
							{card.caption && (
								<div
									style={{
										position: "absolute",
										bottom: "20px",
										left: "50%",
										transform: "translateX(-50%)",
										backgroundColor: captionBackgroundColor,
										color: captionTextColor,
										padding: "8px 16px",
										borderRadius: "20px",
										whiteSpace: "nowrap",
										...captionFont,
									}}
								>
									{card.caption}
								</div>
							)}
						</div>
					</motion.div>
				);
			})}
		</div>
	);
}
addPropertyControls(HoverCards, {
	layout: {
		type: ControlType.Enum,
		title: "Layout",
		options: ["desktop", "mobile"],
		optionTitles: ["Desktop", "Mobile"],
		defaultValue: "desktop",
		displaySegmentedControl: true,
	},
	cards: {
		type: ControlType.Array,
		title: "Cards",
		control: {
			type: ControlType.Object,
			controls: {
				image: {
					type: ControlType.ResponsiveImage,
					title: "Image",
				},
				caption: {
					type: ControlType.String,
					title: "Caption",
					defaultValue: "Caption text",
				},
				rotation: {
					type: ControlType.Number,
					title: "Rotation",
					defaultValue: 0,
					min: -45,
					max: 45,
					step: 1,
					unit: "deg",
				},
				x: {
					type: ControlType.Number,
					title: "X Position",
					defaultValue: 0,
					min: -500,
					max: 500,
					step: 5,
					unit: "px",
				},
				y: {
					type: ControlType.Number,
					title: "Y Position",
					defaultValue: 0,
					min: -500,
					max: 500,
					step: 5,
					unit: "px",
				},
			},
		},
		defaultValue: [
			{
				image: {
					src: "https://framerusercontent.com/images/GfGkADagM4KEibNcIiRUWlfrR0.jpg",
					alt: "Card 1",
				},
				caption: "girls just wanna have fun!",
				rotation: -8,
				x: 0,
				y: 0,
			},
			{
				image: {
					src: "https://framerusercontent.com/images/aNsAT3jCvt4zglbWCUoFe33Q.jpg",
					alt: "Card 2",
				},
				caption: "mainstream is not a dirty word",
				rotation: 5,
				x: 0,
				y: 0,
			},
			{
				image: {
					src: "https://framerusercontent.com/images/BYnxEV1zjYb9bhWh1IwBZ1ZoS60.jpg",
					alt: "Card 3",
				},
				caption: "",
				rotation: -3,
				x: 0,
				y: 0,
			},
			{
				image: {
					src: "https://framerusercontent.com/images/2uTNEj5aTl2K3NJaEFWMbnrA.jpg",
					alt: "Card 4",
				},
				caption: "arrogance = old fashioned",
				rotation: 7,
				x: 0,
				y: 0,
			},
			{
				image: {
					src: "https://framerusercontent.com/images/f9RiWoNpmlCMqVRIHz8l8wYfeI.jpg",
					alt: "Card 5",
				},
				caption: "new card",
				rotation: -5,
				x: 0,
				y: 0,
			},
			{
				image: {
					src: "https://framerusercontent.com/images/GfGkADagM4KEibNcIiRUWlfrR0.jpg",
					alt: "Card 6",
				},
				caption: "another card",
				rotation: 4,
				x: 0,
				y: 0,
			},
		],
		maxCount: 10,
	},
	cardAlignment: {
		type: ControlType.Enum,
		title: "Card Placement",
		options: [
			"flex-start",
			"center",
			"flex-end",
			"space-between",
			"space-around",
		],
		optionTitles: ["Start", "Center", "End", "Space Between", "Space Around"],
		defaultValue: "center",
		displaySegmentedControl: false,
	},
	cardWidth: {
		type: ControlType.Number,
		title: "Card Width",
		defaultValue: 250,
		min: 100,
		max: 500,
		step: 10,
		unit: "px",
	},
	cardSpacing: {
		type: ControlType.Number,
		title: "Card Spacing",
		defaultValue: 40,
		min: -500,
		max: 200,
		step: 5,
		unit: "px",
	},
	backgroundColor: {
		type: ControlType.Color,
		title: "Background",
		defaultValue: "#F5F5F5",
	},
	captionBackgroundColor: {
		type: ControlType.Color,
		title: "Caption BG",
		defaultValue: "#FFFFFF",
	},
	captionTextColor: {
		type: ControlType.Color,
		title: "Caption Text",
		defaultValue: "#000000",
	},
	captionFont: {
		type: ControlType.Font,
		title: "Caption Font",
		controls: "extended",
		defaultFontType: "sans-serif",
		defaultValue: {
			fontSize: "14px",
			variant: "Medium",
			letterSpacing: "-0.01em",
			lineHeight: "1em",
		},
	},
	hoverScale: {
		type: ControlType.Number,
		title: "Hover Scale",
		defaultValue: 1.05,
		min: 1,
		max: 1.3,
		step: 0.05,
	},
	hoverRotation: {
		type: ControlType.Number,
		title: "Hover Rotation",
		defaultValue: 3,
		min: -15,
		max: 15,
		step: 1,
		unit: "deg",
	},
	hoverMove: {
		type: ControlType.Number,
		title: "Hover Move",
		defaultValue: 10,
		min: -50,
		max: 50,
		step: 5,
		unit: "px",
	},
	borderRadius: {
		type: ControlType.Number,
		title: "Border Radius",
		defaultValue: 16,
		min: 0,
		max: 50,
		step: 1,
		unit: "px",
	},
	overflow: {
		type: ControlType.Enum,
		title: "Overflow",
		options: ["visible", "hidden"],
		optionTitles: ["Visible", "Hidden"],
		defaultValue: "hidden",
		displaySegmentedControl: true,
	},
	showShadow: {
		type: ControlType.Boolean,
		title: "Shadow",
		defaultValue: true,
		enabledTitle: "On",
		disabledTitle: "Off",
	},
});

// virtual:hover-cards
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"fbc126bea31ebbe6cf64cc6db71380905aa865df749edb6fe0a120a118d79a8c"
			}
			locale={locale}
			locales={locales}
		>
			<HoverCards {...rest} />
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders HoverCardsFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"fbc126bea31ebbe6cf64cc6db71380905aa865df749edb6fe0a120a118d79a8c"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={HoverCards}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, HoverCards);
var hover_cards_default = ComponentWithRoot;
export { hover_cards_default as default };
