// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project fbc126bea31ebbe6 "Untitled", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * image?: {src: string, srcSet?: string, alt?: string} // Image
}} Props

 */
import { routes } from "./chunks/chunk-2F3PHDTH.js";

// virtual:image
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/TyZk9XOGqaKPWcvAGMtZ/OOZgClo2rcOIsFLWZQ75/Ui485h2ey.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getLoadingLazyAtYPosition,
	Image,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var serializationHash = "framer-cQEax";
var variantClassNames = {
	AWfwFeBKO: "framer-v-1j3wqvd",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, image, width, ...props }) => {
	return {
		...props,
		GRpZ7EoWk: image ??
			props.GRpZ7EoWk ?? {
				alt: "man in black and white long-sleeved shirt",
				pixelHeight: 6e3,
				pixelWidth: 4e3,
				src: "https://framerusercontent.com/images/cMjOTqB9qc9vHyxaqxLeE6jIM.jpg?width=4000&height=6000",
				srcSet:
					"https://framerusercontent.com/images/cMjOTqB9qc9vHyxaqxLeE6jIM.jpg?scale-down-to=1024&width=4000&height=6000 682w,https://framerusercontent.com/images/cMjOTqB9qc9vHyxaqxLeE6jIM.jpg?scale-down-to=2048&width=4000&height=6000 1365w,https://framerusercontent.com/images/cMjOTqB9qc9vHyxaqxLeE6jIM.jpg?scale-down-to=4096&width=4000&height=6000 2730w,https://framerusercontent.com/images/cMjOTqB9qc9vHyxaqxLeE6jIM.jpg?width=4000&height=6000 4000w",
			},
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		GRpZ7EoWk: GRpZ7EoWk2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "AWfwFeBKO",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Image
						{...restProps}
						{...gestureHandlers}
						background={{
							alt: "man in black and white long-sleeved shirt",
							fit: "fill",
							loading: getLoadingLazyAtYPosition(componentViewport?.y || 0),
							pixelHeight: 6e3,
							pixelWidth: 4e3,
							sizes: componentViewport?.width || "100vw",
							...toResponsiveImage(GRpZ7EoWk2),
						}}
						className={cx(
							scopingClassNames,
							"framer-1j3wqvd",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"AWfwFeBKO"}
						ref={refBinding}
						style={{
							borderBottomLeftRadius: 12,
							borderBottomRightRadius: 12,
							borderTopLeftRadius: 12,
							borderTopRightRadius: 12,
							...style,
						}}
					/>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-cQEax.framer-j7zpme, .framer-cQEax .framer-j7zpme { display: block; }",
	".framer-cQEax.framer-1j3wqvd { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; height: 520px; justify-content: space-between; overflow: hidden; padding: 40px; position: relative; width: 390px; will-change: var(--framer-will-change-override, transform); }",
];
var FramerUi485h2ey = withCSS(Component, css, "framer-cQEax");
var stdin_default = FramerUi485h2ey;
FramerUi485h2ey.displayName = "Image";
FramerUi485h2ey.defaultProps = {
	height: 520,
	width: 389.5,
};
addPropertyControls(FramerUi485h2ey, {
	GRpZ7EoWk: {
		__defaultAssetReference:
			"data:framer/asset-reference,cMjOTqB9qc9vHyxaqxLeE6jIM.jpg?originalFilename=photo-1573144142793-a87ccabca492%3Fcrop%3Dentropy%26cs%3Dsrgb%26fm%3Djpg%26ixid%3DM3wxMzc5NjJ8MHwxfHNlYXJjaHwxMzV8fGRlc2lnbmVyfGVufDB8fHx8MTc3MTQ1MTc4NHww%26ixlib%3Drb-4.1.jpg&preferredSize=auto&width=4000&height=6000",
		__vekterDefault: {
			alt: "man in black and white long-sleeved shirt",
			assetReference:
				"data:framer/asset-reference,cMjOTqB9qc9vHyxaqxLeE6jIM.jpg?originalFilename=photo-1573144142793-a87ccabca492%3Fcrop%3Dentropy%26cs%3Dsrgb%26fm%3Djpg%26ixid%3DM3wxMzc5NjJ8MHwxfHNlYXJjaHwxMzV8fGRlc2lnbmVyfGVufDB8fHx8MTc3MTQ1MTc4NHww%26ixlib%3Drb-4.1.jpg&preferredSize=auto&width=4000&height=6000",
		},
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
});
addFonts(
	FramerUi485h2ey,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:image
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"fbc126bea31ebbe6cf64cc6db71380905aa865df749edb6fe0a120a118d79a8c"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ImageFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"fbc126bea31ebbe6cf64cc6db71380905aa865df749edb6fe0a120a118d79a8c"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var image_default = ComponentWithRoot;
export { image_default as default };
