// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project fbc126bea31ebbe6 "Untitled", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * location?: string // Location
 * textColor?: string // Text Color
 * background?: string // Background
 * font?: undefined // Font
 * timeFormat?: '12 Hour' | '24 Hour' // Time Format
 * showWeatherSymbol?: boolean // Show Weather Symbol
 * showTemperature?: boolean // Show Temperature
 * temperatureUnit?: 'Celsius' | 'Fahrenheit' // Temperature Unit
 * radius?: number // Radius
 * padding?: number // Padding
}} Props

 */
import { routes } from "./chunks/chunk-2F3PHDTH.js";

// virtual:location-time
import { Fragment } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/AL4QNrclDzTT2J2xp0GG/pyaVqcpJndCkfPamzDwf/LocationTime.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect, useState, startTransition } from "react";
import { addPropertyControls, ControlType } from "unframer";
var __unframerWindow = typeof window !== "undefined" ? window : void 0;
var __unframerNavigator =
	typeof __unframerWindow !== "undefined" ? navigator : void 0;
function LocationTime(props) {
	const {
		locationText,
		textColor,
		backgroundColor,
		font,
		timeFormat,
		borderRadius,
		padding,
		showTemperature,
		temperatureUnit,
		showWeatherSymbol,
	} = props;
	const [time, setTime] = useState("");
	const [temperature, setTemperature] = useState(null);
	const [weatherCode, setWeatherCode] = useState(null);
	const getWeatherIcon = (code, currentHour) => {
		if (code === null) return null;
		const isNight = currentHour < 6 || currentHour >= 20;
		const iconSize = parseInt(font.fontSize) || 15;
		if (code === 0) {
			return isNight ? (
				<svg
					width={iconSize}
					height={iconSize}
					viewBox={"0 0 24 24"}
					fill={"none"}
					stroke={textColor}
					strokeWidth={"2"}
					strokeLinecap={"round"}
					strokeLinejoin={"round"}
				>
					<path d={"M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"} />
				</svg>
			) : (
				<svg
					width={iconSize}
					height={iconSize}
					viewBox={"0 0 24 24"}
					fill={"none"}
					stroke={textColor}
					strokeWidth={"2"}
					strokeLinecap={"round"}
					strokeLinejoin={"round"}
				>
					<circle cx={"12"} cy={"12"} r={"5"} />
					<line x1={"12"} y1={"1"} x2={"12"} y2={"3"} />
					<line x1={"12"} y1={"21"} x2={"12"} y2={"23"} />
					<line x1={"4.22"} y1={"4.22"} x2={"5.64"} y2={"5.64"} />
					<line x1={"18.36"} y1={"18.36"} x2={"19.78"} y2={"19.78"} />
					<line x1={"1"} y1={"12"} x2={"3"} y2={"12"} />
					<line x1={"21"} y1={"12"} x2={"23"} y2={"12"} />
					<line x1={"4.22"} y1={"19.78"} x2={"5.64"} y2={"18.36"} />
					<line x1={"18.36"} y1={"5.64"} x2={"19.78"} y2={"4.22"} />
				</svg>
			);
		}
		if (code >= 1 && code <= 3) {
			return (
				<svg
					width={iconSize}
					height={iconSize}
					viewBox={"0 0 24 24"}
					fill={"none"}
					stroke={textColor}
					strokeWidth={"2"}
					strokeLinecap={"round"}
					strokeLinejoin={"round"}
				>
					<path d={"M18 10h-1.26A8 8 0 1 0 9 20h9a5 5 0 0 0 0-10z"} />
				</svg>
			);
		}
		if (code === 45 || code === 48) {
			return (
				<svg
					width={iconSize}
					height={iconSize}
					viewBox={"0 0 24 24"}
					fill={"none"}
					stroke={textColor}
					strokeWidth={"2"}
					strokeLinecap={"round"}
					strokeLinejoin={"round"}
				>
					<line x1={"3"} y1={"9"} x2={"21"} y2={"9"} />
					<line x1={"3"} y1={"15"} x2={"21"} y2={"15"} />
					<line x1={"6"} y1={"12"} x2={"18"} y2={"12"} />
					<line x1={"6"} y1={"18"} x2={"18"} y2={"18"} />
				</svg>
			);
		}
		if (code >= 51 && code <= 67) {
			return (
				<svg
					width={iconSize}
					height={iconSize}
					viewBox={"0 0 24 24"}
					fill={"none"}
					stroke={textColor}
					strokeWidth={"2"}
					strokeLinecap={"round"}
					strokeLinejoin={"round"}
				>
					<line x1={"16"} y1={"13"} x2={"16"} y2={"21"} />
					<line x1={"8"} y1={"13"} x2={"8"} y2={"21"} />
					<line x1={"12"} y1={"15"} x2={"12"} y2={"23"} />
					<path d={"M20 16.58A5 5 0 0 0 18 7h-1.26A8 8 0 1 0 4 15.25"} />
				</svg>
			);
		}
		if ((code >= 71 && code <= 77) || code === 85 || code === 86) {
			return (
				<svg
					width={iconSize}
					height={iconSize}
					viewBox={"0 0 24 24"}
					fill={"none"}
					stroke={textColor}
					strokeWidth={"2"}
					strokeLinecap={"round"}
					strokeLinejoin={"round"}
				>
					<path d={"M20 17.58A5 5 0 0 0 18 8h-1.26A8 8 0 1 0 4 16.25"} />
					<line x1={"8"} y1={"16"} x2={"8.01"} y2={"16"} />
					<line x1={"8"} y1={"20"} x2={"8.01"} y2={"20"} />
					<line x1={"12"} y1={"18"} x2={"12.01"} y2={"18"} />
					<line x1={"12"} y1={"22"} x2={"12.01"} y2={"22"} />
					<line x1={"16"} y1={"16"} x2={"16.01"} y2={"16"} />
					<line x1={"16"} y1={"20"} x2={"16.01"} y2={"20"} />
				</svg>
			);
		}
		if (code >= 80 && code <= 82) {
			return (
				<svg
					width={iconSize}
					height={iconSize}
					viewBox={"0 0 24 24"}
					fill={"none"}
					stroke={textColor}
					strokeWidth={"2"}
					strokeLinecap={"round"}
					strokeLinejoin={"round"}
				>
					<line x1={"16"} y1={"13"} x2={"16"} y2={"21"} />
					<line x1={"8"} y1={"13"} x2={"8"} y2={"21"} />
					<line x1={"12"} y1={"15"} x2={"12"} y2={"23"} />
					<path d={"M20 16.58A5 5 0 0 0 18 7h-1.26A8 8 0 1 0 4 15.25"} />
				</svg>
			);
		}
		if (code >= 95 && code <= 99) {
			return (
				<svg
					width={iconSize}
					height={iconSize}
					viewBox={"0 0 24 24"}
					fill={"none"}
					stroke={textColor}
					strokeWidth={"2"}
					strokeLinecap={"round"}
					strokeLinejoin={"round"}
				>
					<path d={"M19 16.9A5 5 0 0 0 18 7h-1.26a8 8 0 1 0-11.62 9"} />
					<polyline points={"13 11 9 17 15 17 11 23"} />
				</svg>
			);
		}
		return isNight ? (
			<svg
				width={iconSize}
				height={iconSize}
				viewBox={"0 0 24 24"}
				fill={"none"}
				stroke={textColor}
				strokeWidth={"2"}
				strokeLinecap={"round"}
				strokeLinejoin={"round"}
			>
				<path d={"M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"} />
			</svg>
		) : (
			<svg
				width={iconSize}
				height={iconSize}
				viewBox={"0 0 24 24"}
				fill={"none"}
				stroke={textColor}
				strokeWidth={"2"}
				strokeLinecap={"round"}
				strokeLinejoin={"round"}
			>
				<circle cx={"12"} cy={"12"} r={"5"} />
				<line x1={"12"} y1={"1"} x2={"12"} y2={"3"} />
				<line x1={"12"} y1={"21"} x2={"12"} y2={"23"} />
				<line x1={"4.22"} y1={"4.22"} x2={"5.64"} y2={"5.64"} />
				<line x1={"18.36"} y1={"18.36"} x2={"19.78"} y2={"19.78"} />
				<line x1={"1"} y1={"12"} x2={"3"} y2={"12"} />
				<line x1={"21"} y1={"12"} x2={"23"} y2={"12"} />
				<line x1={"4.22"} y1={"19.78"} x2={"5.64"} y2={"18.36"} />
				<line x1={"18.36"} y1={"5.64"} x2={"19.78"} y2={"4.22"} />
			</svg>
		);
	};
	useEffect(() => {
		if (
			typeof __unframerWindow === "undefined" ||
			(!showTemperature && !showWeatherSymbol)
		)
			return;
		const fetchTemperature = async () => {
			try {
				__unframerNavigator.geolocation.getCurrentPosition(
					async (position) => {
						const { latitude, longitude } = position.coords;
						const response = await fetch(
							`https://api.open-meteo.com/v1/forecast?latitude=${latitude}&longitude=${longitude}&current_weather=true`,
						);
						const data = await response.json();
						const temp = data.current_weather.temperature;
						const code = data.current_weather.weathercode;
						let displayTemp = temp;
						if (temperatureUnit === "F") {
							displayTemp = (temp * 9) / 5 + 32;
						}
						startTransition(() => {
							if (showTemperature) {
								setTemperature(
									`${Math.round(displayTemp)}\xB0${temperatureUnit}`,
								);
							}
							if (showWeatherSymbol) {
								setWeatherCode(code);
							}
						});
					},
					(error) => {
						console.error("Error getting location:", error);
					},
				);
			} catch (error) {
				console.error("Error fetching temperature:", error);
			}
		};
		fetchTemperature();
		const interval = setInterval(fetchTemperature, 6e5);
		return () => clearInterval(interval);
	}, [showTemperature, temperatureUnit, showWeatherSymbol]);
	useEffect(() => {
		if (typeof __unframerWindow === "undefined") return;
		const updateTime = () => {
			const now = /* @__PURE__ */ new Date();
			let hours = now.getHours();
			const minutes = now.getMinutes();
			const seconds = now.getSeconds();
			let timeString = "";
			if (timeFormat === "12h") {
				const ampm = hours >= 12 ? "PM" : "AM";
				hours = hours % 12;
				hours = hours ? hours : 12;
				timeString = `${hours.toString().padStart(2, "0")}:${minutes.toString().padStart(2, "0")} ${ampm}`;
			} else {
				timeString = `${hours.toString().padStart(2, "0")}:${minutes.toString().padStart(2, "0")}`;
			}
			startTransition(() => {
				setTime(timeString);
			});
		};
		updateTime();
		const interval = setInterval(updateTime, 1e3);
		return () => clearInterval(interval);
	}, [timeFormat]);
	return (
		<div
			style={{
				display: "flex",
				flexDirection: "row",
				gap: 8,
				backgroundColor,
				padding,
				borderRadius,
				width: "max-content",
				color: textColor,
				alignItems: "center",
				...font,
			}}
		>
			{locationText} {time}{" "}
			{showTemperature && temperature && `\u2022 ${temperature}`}
			{showWeatherSymbol &&
				weatherCode !== null &&
				getWeatherIcon(weatherCode, /* @__PURE__ */ new Date().getHours())}
		</div>
	);
}
addPropertyControls(LocationTime, {
	locationText: {
		type: ControlType.String,
		title: "Location",
		defaultValue: "Vancouver, Canada",
	},
	textColor: {
		type: ControlType.Color,
		title: "Text Color",
		defaultValue: "#000000",
	},
	backgroundColor: {
		type: ControlType.Color,
		title: "Background",
		defaultValue: "#FFFFFF",
	},
	font: {
		type: ControlType.Font,
		title: "Font",
		defaultValue: {
			fontSize: "15px",
			variant: "Medium",
			letterSpacing: "-0.01em",
			lineHeight: "1.3em",
		},
		controls: "extended",
		defaultFontType: "sans-serif",
	},
	timeFormat: {
		type: ControlType.Enum,
		title: "Time Format",
		options: ["12h", "24h"],
		optionTitles: ["12 Hour", "24 Hour"],
		defaultValue: "12h",
		displaySegmentedControl: true,
	},
	showWeatherSymbol: {
		type: ControlType.Boolean,
		title: "Show Weather Symbol",
		defaultValue: true,
		enabledTitle: "Show",
		disabledTitle: "Hide",
	},
	showTemperature: {
		type: ControlType.Boolean,
		title: "Show Temperature",
		defaultValue: true,
		enabledTitle: "Show",
		disabledTitle: "Hide",
	},
	temperatureUnit: {
		type: ControlType.Enum,
		title: "Temperature Unit",
		options: ["C", "F"],
		optionTitles: ["Celsius", "Fahrenheit"],
		defaultValue: "C",
		displaySegmentedControl: true,
		hidden: ({ showTemperature }) => !showTemperature,
	},
	borderRadius: {
		type: ControlType.Number,
		title: "Radius",
		defaultValue: 8,
		min: 0,
		max: 32,
	},
	padding: {
		type: ControlType.Number,
		title: "Padding",
		defaultValue: 20,
		min: 0,
		max: 50,
	},
});

// virtual:location-time
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"fbc126bea31ebbe6cf64cc6db71380905aa865df749edb6fe0a120a118d79a8c"
			}
			locale={locale}
			locales={locales}
		>
			<LocationTime {...rest} />
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders LocationTimeFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"fbc126bea31ebbe6cf64cc6db71380905aa865df749edb6fe0a120a118d79a8c"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={LocationTime}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, LocationTime);
var location_time_default = ComponentWithRoot;
export { location_time_default as default };
