// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project fbc126bea31ebbe6 "Untitled", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * image2?: {src: string, srcSet?: string, alt?: string} // Image 2
}} Props

 */
import { routes } from "./chunks/chunk-2F3PHDTH.js";

// virtual:main-tile
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/3Ssm2EW8qmJkqY95KLwc/zpST9NYR13N8ptvaVe3X/VnqOR3fjd.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getLoadingLazyAtYPosition,
	Image as Image1,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var Image1WithFX = withFX(Image1);
var serializationHash = "framer-AKDNY";
var variantClassNames = {
	EABW8sWUB: "framer-v-1s6092h",
};
var transition1 = {
	delay: 0,
	duration: 0.4,
	ease: [1, 0, 1, 1],
	type: "tween",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, image2, width, ...props }) => {
	return {
		...props,
		R9YxqtLs5: image2 ?? props.R9YxqtLs5,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		R9YxqtLs5: R9YxqtLs52,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "EABW8sWUB",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1s6092h",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"EABW8sWUB"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-06cbdf7a-4b04-4493-a020-8aa6e2439856, rgb(240, 240, 240))",
							borderBottomLeftRadius: 8,
							borderBottomRightRadius: 8,
							borderTopLeftRadius: 8,
							borderTopRightRadius: 8,
							...style,
						}}
					>
						<Image1
							background={{
								alt: "",
								fit: "fill",
								sizes: `max(${componentViewport?.width || "100vw"}, 1px)`,
							}}
							className={"framer-lnkxsg"}
							layoutDependency={layoutDependency}
							layoutId={"VwtL9gK4W"}
						>
							<Image1WithFX
								__framer__spring={{
									damping: 60,
									delay: 0,
									duration: 0.3,
									ease: [0.44, 0, 0.56, 1],
									mass: 1,
									stiffness: 200,
									type: "spring",
								}}
								__framer__styleTransformEffectEnabled={true}
								__framer__transformTargets={[
									{
										target: {
											opacity: 1,
											rotate: 0,
											rotateX: 0,
											rotateY: 0,
											scale: 1.1,
											skewX: 0,
											skewY: 0,
											x: 0,
											y: 0,
										},
									},
									{
										target: {
											opacity: 1,
											rotate: 0,
											rotateX: 0,
											rotateY: 0,
											scale: 1,
											skewX: 0,
											skewY: 0,
											x: 0,
											y: 0,
										},
									},
								]}
								__framer__transformTrigger={"onInView"}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								background={{
									alt: "",
									fit: "fill",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											(0 +
												((componentViewport?.height || 600) -
													0 -
													((componentViewport?.height || 600) - 0) * 1) /
													2) +
											(0 +
												(((componentViewport?.height || 600) - 0) * 1 -
													0 -
													Math.max(
														(((componentViewport?.height || 600) - 0) * 1 - 0) *
															1,
														(((componentViewport?.height || 600) - 0) * 1 - 0) *
															1.03,
													)) /
													2),
									),
									sizes: `max(max(${componentViewport?.width || "100vw"}, 1px), max(${componentViewport?.width || "100vw"}, 1px) * 1.03)`,
									...toResponsiveImage(R9YxqtLs52),
								}}
								className={"framer-p60elb"}
								layoutDependency={layoutDependency}
								layoutId={"bhOgsmb_S"}
							/>
						</Image1>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-AKDNY.framer-gnzz2, .framer-AKDNY .framer-gnzz2 { display: block; }",
	".framer-AKDNY.framer-1s6092h { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 6px; height: 600px; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 1200px; will-change: var(--framer-will-change-override, transform); }",
	".framer-AKDNY .framer-lnkxsg { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 100%; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-AKDNY .framer-p60elb { flex: 1 0 0px; height: 100%; min-height: 103%; min-width: 103%; position: relative; width: 1px; }",
];
var FramerVnqOR3fjd = withCSS(Component, css, "framer-AKDNY");
var stdin_default = FramerVnqOR3fjd;
FramerVnqOR3fjd.displayName = "Main Tile";
FramerVnqOR3fjd.defaultProps = {
	height: 600,
	width: 1200,
};
addPropertyControls(FramerVnqOR3fjd, {
	R9YxqtLs5: {
		title: "Image 2",
		type: ControlType.ResponsiveImage,
	},
});
addFonts(
	FramerVnqOR3fjd,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:main-tile
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"fbc126bea31ebbe6cf64cc6db71380905aa865df749edb6fe0a120a118d79a8c"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders MainTileFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"fbc126bea31ebbe6cf64cc6db71380905aa865df749edb6fe0a120a118d79a8c"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var main_tile_default = ComponentWithRoot;
export { main_tile_default as default };
