// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project fbc126bea31ebbe6 "Untitled", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { routes } from "./chunks/chunk-2F3PHDTH.js";

// virtual:reel
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/3oxlmEMAUOPXdbnejrYX/pE02u2MyZuvPzI07dI0o/eJOyDWT3l.js
import { jsx as _jsx2 } from "react/jsx-runtime";
import {
	addFonts,
	ComponentViewportProvider,
	cx,
	getFonts,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext,
} from "unframer";
import * as React from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/B2xAlJLcN0gOnt11mSPw/jyRNgY7vYWXe6t31T0wo/Ticker.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	Children,
	useLayoutEffect,
	useEffect,
	useState,
	useRef,
	useMemo,
	useCallback,
	cloneElement,
} from "react";
import { addPropertyControls, ControlType, RenderTarget } from "unframer";
import {
	useReducedMotion,
	LayoutGroup,
	useInView,
	useMotionValue,
	useTransform,
	motion,
	frame,
} from "unframer";
import { resize } from "@motionone/dom";
var MAX_DUPLICATED_ITEMS = 100;
var directionTransformers = {
	left: (offset) => `translateX(-${offset}px)`,
	right: (offset) => `translateX(${offset}px)`,
	top: (offset) => `translateY(-${offset}px)`,
	bottom: (offset) => `translateY(${offset}px)`,
};
function Ticker(props) {
	let {
		slots = [],
		gap,
		padding,
		paddingPerSide,
		paddingTop,
		paddingRight,
		paddingBottom,
		paddingLeft,
		speed,
		hoverFactor,
		direction,
		alignment,
		sizingOptions,
		fadeOptions,
		style,
	} = props;
	const { fadeContent, overflow, fadeWidth, fadeInset, fadeAlpha } =
		fadeOptions;
	const { widthType, heightType } = sizingOptions;
	const paddingValue = paddingPerSide
		? `${paddingTop}px ${paddingRight}px ${paddingBottom}px ${paddingLeft}px`
		: `${padding}px`;
	const currentTarget = RenderTarget.current();
	const isCanvas =
		currentTarget === RenderTarget.canvas ||
		currentTarget === RenderTarget.export;
	const filteredSlots = slots.filter(Boolean);
	const numChildren = Children.count(filteredSlots);
	const hasChildren = numChildren > 0;
	if (direction === true) {
		direction = "left";
	}
	const isHorizontal = direction === "left" || direction === "right";
	const offset = useMotionValue(0);
	const transformer = directionTransformers[direction];
	const transform = useTransform(offset, transformer);
	const parentRef = useRef(null);
	const childrenRef = useMemo(() => {
		return [
			{
				current: null,
			},
			{
				current: null,
			},
		];
	}, []);
	const [size, setSize] = useState({
		parent: null,
		children: null,
	});
	let clonedChildren = null;
	let dupedChildren = [];
	let duplicateBy = 0;
	let opacity = 0;
	if (isCanvas) {
		duplicateBy = numChildren ? Math.floor(10 / numChildren) : 0;
		opacity = 1;
	}
	if (!isCanvas && hasChildren && size.parent) {
		duplicateBy = Math.round((size.parent / size.children) * 2) + 1;
		duplicateBy = Math.min(duplicateBy, MAX_DUPLICATED_ITEMS);
		opacity = 1;
	}
	const measure = useCallback(() => {
		if (hasChildren && parentRef.current) {
			const parentLength = isHorizontal
				? parentRef.current.offsetWidth
				: parentRef.current.offsetHeight;
			const start = childrenRef[0].current
				? isHorizontal
					? childrenRef[0].current.offsetLeft
					: childrenRef[0].current.offsetTop
				: 0;
			const end = childrenRef[1].current
				? isHorizontal
					? childrenRef[1].current.offsetLeft +
						childrenRef[1].current.offsetWidth
					: childrenRef[1].current.offsetTop +
						childrenRef[1].current.offsetHeight
				: 0;
			const childrenLength = end - start + gap;
			setSize({
				parent: parentLength,
				children: childrenLength,
			});
		}
	}, []);
	const childrenStyles = isCanvas
		? {
				contentVisibility: "auto",
			}
		: {};
	if (hasChildren) {
		if (!isCanvas) {
			let initialResize = useRef(true);
			useLayoutEffect(() => {
				frame.read(measure, false, true);
				return resize(parentRef.current, ({ contentSize }) => {
					if (
						!initialResize.current &&
						(contentSize.width || contentSize.height)
					) {
						frame.read(measure, false, true);
					}
					initialResize.current = false;
				});
			}, []);
		}
		clonedChildren = Children.map(filteredSlots, (child, index) => {
			let ref;
			if (index === 0) {
				ref = childrenRef[0];
			}
			if (index === filteredSlots.length - 1) {
				ref = childrenRef[1];
			}
			const size2 = {
				width: widthType ? child.props?.width : "100%",
				height: heightType ? child.props?.height : "100%",
			};
			return (
				<LayoutGroup inherit={"id"}>
					<li ref={ref} style={size2}>
						{
							/* @__PURE__ */ cloneElement(
								child,
								{
									style: {
										...child.props?.style,
										...size2,
										flexShrink: 0,
										...childrenStyles,
									},
									layoutId: child.props.layoutId
										? child.props.layoutId + "-original-" + index
										: void 0,
								},
								child.props?.children,
							)
						}
					</li>
				</LayoutGroup>
			);
		});
	}
	const isInView = isCanvas ? true : useInView(parentRef);
	if (!isCanvas) {
		for (let i = 0; i < duplicateBy; i++) {
			dupedChildren = dupedChildren.concat(
				Children.map(filteredSlots, (child, childIndex) => {
					const size2 = {
						width: widthType ? child.props?.width : "100%",
						height: heightType ? child.props?.height : "100%",
						willChange: !isInView ? void 0 : "transform",
					};
					return (
						<LayoutGroup inherit={"id"}>
							<li style={size2} aria-hidden={true}>
								{
									/* @__PURE__ */ cloneElement(
										child,
										{
											key: i + " " + childIndex,
											style: {
												...child.props?.style,
												width: widthType ? child.props?.width : "100%",
												height: heightType ? child.props?.height : "100%",
												flexShrink: 0,
												...childrenStyles,
											},
											layoutId: child.props.layoutId
												? child.props.layoutId + "-dupe-" + i
												: void 0,
										},
										child.props?.children,
									)
								}
							</li>
						</LayoutGroup>
					);
				}),
			);
		}
	}
	const animateToValue =
		size.children + size.children * Math.round(size.parent / size.children);
	const initialTime = useRef(null);
	const prevTime = useRef(null);
	const xOrY = useRef(0);
	const isHover = useRef(false);
	const isReducedMotion = useReducedMotion();
	const listRef = useRef(null);
	const animationRef = useRef(null);
	if (!isCanvas) {
		useEffect(() => {
			if (isReducedMotion || !animateToValue || !speed) {
				return;
			}
			animationRef.current = listRef.current.animate(
				{
					transform: [transformer(0), transformer(animateToValue)],
				},
				{
					duration: (Math.abs(animateToValue) / speed) * 1e3,
					iterations: Infinity,
					easing: "linear",
				},
			);
			return () => animationRef.current.cancel();
		}, [hoverFactor, animateToValue, speed]);
		const playOrPause = useCallback(() => {
			if (!animationRef.current) return;
			const hidden = document.hidden;
			if (isInView && !hidden && animationRef.current.playState === "paused") {
				animationRef.current.play();
			} else if (
				(!isInView || hidden) &&
				animationRef.current.playState === "running"
			) {
				animationRef.current.pause();
			}
		}, [isInView]);
		useEffect(() => {
			playOrPause();
		}, [isInView, hoverFactor, animateToValue, speed]);
		useEffect(() => {
			document.addEventListener("visibilitychange", playOrPause);
			return () => {
				document.removeEventListener("visibilitychange", playOrPause);
			};
		}, [playOrPause]);
	}
	const fadeDirection = isHorizontal ? "to right" : "to bottom";
	const fadeWidthStart = fadeWidth / 2;
	const fadeWidthEnd = 100 - fadeWidth / 2;
	const fadeInsetStart = clamp(fadeInset, 0, fadeWidthStart);
	const fadeInsetEnd = 100 - fadeInset;
	const fadeMask = `linear-gradient(${fadeDirection}, rgba(0, 0, 0, ${fadeAlpha}) ${fadeInsetStart}%, rgba(0, 0, 0, 1) ${fadeWidthStart}%, rgba(0, 0, 0, 1) ${fadeWidthEnd}%, rgba(0, 0, 0, ${fadeAlpha}) ${fadeInsetEnd}%)`;
	if (!hasChildren) {
		return (
			<section style={placeholderStyles}>
				<div style={emojiStyles}>{"\u2728"}</div>
				<p style={titleStyles}>{"Connect to Content"}</p>
				<p style={subtitleStyles}>
					{"Add layers or components to infinitely loop on your page."}
				</p>
			</section>
		);
	}
	return (
		<section
			style={{
				...containerStyle,
				opacity,
				WebkitMaskImage: fadeContent ? fadeMask : void 0,
				maskImage: fadeContent ? fadeMask : void 0,
				overflow: overflow ? "visible" : "hidden",
				padding: paddingValue,
			}}
			ref={parentRef}
		>
			<motion.ul
				ref={listRef}
				style={{
					...containerStyle,
					gap,
					top:
						direction === "bottom" && isValidNumber(animateToValue)
							? -animateToValue
							: void 0,
					left:
						direction === "right" && isValidNumber(animateToValue)
							? -animateToValue
							: void 0,
					placeItems: alignment,
					position: "relative",
					flexDirection: isHorizontal ? "row" : "column",
					...style,
					willChange: isCanvas || !isInView ? "auto" : "transform",
					transform: transformer(0),
				}}
				onMouseEnter={() => {
					isHover.current = true;
					if (animationRef.current) {
						animationRef.current.playbackRate = hoverFactor;
					}
				}}
				onMouseLeave={() => {
					isHover.current = false;
					if (animationRef.current) {
						animationRef.current.playbackRate = 1;
					}
				}}
			>
				{clonedChildren}
				{dupedChildren}
			</motion.ul>
		</section>
	);
}
Ticker.defaultProps = {
	gap: 10,
	padding: 10,
	sizingOptions: {
		widthType: true,
		heightType: true,
	},
	fadeOptions: {
		fadeContent: true,
		overflow: false,
		fadeWidth: 25,
		fadeAlpha: 0,
		fadeInset: 0,
	},
	direction: true,
};
addPropertyControls(Ticker, {
	slots: {
		type: ControlType.Array,
		title: "Children",
		control: {
			type: ControlType.ComponentInstance,
		},
	},
	speed: {
		type: ControlType.Number,
		title: "Speed",
		min: 0,
		max: 1e3,
		defaultValue: 100,
		unit: "%",
		displayStepper: true,
		step: 5,
	},
	direction: {
		type: ControlType.Enum,
		title: "Direction",
		options: ["left", "right", "top", "bottom"],
		optionIcons: [
			"direction-left",
			"direction-right",
			"direction-up",
			"direction-down",
		],
		optionTitles: ["Left", "Right", "Top", "Bottom"],
		defaultValue: "left",
		displaySegmentedControl: true,
	},
	alignment: {
		type: ControlType.Enum,
		title: "Align",
		options: ["flex-start", "center", "flex-end"],
		optionIcons: {
			direction: {
				right: ["align-top", "align-middle", "align-bottom"],
				left: ["align-top", "align-middle", "align-bottom"],
				top: ["align-left", "align-center", "align-right"],
				bottom: ["align-left", "align-center", "align-right"],
			},
		},
		defaultValue: "center",
		displaySegmentedControl: true,
	},
	gap: {
		type: ControlType.Number,
		title: "Gap",
	},
	padding: {
		title: "Padding",
		type: ControlType.FusedNumber,
		toggleKey: "paddingPerSide",
		toggleTitles: ["Padding", "Padding per side"],
		valueKeys: ["paddingTop", "paddingRight", "paddingBottom", "paddingLeft"],
		valueLabels: ["T", "R", "B", "L"],
		min: 0,
	},
	sizingOptions: {
		type: ControlType.Object,
		title: "Sizing",
		controls: {
			widthType: {
				type: ControlType.Boolean,
				title: "Width",
				enabledTitle: "Auto",
				disabledTitle: "Stretch",
				defaultValue: true,
			},
			heightType: {
				type: ControlType.Boolean,
				title: "Height",
				enabledTitle: "Auto",
				disabledTitle: "Stretch",
				defaultValue: true,
			},
		},
	},
	fadeOptions: {
		type: ControlType.Object,
		title: "Clipping",
		controls: {
			fadeContent: {
				type: ControlType.Boolean,
				title: "Fade",
				defaultValue: true,
			},
			overflow: {
				type: ControlType.Boolean,
				title: "Overflow",
				enabledTitle: "Show",
				disabledTitle: "Hide",
				defaultValue: false,
				hidden(props) {
					return props.fadeContent === true;
				},
			},
			fadeWidth: {
				type: ControlType.Number,
				title: "Width",
				defaultValue: 25,
				min: 0,
				max: 100,
				unit: "%",
				hidden(props) {
					return props.fadeContent === false;
				},
			},
			fadeInset: {
				type: ControlType.Number,
				title: "Inset",
				defaultValue: 0,
				min: 0,
				max: 100,
				unit: "%",
				hidden(props) {
					return props.fadeContent === false;
				},
			},
			fadeAlpha: {
				type: ControlType.Number,
				title: "Opacity",
				defaultValue: 0,
				min: 0,
				max: 1,
				step: 0.05,
				hidden(props) {
					return props.fadeContent === false;
				},
			},
		},
	},
	hoverFactor: {
		type: ControlType.Number,
		title: "Hover",
		min: 0,
		max: 1,
		unit: "x",
		defaultValue: 1,
		step: 0.1,
		displayStepper: true,
		description: "Slows down the speed while you are hovering.",
	},
});
var containerStyle = {
	display: "flex",
	width: "100%",
	height: "100%",
	maxWidth: "100%",
	maxHeight: "100%",
	placeItems: "center",
	margin: 0,
	padding: 0,
	listStyleType: "none",
	textIndent: "none",
};
var placeholderStyles = {
	display: "flex",
	width: "100%",
	height: "100%",
	placeContent: "center",
	placeItems: "center",
	flexDirection: "column",
	color: "#96F",
	background: "rgba(136, 85, 255, 0.1)",
	fontSize: 11,
	overflow: "hidden",
	padding: "20px 20px 30px 20px",
};
var emojiStyles = {
	fontSize: 32,
	marginBottom: 10,
};
var titleStyles = {
	margin: 0,
	marginBottom: 10,
	fontWeight: 600,
	textAlign: "center",
};
var subtitleStyles = {
	margin: 0,
	opacity: 0.7,
	maxWidth: 150,
	lineHeight: 1.5,
	textAlign: "center",
};
var clamp = (num, min, max) => Math.min(Math.max(num, min), max);
var isValidNumber = (value) => typeof value === "number" && !isNaN(value);

// /:https://framerusercontent.com/modules/3oxlmEMAUOPXdbnejrYX/pE02u2MyZuvPzI07dI0o/eJOyDWT3l.js
var TickerFonts = getFonts(Ticker);
var serializationHash = "framer-gG9ua";
var variantClassNames = {
	WIKfBqwSZ: "framer-v-naf0d",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion2.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "WIKfBqwSZ",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-naf0d",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"WIKfBqwSZ"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						<ComponentViewportProvider>
							<SmartComponentScopedContainer
								className={"framer-17twc6k-container"}
								isAuthoredByUser={true}
								isModuleExternal={true}
								layoutDependency={layoutDependency}
								layoutId={"P6jHDyc4M-container"}
								nodeId={"P6jHDyc4M"}
								rendersWithMotion={true}
								scopeId={"eJOyDWT3l"}
							>
								<Ticker
									alignment={"center"}
									direction={"left"}
									fadeOptions={{
										fadeAlpha: 0,
										fadeContent: false,
										fadeInset: 0,
										fadeWidth: 10,
										overflow: false,
									}}
									gap={20}
									height={"100%"}
									hoverFactor={0.5}
									id={"P6jHDyc4M"}
									layoutId={"P6jHDyc4M"}
									padding={0}
									paddingBottom={0}
									paddingLeft={0}
									paddingPerSide={false}
									paddingRight={0}
									paddingTop={0}
									sizingOptions={{
										heightType: true,
										widthType: true,
									}}
									slots={[
										<motion2.div
											className={"framer-m9wyu6"}
											data-framer-name={"Freshworks"}
											layoutDependency={layoutDependency}
											layoutId={"hB8vfLNgI"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-1yhbjgg"}
												fonts={["GF;IBM Plex Mono-regular"]}
												layoutDependency={layoutDependency}
												layoutId={"kZ9dXLHi4"}
												style={{
													"--extracted-r6o4lv":
														"var(--token-99df6449-e9f2-4797-8ee6-4b98273d37fc, rgb(64, 64, 64))",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion2.p
														dir={"auto"}
														style={{
															"--font-selector":
																"R0Y7SUJNIFBsZXggTW9uby1yZWd1bGFy",
															"--framer-font-family":
																'"IBM Plex Mono", monospace',
															"--framer-font-open-type-features":
																"'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on",
															"--framer-font-size": "14px",
															"--framer-letter-spacing": "-0.02em",
															"--framer-line-height": "1.4em",
															"--framer-text-alignment": "center",
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-99df6449-e9f2-4797-8ee6-4b98273d37fc, rgb(64, 64, 64)))",
															"--framer-text-transform": "uppercase",
														}}
													>
														{"Freshworks"}
													</motion2.p>
												</React.Fragment>
											</RichText>
										</motion2.div>,
										<motion2.div
											className={"framer-1bcrs6t"}
											data-framer-name={"AdPushup"}
											layoutDependency={layoutDependency}
											layoutId={"OAPAmebe_"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-qaz3a8"}
												fonts={["GF;IBM Plex Mono-regular"]}
												layoutDependency={layoutDependency}
												layoutId={"JaVzb8QCm"}
												style={{
													"--extracted-r6o4lv":
														"var(--token-99df6449-e9f2-4797-8ee6-4b98273d37fc, rgb(64, 64, 64))",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion2.p
														dir={"auto"}
														style={{
															"--font-selector":
																"R0Y7SUJNIFBsZXggTW9uby1yZWd1bGFy",
															"--framer-font-family":
																'"IBM Plex Mono", monospace',
															"--framer-font-open-type-features":
																"'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on",
															"--framer-font-size": "14px",
															"--framer-letter-spacing": "-0.02em",
															"--framer-line-height": "1.4em",
															"--framer-text-alignment": "center",
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-99df6449-e9f2-4797-8ee6-4b98273d37fc, rgb(64, 64, 64)))",
															"--framer-text-transform": "uppercase",
														}}
													>
														{"AdPushup"}
													</motion2.p>
												</React.Fragment>
											</RichText>
										</motion2.div>,
										<motion2.div
											className={"framer-1touqq0"}
											data-framer-name={"6sense"}
											layoutDependency={layoutDependency}
											layoutId={"uhnK5k813"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-zvbhci"}
												fonts={["GF;IBM Plex Mono-regular"]}
												layoutDependency={layoutDependency}
												layoutId={"F4NYlmScQ"}
												style={{
													"--extracted-r6o4lv":
														"var(--token-99df6449-e9f2-4797-8ee6-4b98273d37fc, rgb(64, 64, 64))",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion2.p
														dir={"auto"}
														style={{
															"--font-selector":
																"R0Y7SUJNIFBsZXggTW9uby1yZWd1bGFy",
															"--framer-font-family":
																'"IBM Plex Mono", monospace',
															"--framer-font-open-type-features":
																"'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on",
															"--framer-font-size": "14px",
															"--framer-letter-spacing": "-0.02em",
															"--framer-line-height": "1.4em",
															"--framer-text-alignment": "center",
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-99df6449-e9f2-4797-8ee6-4b98273d37fc, rgb(64, 64, 64)))",
															"--framer-text-transform": "uppercase",
														}}
													>
														{"6sense"}
													</motion2.p>
												</React.Fragment>
											</RichText>
										</motion2.div>,
										<motion2.div
											className={"framer-nzxeob"}
											data-framer-name={"Portkey"}
											layoutDependency={layoutDependency}
											layoutId={"TQi8upDGW"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-ituhtz"}
												fonts={["GF;IBM Plex Mono-regular"]}
												layoutDependency={layoutDependency}
												layoutId={"LPqD8_5u7"}
												style={{
													"--extracted-r6o4lv":
														"var(--token-99df6449-e9f2-4797-8ee6-4b98273d37fc, rgb(64, 64, 64))",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion2.p
														dir={"auto"}
														style={{
															"--font-selector":
																"R0Y7SUJNIFBsZXggTW9uby1yZWd1bGFy",
															"--framer-font-family":
																'"IBM Plex Mono", monospace',
															"--framer-font-open-type-features":
																"'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on",
															"--framer-font-size": "14px",
															"--framer-letter-spacing": "-0.02em",
															"--framer-line-height": "1.4em",
															"--framer-text-alignment": "center",
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-99df6449-e9f2-4797-8ee6-4b98273d37fc, rgb(64, 64, 64)))",
															"--framer-text-transform": "uppercase",
														}}
													>
														{"Portkey"}
													</motion2.p>
												</React.Fragment>
											</RichText>
										</motion2.div>,
										<motion2.div
											className={"framer-lzmyxe"}
											data-framer-name={"Freshworks Neo"}
											layoutDependency={layoutDependency}
											layoutId={"rNg0Bcq8t"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-zlqdrc"}
												fonts={["GF;IBM Plex Mono-regular"]}
												layoutDependency={layoutDependency}
												layoutId={"MmEGxHczx"}
												style={{
													"--extracted-r6o4lv":
														"var(--token-99df6449-e9f2-4797-8ee6-4b98273d37fc, rgb(64, 64, 64))",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion2.p
														dir={"auto"}
														style={{
															"--font-selector":
																"R0Y7SUJNIFBsZXggTW9uby1yZWd1bGFy",
															"--framer-font-family":
																'"IBM Plex Mono", monospace',
															"--framer-font-open-type-features":
																"'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on",
															"--framer-font-size": "14px",
															"--framer-letter-spacing": "-0.02em",
															"--framer-line-height": "1.4em",
															"--framer-text-alignment": "center",
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-99df6449-e9f2-4797-8ee6-4b98273d37fc, rgb(64, 64, 64)))",
															"--framer-text-transform": "uppercase",
														}}
													>
														{"Freshworks Neo"}
													</motion2.p>
												</React.Fragment>
											</RichText>
										</motion2.div>,
										<motion2.div
											className={"framer-1kn6vq7"}
											data-framer-name={"Scalekit"}
											layoutDependency={layoutDependency}
											layoutId={"Zjoxwvup7"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-y6pzbl"}
												fonts={["GF;IBM Plex Mono-regular"]}
												layoutDependency={layoutDependency}
												layoutId={"wx6WjypqH"}
												style={{
													"--extracted-r6o4lv":
														"var(--token-99df6449-e9f2-4797-8ee6-4b98273d37fc, rgb(64, 64, 64))",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion2.p
														dir={"auto"}
														style={{
															"--font-selector":
																"R0Y7SUJNIFBsZXggTW9uby1yZWd1bGFy",
															"--framer-font-family":
																'"IBM Plex Mono", monospace',
															"--framer-font-open-type-features":
																"'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on",
															"--framer-font-size": "14px",
															"--framer-letter-spacing": "-0.02em",
															"--framer-line-height": "1.4em",
															"--framer-text-alignment": "center",
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-99df6449-e9f2-4797-8ee6-4b98273d37fc, rgb(64, 64, 64)))",
															"--framer-text-transform": "uppercase",
														}}
													>
														{"Scalekit"}
													</motion2.p>
												</React.Fragment>
											</RichText>
										</motion2.div>,
										<motion2.div
											className={"framer-npfdbn"}
											data-framer-name={"Sprouts.ai"}
											layoutDependency={layoutDependency}
											layoutId={"S_Z3272cA"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-1v8p0ue"}
												fonts={["GF;IBM Plex Mono-regular"]}
												layoutDependency={layoutDependency}
												layoutId={"wNq3xQtmH"}
												style={{
													"--extracted-r6o4lv":
														"var(--token-99df6449-e9f2-4797-8ee6-4b98273d37fc, rgb(64, 64, 64))",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion2.p
														dir={"auto"}
														style={{
															"--font-selector":
																"R0Y7SUJNIFBsZXggTW9uby1yZWd1bGFy",
															"--framer-font-family":
																'"IBM Plex Mono", monospace',
															"--framer-font-open-type-features":
																"'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on",
															"--framer-font-size": "14px",
															"--framer-letter-spacing": "-0.02em",
															"--framer-line-height": "1.4em",
															"--framer-text-alignment": "center",
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-99df6449-e9f2-4797-8ee6-4b98273d37fc, rgb(64, 64, 64)))",
															"--framer-text-transform": "uppercase",
														}}
													>
														{"Sprouts.ai"}
													</motion2.p>
												</React.Fragment>
											</RichText>
										</motion2.div>,
										<motion2.div
											className={"framer-eh5a2k"}
											data-framer-name={"Sourcewiz"}
											layoutDependency={layoutDependency}
											layoutId={"riAnXJaDf"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-183pfcp"}
												fonts={["GF;IBM Plex Mono-regular"]}
												layoutDependency={layoutDependency}
												layoutId={"P9YbX9pTG"}
												style={{
													"--extracted-r6o4lv":
														"var(--token-99df6449-e9f2-4797-8ee6-4b98273d37fc, rgb(64, 64, 64))",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion2.p
														dir={"auto"}
														style={{
															"--font-selector":
																"R0Y7SUJNIFBsZXggTW9uby1yZWd1bGFy",
															"--framer-font-family":
																'"IBM Plex Mono", monospace',
															"--framer-font-open-type-features":
																"'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on",
															"--framer-font-size": "14px",
															"--framer-letter-spacing": "-0.02em",
															"--framer-line-height": "1.4em",
															"--framer-text-alignment": "center",
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-99df6449-e9f2-4797-8ee6-4b98273d37fc, rgb(64, 64, 64)))",
															"--framer-text-transform": "uppercase",
														}}
													>
														{"Sourcewiz"}
													</motion2.p>
												</React.Fragment>
											</RichText>
										</motion2.div>,
										<motion2.div
											className={"framer-mf7ibp"}
											data-framer-name={"Strivelabs"}
											layoutDependency={layoutDependency}
											layoutId={"W3qSTWOrS"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-1emfm0k"}
												fonts={["GF;IBM Plex Mono-regular"]}
												layoutDependency={layoutDependency}
												layoutId={"MY5n0oVOU"}
												style={{
													"--extracted-r6o4lv":
														"var(--token-99df6449-e9f2-4797-8ee6-4b98273d37fc, rgb(64, 64, 64))",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion2.p
														dir={"auto"}
														style={{
															"--font-selector":
																"R0Y7SUJNIFBsZXggTW9uby1yZWd1bGFy",
															"--framer-font-family":
																'"IBM Plex Mono", monospace',
															"--framer-font-open-type-features":
																"'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on",
															"--framer-font-size": "14px",
															"--framer-letter-spacing": "-0.02em",
															"--framer-line-height": "1.4em",
															"--framer-text-alignment": "center",
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-99df6449-e9f2-4797-8ee6-4b98273d37fc, rgb(64, 64, 64)))",
															"--framer-text-transform": "uppercase",
														}}
													>
														{"Strivelabs"}
													</motion2.p>
												</React.Fragment>
											</RichText>
										</motion2.div>,
										<motion2.div
											className={"framer-1f6qck6"}
											data-framer-name={"Lastlink"}
											layoutDependency={layoutDependency}
											layoutId={"dn43rRLUS"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-1hd186r"}
												fonts={["GF;IBM Plex Mono-regular"]}
												layoutDependency={layoutDependency}
												layoutId={"YTR4ELjmn"}
												style={{
													"--extracted-r6o4lv":
														"var(--token-99df6449-e9f2-4797-8ee6-4b98273d37fc, rgb(64, 64, 64))",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion2.p
														dir={"auto"}
														style={{
															"--font-selector":
																"R0Y7SUJNIFBsZXggTW9uby1yZWd1bGFy",
															"--framer-font-family":
																'"IBM Plex Mono", monospace',
															"--framer-font-open-type-features":
																"'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on",
															"--framer-font-size": "14px",
															"--framer-letter-spacing": "-0.02em",
															"--framer-line-height": "1.4em",
															"--framer-text-alignment": "center",
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-99df6449-e9f2-4797-8ee6-4b98273d37fc, rgb(64, 64, 64)))",
															"--framer-text-transform": "uppercase",
														}}
													>
														{"Lastlink"}
													</motion2.p>
												</React.Fragment>
											</RichText>
										</motion2.div>,
										<motion2.div
											className={"framer-jebgn6"}
											data-framer-name={"Saff"}
											layoutDependency={layoutDependency}
											layoutId={"iiXibEi4V"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-aetfja"}
												fonts={["GF;IBM Plex Mono-regular"]}
												layoutDependency={layoutDependency}
												layoutId={"yecDAUS3I"}
												style={{
													"--extracted-r6o4lv":
														"var(--token-99df6449-e9f2-4797-8ee6-4b98273d37fc, rgb(64, 64, 64))",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion2.p
														dir={"auto"}
														style={{
															"--font-selector":
																"R0Y7SUJNIFBsZXggTW9uby1yZWd1bGFy",
															"--framer-font-family":
																'"IBM Plex Mono", monospace',
															"--framer-font-open-type-features":
																"'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on",
															"--framer-font-size": "14px",
															"--framer-letter-spacing": "-0.02em",
															"--framer-line-height": "1.4em",
															"--framer-text-alignment": "center",
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-99df6449-e9f2-4797-8ee6-4b98273d37fc, rgb(64, 64, 64)))",
															"--framer-text-transform": "uppercase",
														}}
													>
														{"Saff+"}
													</motion2.p>
												</React.Fragment>
											</RichText>
										</motion2.div>,
										<motion2.div
											className={"framer-v2ifp8"}
											data-framer-name={"Ithra"}
											layoutDependency={layoutDependency}
											layoutId={"HGyuPe7xx"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-1u3u7ax"}
												fonts={["GF;IBM Plex Mono-regular"]}
												layoutDependency={layoutDependency}
												layoutId={"xnpkkJrOD"}
												style={{
													"--extracted-r6o4lv":
														"var(--token-99df6449-e9f2-4797-8ee6-4b98273d37fc, rgb(64, 64, 64))",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion2.p
														dir={"auto"}
														style={{
															"--font-selector":
																"R0Y7SUJNIFBsZXggTW9uby1yZWd1bGFy",
															"--framer-font-family":
																'"IBM Plex Mono", monospace',
															"--framer-font-open-type-features":
																"'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on",
															"--framer-font-size": "14px",
															"--framer-letter-spacing": "-0.02em",
															"--framer-line-height": "1.4em",
															"--framer-text-alignment": "center",
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-99df6449-e9f2-4797-8ee6-4b98273d37fc, rgb(64, 64, 64)))",
															"--framer-text-transform": "uppercase",
														}}
													>
														{"Ithra"}
													</motion2.p>
												</React.Fragment>
											</RichText>
										</motion2.div>,
										<motion2.div
											className={"framer-9vjdkq"}
											data-framer-name={"Haua"}
											layoutDependency={layoutDependency}
											layoutId={"t2Vn7OpTs"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-snkcif"}
												fonts={["GF;IBM Plex Mono-regular"]}
												layoutDependency={layoutDependency}
												layoutId={"vDgrkMYJe"}
												style={{
													"--extracted-r6o4lv":
														"var(--token-99df6449-e9f2-4797-8ee6-4b98273d37fc, rgb(64, 64, 64))",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion2.p
														dir={"auto"}
														style={{
															"--font-selector":
																"R0Y7SUJNIFBsZXggTW9uby1yZWd1bGFy",
															"--framer-font-family":
																'"IBM Plex Mono", monospace',
															"--framer-font-open-type-features":
																"'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on",
															"--framer-font-size": "14px",
															"--framer-letter-spacing": "-0.02em",
															"--framer-line-height": "1.4em",
															"--framer-text-alignment": "center",
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-99df6449-e9f2-4797-8ee6-4b98273d37fc, rgb(64, 64, 64)))",
															"--framer-text-transform": "uppercase",
														}}
													>
														{"Haua"}
													</motion2.p>
												</React.Fragment>
											</RichText>
										</motion2.div>,
										<motion2.div
											className={"framer-18sqpiv"}
											data-framer-name={"Saudi Arabian Football Federation"}
											layoutDependency={layoutDependency}
											layoutId={"j1GfgdkBx"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-8w3yky"}
												fonts={["GF;IBM Plex Mono-regular"]}
												layoutDependency={layoutDependency}
												layoutId={"F8O02AQVI"}
												style={{
													"--extracted-r6o4lv":
														"var(--token-99df6449-e9f2-4797-8ee6-4b98273d37fc, rgb(64, 64, 64))",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion2.p
														dir={"auto"}
														style={{
															"--font-selector":
																"R0Y7SUJNIFBsZXggTW9uby1yZWd1bGFy",
															"--framer-font-family":
																'"IBM Plex Mono", monospace',
															"--framer-font-open-type-features":
																"'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on",
															"--framer-font-size": "14px",
															"--framer-letter-spacing": "-0.02em",
															"--framer-line-height": "1.4em",
															"--framer-text-alignment": "center",
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-99df6449-e9f2-4797-8ee6-4b98273d37fc, rgb(64, 64, 64)))",
															"--framer-text-transform": "uppercase",
														}}
													>
														{"Saudi Arabian Football Federation"}
													</motion2.p>
												</React.Fragment>
											</RichText>
										</motion2.div>,
										<motion2.div
											className={"framer-9vjdkq"}
											data-framer-name={"Haua"}
											layoutDependency={layoutDependency}
											layoutId={"t2Vn7OpTs"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-snkcif"}
												fonts={["GF;IBM Plex Mono-regular"]}
												layoutDependency={layoutDependency}
												layoutId={"vDgrkMYJe"}
												style={{
													"--extracted-r6o4lv":
														"var(--token-99df6449-e9f2-4797-8ee6-4b98273d37fc, rgb(64, 64, 64))",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion2.p
														dir={"auto"}
														style={{
															"--font-selector":
																"R0Y7SUJNIFBsZXggTW9uby1yZWd1bGFy",
															"--framer-font-family":
																'"IBM Plex Mono", monospace',
															"--framer-font-open-type-features":
																"'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on",
															"--framer-font-size": "14px",
															"--framer-letter-spacing": "-0.02em",
															"--framer-line-height": "1.4em",
															"--framer-text-alignment": "center",
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-99df6449-e9f2-4797-8ee6-4b98273d37fc, rgb(64, 64, 64)))",
															"--framer-text-transform": "uppercase",
														}}
													>
														{"Haua"}
													</motion2.p>
												</React.Fragment>
											</RichText>
										</motion2.div>,
										<motion2.div
											className={"framer-u7i7pp"}
											data-framer-name={"Joova"}
											layoutDependency={layoutDependency}
											layoutId={"Z33tJnQd7"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-tu2e0g"}
												fonts={["GF;IBM Plex Mono-regular"]}
												layoutDependency={layoutDependency}
												layoutId={"tP62KF_IV"}
												style={{
													"--extracted-r6o4lv":
														"var(--token-99df6449-e9f2-4797-8ee6-4b98273d37fc, rgb(64, 64, 64))",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion2.p
														dir={"auto"}
														style={{
															"--font-selector":
																"R0Y7SUJNIFBsZXggTW9uby1yZWd1bGFy",
															"--framer-font-family":
																'"IBM Plex Mono", monospace',
															"--framer-font-open-type-features":
																"'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on",
															"--framer-font-size": "14px",
															"--framer-letter-spacing": "-0.02em",
															"--framer-line-height": "1.4em",
															"--framer-text-alignment": "center",
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-99df6449-e9f2-4797-8ee6-4b98273d37fc, rgb(64, 64, 64)))",
															"--framer-text-transform": "uppercase",
														}}
													>
														{"Joova"}
													</motion2.p>
												</React.Fragment>
											</RichText>
										</motion2.div>,
									]}
									speed={30}
									style={{
										height: "100%",
										maxWidth: "100%",
										width: "100%",
									}}
									width={"100%"}
								/>
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</motion2.div>
				</Transition>
			</Variants>
		</LayoutGroup2>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-gG9ua.framer-1sllw0m, .framer-gG9ua .framer-1sllw0m { display: block; }",
	".framer-gG9ua.framer-naf0d { height: 94px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 1972px; }",
	".framer-gG9ua .framer-17twc6k-container { bottom: 0px; flex: none; left: calc(50.00000000000002% - min(100%, 100%) / 2); max-width: 100%; position: absolute; top: 0px; width: 100%; z-index: 2; }",
	".framer-gG9ua .framer-m9wyu6, .framer-gG9ua .framer-1bcrs6t, .framer-gG9ua .framer-1touqq0, .framer-gG9ua .framer-nzxeob, .framer-gG9ua .framer-lzmyxe, .framer-gG9ua .framer-1kn6vq7, .framer-gG9ua .framer-npfdbn, .framer-gG9ua .framer-eh5a2k, .framer-gG9ua .framer-mf7ibp, .framer-gG9ua .framer-1f6qck6, .framer-gG9ua .framer-jebgn6, .framer-gG9ua .framer-v2ifp8, .framer-gG9ua .framer-9vjdkq, .framer-gG9ua .framer-18sqpiv, .framer-gG9ua .framer-u7i7pp { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 18px; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: min-content; }",
	".framer-gG9ua .framer-1yhbjgg, .framer-gG9ua .framer-qaz3a8, .framer-gG9ua .framer-zvbhci, .framer-gG9ua .framer-ituhtz, .framer-gG9ua .framer-zlqdrc, .framer-gG9ua .framer-y6pzbl, .framer-gG9ua .framer-1v8p0ue, .framer-gG9ua .framer-183pfcp, .framer-gG9ua .framer-1emfm0k, .framer-gG9ua .framer-1hd186r, .framer-gG9ua .framer-aetfja, .framer-gG9ua .framer-1u3u7ax, .framer-gG9ua .framer-snkcif, .framer-gG9ua .framer-8w3yky, .framer-gG9ua .framer-tu2e0g { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
];
var FramereJOyDWT3l = withCSS(Component, css, "framer-gG9ua");
var stdin_default = FramereJOyDWT3l;
FramereJOyDWT3l.displayName = "Reel";
FramereJOyDWT3l.defaultProps = {
	height: 94,
	width: 1972,
};
addFonts(
	FramereJOyDWT3l,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "IBM Plex Mono",
					openType: true,
					source: "google",
					style: "normal",
					uiFamilyName: "IBM Plex Mono",
					url: "https://fonts.gstatic.com/s/ibmplexmono/v20/-F63fjptAgt5VM-kVkqdyU8n5i0g1l9kn-s.woff2",
					weight: "400",
				},
			],
		},
		...TickerFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:reel
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"fbc126bea31ebbe6cf64cc6db71380905aa865df749edb6fe0a120a118d79a8c"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ReelFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"fbc126bea31ebbe6cf64cc6db71380905aa865df749edb6fe0a120a118d79a8c"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var reel_default = ComponentWithRoot;
export { reel_default as default };
