// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project fbc126bea31ebbe6 "Untitled", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * image?: string // Image
 * revealStart?: number // Reveal Start
 * revealEnd?: number // Reveal End
 * edge%?: number // Edge %
 * direction?: 'Top → Bottom' | 'Bottom → Top' | 'Left → Right' | 'Right → Left' | 'Top-Left → Bottom-Right' | 'Bottom-Right → Top-Left' | 'Top-Right → Bottom-Left' | 'Bottom-Left → Top-Right' // Direction
 * repeatOnScroll?: boolean // Repeat on Scroll
 * offsetFrom?: 'None' | 'Bottom' | 'Top' | 'Left' | 'Right' // Offset From
 * offsetFromSpacing?: number // Offset From Spacing
 * radius?: number // Radius
 * fadeSpeed?: number // Fade Speed
}} Props

 */
import { routes } from "./chunks/chunk-2F3PHDTH.js";

// virtual:reveal-image-scroll
import { Fragment } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/wO3CXLgPUKXV2Pcl91ID/y94Wwc74xKCEg70tEp5e/Reveal_Image_Scroll.js
import { jsx as _jsx } from "react/jsx-runtime";
import { addPropertyControls, ControlType } from "unframer";
import {
	motion,
	useScroll,
	useSpring,
	useTransform,
	useMotionTemplate,
	useMotionValue,
} from "unframer";
import { useRef, useEffect } from "react";
function Reveal_Image_Scroll(props) {
	const {
		image,
		revealStart,
		revealEnd,
		edgePct,
		directionPreset,
		repeatReveal,
		offsetFrom,
		offsetSpacing,
		radius,
		fadeSpeed,
		style,
	} = props;
	const rootRef = useRef(null);
	const { scrollYProgress } = useScroll({
		target: rootRef,
		offset: ["start 120%", "start -20%"],
	});
	const sp = Math.max(0.25, Math.min(2, fadeSpeed ?? 1));
	const smooth = useSpring(scrollYProgress, {
		stiffness: 120 * sp,
		damping: 30 * Math.sqrt(sp),
		mass: 0.25,
	});
	const maskProg = useMotionValue(0);
	useEffect(() => {
		if (repeatReveal) {
			const u = smooth.on("change", (v) => maskProg.set(v));
			return () => u();
		} else {
			let m = maskProg.get();
			const u = smooth.on("change", (v) => {
				m = Math.max(m, v);
				maskProg.set(m);
			});
			return () => u();
		}
	}, [smooth, repeatReveal]);
	const clamp01 = (v) => Math.max(0, Math.min(1, v));
	const startPct = -100 + clamp01(revealStart) * 100;
	const endPct = 100 + clamp01(revealEnd) * 200;
	const visiblePct = useTransform(maskProg, [0, 1], [startPct, endPct]);
	let globalMask;
	switch (directionPreset) {
		case "Top \u2192 Bottom":
			globalMask = useMotionTemplate`
        linear-gradient(180deg,
          rgba(0,0,0,1) 0%,
          rgba(0,0,0,1) ${visiblePct}%,
          rgba(0,0,0,0.85) calc(${visiblePct}% + ${edgePct}% * 0.2),
          rgba(0,0,0,0.50) calc(${visiblePct}% + ${edgePct}% * 0.5),
          rgba(0,0,0,0.20) calc(${visiblePct}% + ${edgePct}% * 0.8),
          rgba(0,0,0,0.00) calc(${visiblePct}% + ${edgePct}%),
          rgba(0,0,0,0.00) 100%)`;
			break;
		case "Bottom \u2192 Top":
			globalMask = useMotionTemplate`
        linear-gradient(180deg,
          rgba(0,0,0,0.00) 0%,
          rgba(0,0,0,0.00) calc(100% - ${visiblePct}% - ${edgePct}%),
          rgba(0,0,0,0.20) calc(100% - ${visiblePct}% - ${edgePct}% * 0.8),
          rgba(0,0,0,0.50) calc(100% - ${visiblePct}% - ${edgePct}% * 0.5),
          rgba(0,0,0,0.85) calc(100% - ${visiblePct}% - ${edgePct}% * 0.2),
          rgba(0,0,0,1.00) calc(100% - ${visiblePct}%),
          rgba(0,0,0,1.00) 100%)`;
			break;
		case "Left \u2192 Right":
			globalMask = useMotionTemplate`
        linear-gradient(90deg,
          rgba(0,0,0,1) 0%,
          rgba(0,0,0,1) ${visiblePct}%,
          rgba(0,0,0,0.85) calc(${visiblePct}% + ${edgePct}% * 0.2),
          rgba(0,0,0,0.50) calc(${visiblePct}% + ${edgePct}% * 0.5),
          rgba(0,0,0,0.20) calc(${visiblePct}% + ${edgePct}% * 0.8),
          rgba(0,0,0,0.00) calc(${visiblePct}% + ${edgePct}%),
          rgba(0,0,0,0.00) 100%)`;
			break;
		case "Right \u2192 Left":
			globalMask = useMotionTemplate`
        linear-gradient(270deg,
          rgba(0,0,0,1) 0%,
          rgba(0,0,0,1) ${visiblePct}%,
          rgba(0,0,0,0.85) calc(${visiblePct}% + ${edgePct}% * 0.2),
          rgba(0,0,0,0.50) calc(${visiblePct}% + ${edgePct}% * 0.5),
          rgba(0,0,0,0.20) calc(${visiblePct}% + ${edgePct}% * 0.8),
          rgba(0,0,0,0.00) calc(${visiblePct}% + ${edgePct}%),
          rgba(0,0,0,0.00) 100%)`;
			break;
		case "Top-Left \u2192 Bottom-Right":
			globalMask = useMotionTemplate`
        linear-gradient(135deg,
          rgba(0,0,0,1) 0%,
          rgba(0,0,0,1) ${visiblePct}%,
          rgba(0,0,0,0.85) calc(${visiblePct}% + ${edgePct}% * 0.2),
          rgba(0,0,0,0.50) calc(${visiblePct}% + ${edgePct}% * 0.5),
          rgba(0,0,0,0.20) calc(${visiblePct}% + ${edgePct}% * 0.8),
          rgba(0,0,0,0.00) calc(${visiblePct}% + ${edgePct}%),
          rgba(0,0,0,0.00) 100%)`;
			break;
		case "Bottom-Right \u2192 Top-Left":
			globalMask = useMotionTemplate`
        linear-gradient(315deg,
          rgba(0,0,0,0.00) 0%,
          rgba(0,0,0,0.00) calc(100% - ${visiblePct}% - ${edgePct}%),
          rgba(0,0,0,0.20) calc(100% - ${visiblePct}% - ${edgePct}% * 0.8),
          rgba(0,0,0,0.50) calc(100% - ${visiblePct}% - ${edgePct}% * 0.5),
          rgba(0,0,0,0.85) calc(100% - ${visiblePct}% - ${edgePct}% * 0.2),
          rgba(0,0,0,1.00) calc(100% - ${visiblePct}%),
          rgba(0,0,0,1.00) 100%)`;
			break;
		case "Top-Right \u2192 Bottom-Left":
			globalMask = useMotionTemplate`
        linear-gradient(225deg,
          rgba(0,0,0,1) 0%,
          rgba(0,0,0,1) ${visiblePct}%,
          rgba(0,0,0,0.85) calc(${visiblePct}% + ${edgePct}% * 0.2),
          rgba(0,0,0,0.50) calc(${visiblePct}% + ${edgePct}% * 0.5),
          rgba(0,0,0,0.20) calc(${visiblePct}% + ${edgePct}% * 0.8),
          rgba(0,0,0,0.00) calc(${visiblePct}% + ${edgePct}%),
          rgba(0,0,0,0.00) 100%)`;
			break;
		case "Bottom-Left \u2192 Top-Right":
			globalMask = useMotionTemplate`
        linear-gradient(45deg,
          rgba(0,0,0,0.00) 0%,
          rgba(0,0,0,0.00) calc(100% - ${visiblePct}% - ${edgePct}%),
          rgba(0,0,0,0.20) calc(100% - ${visiblePct}% - ${edgePct}% * 0.8),
          rgba(0,0,0,0.50) calc(100% - ${visiblePct}% - ${edgePct}% * 0.5),
          rgba(0,0,0,0.85) calc(100% - ${visiblePct}% - ${edgePct}% * 0.2),
          rgba(0,0,0,1.00) calc(100% - ${visiblePct}%),
          rgba(0,0,0,1.00) 100%)`;
			break;
		default:
			globalMask = useMotionTemplate`
        linear-gradient(180deg,
          rgba(0,0,0,1) 0%,
          rgba(0,0,0,1) ${visiblePct}%,
          rgba(0,0,0,0.85) calc(${visiblePct}% + ${edgePct}% * 0.2),
          rgba(0,0,0,0.50) calc(${visiblePct}% + ${edgePct}% * 0.5),
          rgba(0,0,0,0.20) calc(${visiblePct}% + ${edgePct}% * 0.8),
          rgba(0,0,0,0.00) calc(${visiblePct}% + ${edgePct}%),
          rgba(0,0,0,0.00) 100%)`;
	}
	const offsetDoneAt = 0.6;
	const offsetT = useTransform(maskProg, [0, offsetDoneAt], [0, 1], {
		clamp: true,
	});
	const s = Math.max(20, Math.min(200, offsetSpacing || 80));
	const yFromTop = useTransform(offsetT, [0, 1], [-s, 0]);
	const yFromBottom = useTransform(offsetT, [0, 1], [s, 0]);
	const xFromLeft = useTransform(offsetT, [0, 1], [-s, 0]);
	const xFromRight = useTransform(offsetT, [0, 1], [s, 0]);
	let xVal = 0,
		yVal = 0;
	if (offsetFrom === "Top") yVal = yFromTop;
	if (offsetFrom === "Bottom") yVal = yFromBottom;
	if (offsetFrom === "Left") xVal = xFromLeft;
	if (offsetFrom === "Right") xVal = xFromRight;
	const rootStyle = {
		position: "relative",
		borderRadius: `${Math.max(0, Math.min(100, radius || 0))}px`,
		overflow: "hidden",
		WebkitMaskImage: globalMask,
		maskImage: globalMask,
		WebkitMaskRepeat: "no-repeat",
		maskRepeat: "no-repeat",
		WebkitMaskSize: "100% 100%",
		maskSize: "100% 100%",
		...(style || {}),
	};
	if (!style || (style.width === void 0 && style.height === void 0)) {
		rootStyle.width = 100;
		rootStyle.height = 100;
	}
	return (
		<motion.div ref={rootRef} style={rootStyle}>
			<motion.img
				src={image}
				alt={""}
				draggable={false}
				style={{
					position: "absolute",
					inset: 0,
					width: "100%",
					height: "100%",
					objectFit: "cover",
					borderRadius: "inherit",
					x: xVal,
					y: yVal,
					display: "block",
					userSelect: "none",
					pointerEvents: "none",
					willChange: "transform",
				}}
			/>
		</motion.div>
	);
}
addPropertyControls(Reveal_Image_Scroll, {
	image: {
		title: "Image",
		type: ControlType.Image,
	},
	revealStart: {
		title: "Reveal Start",
		type: ControlType.Number,
		defaultValue: 0.5,
		min: 0,
		max: 1,
		step: 0.01,
	},
	revealEnd: {
		title: "Reveal End",
		type: ControlType.Number,
		defaultValue: 0.5,
		min: 0,
		max: 1,
		step: 0.01,
	},
	edgePct: {
		title: "Edge %",
		type: ControlType.Number,
		defaultValue: 25,
		min: 0,
		max: 70,
		step: 1,
	},
	directionPreset: {
		title: "Direction",
		type: ControlType.Enum,
		options: [
			"Top \u2192 Bottom",
			"Bottom \u2192 Top",
			"Left \u2192 Right",
			"Right \u2192 Left",
			"Top-Left \u2192 Bottom-Right",
			"Bottom-Right \u2192 Top-Left",
			"Top-Right \u2192 Bottom-Left",
			"Bottom-Left \u2192 Top-Right",
		],
		optionTitles: [
			"Top \u2192 Bottom",
			"Bottom \u2192 Top",
			"Left \u2192 Right",
			"Right \u2192 Left",
			"Top-Left \u2192 Bottom-Right",
			"Bottom-Right \u2192 Top-Left",
			"Top-Right \u2192 Bottom-Left",
			"Bottom-Left \u2192 Top-Right",
		],
		defaultValue: "Top \u2192 Bottom",
	},
	repeatReveal: {
		title: "Repeat on Scroll",
		type: ControlType.Boolean,
		defaultValue: true,
	},
	offsetFrom: {
		title: "Offset From",
		type: ControlType.Enum,
		options: ["None", "Bottom", "Top", "Left", "Right"],
		optionTitles: ["None", "Bottom", "Top", "Left", "Right"],
		defaultValue: "None",
	},
	offsetSpacing: {
		title: "Offset From Spacing",
		type: ControlType.Number,
		defaultValue: 80,
		min: 20,
		max: 200,
		step: 1,
	},
	radius: {
		title: "Radius",
		type: ControlType.Number,
		defaultValue: 0,
		min: 0,
		max: 100,
		step: 1,
	},
	fadeSpeed: {
		title: "Fade Speed",
		type: ControlType.Number,
		defaultValue: 1,
		min: 0.25,
		max: 2,
		step: 0.05,
	},
});

// virtual:reveal-image-scroll
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"fbc126bea31ebbe6cf64cc6db71380905aa865df749edb6fe0a120a118d79a8c"
			}
			locale={locale}
			locales={locales}
		>
			<Reveal_Image_Scroll {...rest} />
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders RevealImageScrollFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"fbc126bea31ebbe6cf64cc6db71380905aa865df749edb6fe0a120a118d79a8c"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={Reveal_Image_Scroll}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, Reveal_Image_Scroll);
var reveal_image_scroll_default = ComponentWithRoot;
export { reveal_image_scroll_default as default };
