// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project fbc126bea31ebbe6 "Untitled", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * text?: string // Text
 * text2?: string // Text 2
 * alignment?: 'Left' | 'Center' | 'Right' // Alignment
 * font?: undefined // Font
 * duration?: number // Duration
 * speed?: number // Speed
 * autoPlay?: boolean // Auto Play
 * loop?: boolean // Loop
 * textColor?: string // Text Color
 * scrambleColor?: string // Scramble Color
}} Props

 */
import { routes } from "./chunks/chunk-2F3PHDTH.js";

// virtual:scramble-font
import { Fragment } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/4K5DcAX9aSOMJhN30DQL/NbR3cOffsODn4L5Pf1qw/ScrambleFont.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect, useState, useRef, startTransition } from "react";
import { addPropertyControls, ControlType, RenderTarget } from "unframer";
var __unframerWindow = typeof window !== "undefined" ? window : void 0;
function ScrambleFont(props) {
	const {
		text = "Hello World",
		text2 = "Second Line",
		duration = 2e3,
		typingSpeed = 100,
		autoPlay = true,
		loop = false,
		color = "#000000",
		scrambleColor = "#CCCCCC",
		font,
		alignment = "left",
		style,
	} = props;
	const [displayText, setDisplayText] = useState(text);
	const [displayText2, setDisplayText2] = useState(text2);
	const [revealedCount, setRevealedCount] = useState(0);
	const [revealedCount2, setRevealedCount2] = useState(0);
	const [isAnimating, setIsAnimating] = useState(false);
	const [isMobile, setIsMobile] = useState(false);
	const animationRef = useRef(null);
	const timeoutRef = useRef(null);
	const characters =
		"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*";
	useEffect(() => {
		if (typeof __unframerWindow === "undefined") return;
		const checkMobile = () => {
			startTransition(() => setIsMobile(__unframerWindow.innerWidth <= 768));
		};
		checkMobile();
		__unframerWindow.addEventListener("resize", checkMobile);
		return () => {
			__unframerWindow.removeEventListener("resize", checkMobile);
		};
	}, []);
	const scramble = () => {
		if (RenderTarget.current() === RenderTarget.thumbnail) return;
		startTransition(() => setIsAnimating(true));
		const startTime = Date.now();
		const textLength = text.length;
		const text2Length = text2.length;
		const animate = () => {
			const elapsed = Date.now() - startTime;
			const progress = Math.min(elapsed / duration, 1);
			const revealedChars = Math.floor(progress * textLength);
			const revealedChars2 = Math.floor(progress * text2Length);
			let newText = "";
			let newText2 = "";
			for (let i = 0; i < textLength; i++) {
				if (i < revealedChars) {
					newText += text[i];
				} else {
					newText += characters[Math.floor(Math.random() * characters.length)];
				}
			}
			for (let i = 0; i < text2Length; i++) {
				if (i < revealedChars2) {
					newText2 += text2[i];
				} else {
					newText2 += characters[Math.floor(Math.random() * characters.length)];
				}
			}
			startTransition(() => {
				setDisplayText(newText);
				setDisplayText2(newText2);
				setRevealedCount(revealedChars);
				setRevealedCount2(revealedChars2);
			});
			if (progress < 1) {
				animationRef.current = __unframerWindow.setTimeout(
					animate,
					typingSpeed,
				);
			} else {
				startTransition(() => {
					setDisplayText(text);
					setDisplayText2(text2);
					setRevealedCount(textLength);
					setRevealedCount2(text2Length);
					setIsAnimating(false);
				});
				if (loop) {
					timeoutRef.current = __unframerWindow.setTimeout(() => {
						scramble();
					}, 1e3);
				}
			}
		};
		animate();
	};
	useEffect(() => {
		if (autoPlay && !isAnimating) {
			scramble();
		}
		return () => {
			if (animationRef.current !== null) {
				clearTimeout(animationRef.current);
			}
			if (timeoutRef.current !== null) {
				clearTimeout(timeoutRef.current);
			}
		};
	}, [text, duration, typingSpeed, autoPlay, loop]);
	const handleClick = () => {
		if (!autoPlay && !isAnimating) {
			scramble();
		}
	};
	const getFontSize = () => {
		const baseFontSize = font?.fontSize || "32px";
		if (!isMobile) return baseFontSize;
		const fontSizeString = String(baseFontSize);
		const numericValue = parseFloat(fontSizeString);
		const unit = fontSizeString.replace(/[0-9.]/g, "");
		return `${numericValue * 0.5}${unit}`;
	};
	const responsiveFontSize = getFontSize();
	return (
		<div
			style={{
				...style,
				position: "relative",
				width: "100%",
				minHeight: "1em",
				cursor: !autoPlay ? "pointer" : "default",
				display: "flex",
				flexDirection: "column",
				gap: "0.5em",
				textAlign: alignment,
			}}
			onClick={handleClick}
		>
			<span
				style={{
					whiteSpace: "pre",
					...font,
					fontSize: responsiveFontSize,
					display: "inline-block",
				}}
			>
				{displayText.split("").map((char, index) => (
					<span
						style={{
							color: index < revealedCount ? color : scrambleColor,
						}}
					>
						{char}
					</span>
				))}
			</span>
			<span
				style={{
					whiteSpace: "pre",
					...font,
					fontSize: responsiveFontSize,
					display: "inline-block",
				}}
			>
				{displayText2.split("").map((char, index) => (
					<span
						style={{
							color: index < revealedCount2 ? color : scrambleColor,
						}}
					>
						{char}
					</span>
				))}
			</span>
		</div>
	);
}
addPropertyControls(ScrambleFont, {
	text: {
		type: ControlType.String,
		title: "Text",
		defaultValue: "Hello World",
	},
	text2: {
		type: ControlType.String,
		title: "Text 2",
		defaultValue: "Second Line",
	},
	alignment: {
		type: ControlType.Enum,
		title: "Alignment",
		options: ["left", "center", "right"],
		optionTitles: ["Left", "Center", "Right"],
		defaultValue: "left",
		displaySegmentedControl: true,
	},
	font: {
		type: ControlType.Font,
		title: "Font",
		controls: "extended",
		defaultFontType: "sans-serif",
		defaultValue: {
			fontSize: "32px",
			variant: "Bold",
			letterSpacing: "-0.03em",
			lineHeight: "1em",
		},
	},
	duration: {
		type: ControlType.Number,
		title: "Duration",
		defaultValue: 2e3,
		min: 500,
		max: 1e4,
		step: 100,
		unit: "ms",
	},
	typingSpeed: {
		type: ControlType.Number,
		title: "Speed",
		defaultValue: 100,
		min: 10,
		max: 500,
		step: 10,
		unit: "ms",
	},
	autoPlay: {
		type: ControlType.Boolean,
		title: "Auto Play",
		defaultValue: true,
		enabledTitle: "On",
		disabledTitle: "Off",
	},
	loop: {
		type: ControlType.Boolean,
		title: "Loop",
		defaultValue: false,
		enabledTitle: "On",
		disabledTitle: "Off",
	},
	color: {
		type: ControlType.Color,
		title: "Text Color",
		defaultValue: "#000000",
	},
	scrambleColor: {
		type: ControlType.Color,
		title: "Scramble Color",
		defaultValue: "#CCCCCC",
	},
});

// virtual:scramble-font
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"fbc126bea31ebbe6cf64cc6db71380905aa865df749edb6fe0a120a118d79a8c"
			}
			locale={locale}
			locales={locales}
		>
			<ScrambleFont {...rest} />
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ScrambleFontFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"fbc126bea31ebbe6cf64cc6db71380905aa865df749edb6fe0a120a118d79a8c"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={ScrambleFont}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, ScrambleFont);
var scramble_font_default = ComponentWithRoot;
export { scramble_font_default as default };
