// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project fbc126bea31ebbe6 "Untitled", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * sections?: {id: string, mode: 'Light' | 'Dark'[] // Sections
 * lightBG?: string // Light BG
 * darkBG?: string // Dark BG
 * lightText?: string // Light Text
 * darkText?: string // Dark Text
 * transition?: number // Transition
 * offset?: number // Offset
}} Props

 */
import { routes } from "./chunks/chunk-2F3PHDTH.js";

// virtual:scroll-mode-switcher
import { Fragment } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/cErLfRC3FYpI4mWhgiM0/QY9QnEwttvXlg5lDN6ri/ScrollModeSwitcher.js
import { jsx as _jsx } from "react/jsx-runtime";
import { useEffect, useState, startTransition } from "react";
import { addPropertyControls, ControlType } from "unframer";
var __unframerWindow = typeof window !== "undefined" ? window : void 0;
function ScrollModeSwitcher(props) {
	const {
		sections,
		lightBackground,
		darkBackground,
		lightText,
		darkText,
		transitionDuration,
		offset,
	} = props;
	const [currentMode, setCurrentMode] = useState("light");
	useEffect(() => {
		if (typeof __unframerWindow === "undefined") return;
		const observerOptions = {
			root: null,
			rootMargin: `${-offset}px 0px ${-offset}px 0px`,
			threshold: [0, 0.25, 0.5, 0.75, 1],
		};
		let visibleSections = /* @__PURE__ */ new Map();
		const observerCallback = (entries) => {
			entries.forEach((entry) => {
				const sectionId = entry.target.id;
				if (entry.isIntersecting) {
					visibleSections.set(sectionId, entry.intersectionRatio);
				} else {
					visibleSections.delete(sectionId);
				}
			});
			let maxRatio = 0;
			let mostVisibleId = "";
			visibleSections.forEach((ratio, id) => {
				if (ratio > maxRatio) {
					maxRatio = ratio;
					mostVisibleId = id;
				}
			});
			if (mostVisibleId) {
				const section = sections.find((s) => s.id === mostVisibleId);
				if (section) {
					startTransition(() => setCurrentMode(section.mode));
				}
			}
		};
		const observer = new IntersectionObserver(
			observerCallback,
			observerOptions,
		);
		sections.forEach((section) => {
			const element = document.getElementById(section.id);
			if (element) {
				observer.observe(element);
			}
		});
		return () => {
			observer.disconnect();
			visibleSections.clear();
		};
	}, [sections, offset]);
	const backgroundColor =
		currentMode === "light" ? lightBackground : darkBackground;
	const textColor = currentMode === "light" ? lightText : darkText;
	useEffect(() => {
		if (typeof document === "undefined") return;
		document.body.style.backgroundColor = backgroundColor;
		document.body.style.color = textColor;
		document.body.style.transition = `background-color ${transitionDuration}ms ease, color ${transitionDuration}ms ease`;
	}, [backgroundColor, textColor, transitionDuration]);
	return (
		<div
			style={{
				position: "fixed",
				top: 20,
				right: 20,
				padding: "12px 20px",
				backgroundColor: currentMode === "light" ? "#000" : "#fff",
				color: currentMode === "light" ? "#fff" : "#000",
				borderRadius: 8,
				fontSize: 14,
				fontWeight: 600,
				transition: `all ${transitionDuration}ms ease`,
				zIndex: 9999,
				pointerEvents: "none",
			}}
		>
			{currentMode === "light"
				? "\u2600\uFE0F Light Mode"
				: "\u{1F319} Dark Mode"}
		</div>
	);
}
addPropertyControls(ScrollModeSwitcher, {
	sections: {
		type: ControlType.Array,
		title: "Sections",
		control: {
			type: ControlType.Object,
			controls: {
				id: {
					type: ControlType.String,
					title: "Section ID",
					defaultValue: "section-1",
				},
				mode: {
					type: ControlType.Enum,
					title: "Mode",
					options: ["light", "dark"],
					optionTitles: ["Light", "Dark"],
					defaultValue: "light",
					displaySegmentedControl: true,
				},
			},
		},
		defaultValue: [
			{
				id: "section-1",
				mode: "light",
			},
			{
				id: "section-2",
				mode: "dark",
			},
			{
				id: "section-3",
				mode: "light",
			},
		],
	},
	lightBackground: {
		type: ControlType.Color,
		title: "Light BG",
		defaultValue: "#FFFFFF",
	},
	darkBackground: {
		type: ControlType.Color,
		title: "Dark BG",
		defaultValue: "#000000",
	},
	lightText: {
		type: ControlType.Color,
		title: "Light Text",
		defaultValue: "#000000",
	},
	darkText: {
		type: ControlType.Color,
		title: "Dark Text",
		defaultValue: "#FFFFFF",
	},
	transitionDuration: {
		type: ControlType.Number,
		title: "Transition",
		defaultValue: 500,
		min: 0,
		max: 2e3,
		step: 100,
		unit: "ms",
	},
	offset: {
		type: ControlType.Number,
		title: "Offset",
		defaultValue: 100,
		min: 0,
		max: 500,
		step: 10,
		unit: "px",
	},
});

// virtual:scroll-mode-switcher
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"fbc126bea31ebbe6cf64cc6db71380905aa865df749edb6fe0a120a118d79a8c"
			}
			locale={locale}
			locales={locales}
		>
			<ScrollModeSwitcher {...rest} />
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ScrollModeSwitcherFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"fbc126bea31ebbe6cf64cc6db71380905aa865df749edb6fe0a120a118d79a8c"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={ScrollModeSwitcher}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, ScrollModeSwitcher);
var scroll_mode_switcher_default = ComponentWithRoot;
export { scroll_mode_switcher_default as default };
