// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project fbc126bea31ebbe6 "Untitled", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * navItems?: {label: string, link: string[] // Nav Items
 * alignment?: 'Left' | 'Center' | 'Right' // Alignment
 * background?: string // Background
 * textColor?: string // Text Color
 * activeColor?: string // Active Color
 * hoverColor?: string // Hover Color
 * showSeparator?: boolean // Show Separator
 * separator?: string // Separator
 * separatorColor?: string // Separator Color
 * separatorSpacing?: number // Separator Spacing
 * font?: undefined // Font
 * activeFont?: undefined // Active Font
 * shadow?: boolean // Shadow
 * spacing?: number // Spacing
}} Props

 */
import { routes } from "./chunks/chunk-2F3PHDTH.js";

// virtual:secondary-navigation
import { Fragment } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/6pklEvfoijrqeP381gpS/eIpwaoBMb14K2IQWvffi/SecondaryNavigation.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { addPropertyControls, ControlType } from "unframer";
import { useState, startTransition } from "react";
var __unframerWindow = typeof window !== "undefined" ? window : void 0;
function SecondaryNavigation(props) {
	const {
		items = [
			{
				label: "Home",
				link: "/",
			},
			{
				label: "Products",
				link: "/products",
			},
			{
				label: "Category",
				link: "/products/category",
			},
		],
		backgroundColor = "#FFFFFF",
		textColor = "#000000",
		activeColor = "#0099FF",
		hoverColor = "#666666",
		separatorColor = "#CCCCCC",
		font,
		activeFont,
		shadow = true,
		spacing = 8,
		separatorSpacing = 8,
		showSeparator = true,
		separatorSymbol = "/",
		alignment = "flex-start",
		style,
	} = props;
	const [hoveredIndex, setHoveredIndex] = useState(null);
	const handleClick = (link, index) => {
		if (typeof __unframerWindow === "undefined") return;
		if (index === items.length - 1) {
			return;
		}
		__unframerWindow.location.href = link;
	};
	return (
		<nav
			style={{
				...style,
				position: "relative",
				backgroundColor,
				display: "flex",
				alignItems: "center",
				justifyContent: alignment,
				boxShadow: shadow ? "0 2px 8px rgba(0,0,0,0.08)" : "none",
				padding: "16px 24px",
				gap: spacing,
				flexWrap: "wrap",
				...font,
			}}
		>
			{items.map((item, index) => {
				const isLast = index === items.length - 1;
				const isHovered = hoveredIndex === index;
				return (
					<div
						style={{
							display: "flex",
							alignItems: "center",
							gap: spacing,
						}}
					>
						<button
							onClick={() => handleClick(item.link, index)}
							onMouseEnter={() => startTransition(() => setHoveredIndex(index))}
							onMouseLeave={() => startTransition(() => setHoveredIndex(null))}
							style={{
								background: "none",
								border: "none",
								cursor: isLast ? "default" : "pointer",
								padding: "4px 0px",
								color: isLast
									? activeColor
									: isHovered
										? hoverColor
										: textColor,
								transition: "color 0.2s ease",
								...(isLast ? activeFont : font),
							}}
						>
							{item.label}
							{isLast && "_"}
						</button>
						{!isLast && showSeparator && (
							<span
								style={{
									color: separatorColor,
									userSelect: "none",
									paddingLeft: separatorSpacing,
									paddingRight: separatorSpacing,
									...font,
								}}
							>
								{separatorSymbol}
							</span>
						)}
					</div>
				);
			})}
		</nav>
	);
}
addPropertyControls(SecondaryNavigation, {
	items: {
		type: ControlType.Array,
		title: "Nav Items",
		control: {
			type: ControlType.Object,
			controls: {
				label: {
					type: ControlType.String,
					title: "Label",
					defaultValue: "Page",
				},
				link: {
					type: ControlType.String,
					title: "Link",
					defaultValue: "/",
				},
			},
		},
		defaultValue: [
			{
				label: "Home",
				link: "/",
			},
			{
				label: "Products",
				link: "/products",
			},
			{
				label: "Category",
				link: "/products/category",
			},
		],
	},
	alignment: {
		type: ControlType.Enum,
		title: "Alignment",
		options: ["flex-start", "center", "flex-end"],
		optionTitles: ["Left", "Center", "Right"],
		defaultValue: "flex-start",
		displaySegmentedControl: true,
	},
	backgroundColor: {
		type: ControlType.Color,
		title: "Background",
		defaultValue: "#FFFFFF",
	},
	textColor: {
		type: ControlType.Color,
		title: "Text Color",
		defaultValue: "#000000",
	},
	activeColor: {
		type: ControlType.Color,
		title: "Active Color",
		defaultValue: "#0099FF",
	},
	hoverColor: {
		type: ControlType.Color,
		title: "Hover Color",
		defaultValue: "#666666",
	},
	showSeparator: {
		type: ControlType.Boolean,
		title: "Show Separator",
		defaultValue: true,
		enabledTitle: "Show",
		disabledTitle: "Hide",
	},
	separatorSymbol: {
		type: ControlType.String,
		title: "Separator",
		defaultValue: "/",
		hidden: ({ showSeparator }) => !showSeparator,
	},
	separatorColor: {
		type: ControlType.Color,
		title: "Separator Color",
		defaultValue: "#CCCCCC",
		hidden: ({ showSeparator }) => !showSeparator,
	},
	separatorSpacing: {
		type: ControlType.Number,
		title: "Separator Spacing",
		defaultValue: 8,
		min: 0,
		max: 32,
		step: 1,
		unit: "px",
		hidden: ({ showSeparator }) => !showSeparator,
	},
	font: {
		type: ControlType.Font,
		title: "Font",
		controls: "extended",
		defaultFontType: "sans-serif",
		defaultValue: {
			fontSize: "14px",
			variant: "Medium",
			letterSpacing: "-0.01em",
			lineHeight: "1em",
		},
	},
	activeFont: {
		type: ControlType.Font,
		title: "Active Font",
		controls: "extended",
		defaultFontType: "sans-serif",
		defaultValue: {
			fontSize: "14px",
			variant: "Semibold",
			letterSpacing: "-0.01em",
			lineHeight: "1em",
		},
	},
	shadow: {
		type: ControlType.Boolean,
		title: "Shadow",
		defaultValue: true,
		enabledTitle: "Show",
		disabledTitle: "Hide",
	},
	spacing: {
		type: ControlType.Number,
		title: "Spacing",
		defaultValue: 8,
		min: 0,
		max: 32,
		step: 1,
		unit: "px",
	},
});

// virtual:secondary-navigation
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"fbc126bea31ebbe6cf64cc6db71380905aa865df749edb6fe0a120a118d79a8c"
			}
			locale={locale}
			locales={locales}
		>
			<SecondaryNavigation {...rest} />
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders SecondaryNavigationFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"fbc126bea31ebbe6cf64cc6db71380905aa865df749edb6fe0a120a118d79a8c"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={SecondaryNavigation}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, SecondaryNavigation);
var secondary_navigation_default = ComponentWithRoot;
export { secondary_navigation_default as default };
