// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project fbc126bea31ebbe6 "Untitled", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Product' | 'Design system' | 'Variant 3' | 'Variant 5' | 'Variant 6' // Variant
 * title?: string // Title
 * onjbNAXJiAiChange?: undefined // onjbNAXJiAiChange
}} Props

 */
import { routes } from "./chunks/chunk-2F3PHDTH.js";

// virtual:skill-labels
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/TokB3xxVzIW3WLIX205m/mRoei0XqYyyuOYHeAMrD/NjbueEOlj.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	SVG,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/fg6qVnxCq0i0qkBGdPkc/OoszHOX99fiQIZAxe9OT/octs4y9CP.js
import { fontStore } from "unframer";
fontStore.loadFonts(["GF;Geist Mono-regular", "GF;Geist Mono-700"]);
var fonts = [
	{
		explicitInter: true,
		fonts: [
			{
				cssFamilyName: "Geist Mono",
				openType: true,
				source: "google",
				style: "normal",
				uiFamilyName: "Geist Mono",
				url: "https://fonts.gstatic.com/s/geistmono/v4/or3yQ6H-1_WfwkMZI_qYPLs1a-t7PU0AbeE9KJ5W7ihaO_CS.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Geist Mono",
				openType: true,
				source: "google",
				style: "normal",
				uiFamilyName: "Geist Mono",
				url: "https://fonts.gstatic.com/s/geistmono/v4/or3yQ6H-1_WfwkMZI_qYPLs1a-t7PU0AbeHaL55W7ihaO_CS.woff2",
				weight: "700",
			},
		],
	},
];
var css = [
	`.framer-cbtgO .framer-styles-preset-lq42z8:not(.rich-text-wrapper), .framer-cbtgO .framer-styles-preset-lq42z8.rich-text-wrapper p { --framer-font-family: "Geist Mono", monospace; --framer-font-family-bold: "Geist Mono", monospace; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 12px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-letter-spacing: -0.02em; --framer-line-height: 1.4em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-99df6449-e9f2-4797-8ee6-4b98273d37fc, #001b25); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: uppercase; }`,
	`@media (max-width: 1199px) and (min-width: 390px) { .framer-cbtgO .framer-styles-preset-lq42z8:not(.rich-text-wrapper), .framer-cbtgO .framer-styles-preset-lq42z8.rich-text-wrapper p { --framer-font-family: "Geist Mono", monospace; --framer-font-family-bold: "Geist Mono", monospace; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 14px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-letter-spacing: -0.02em; --framer-line-height: 1.4em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-99df6449-e9f2-4797-8ee6-4b98273d37fc, #001b25); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: uppercase; } }`,
	`@media (max-width: 389px) and (min-width: 0px) { .framer-cbtgO .framer-styles-preset-lq42z8:not(.rich-text-wrapper), .framer-cbtgO .framer-styles-preset-lq42z8.rich-text-wrapper p { --framer-font-family: "Geist Mono", monospace; --framer-font-family-bold: "Geist Mono", monospace; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 14px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-letter-spacing: -0.02em; --framer-line-height: 1.4em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-99df6449-e9f2-4797-8ee6-4b98273d37fc, #001b25); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: uppercase; } }`,
];
var className = "framer-cbtgO";

// /:https://framerusercontent.com/modules/TokB3xxVzIW3WLIX205m/mRoei0XqYyyuOYHeAMrD/NjbueEOlj.js
var cycleOrder = [
	"IhtjFU4Lt",
	"gikqy4egp",
	"f3PPmXtq4",
	"SVGlsm2J4",
	"S5z5ngRk7",
];
var serializationHash = "framer-EIRiU";
var variantClassNames = {
	f3PPmXtq4: "framer-v-1nu797j",
	gikqy4egp: "framer-v-1swtu2w",
	IhtjFU4Lt: "framer-v-1cmcmiq",
	S5z5ngRk7: "framer-v-i72elh",
	SVGlsm2J4: "framer-v-ondg8q",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"Design system": "gikqy4egp",
	"Variant 3": "f3PPmXtq4",
	"Variant 5": "SVGlsm2J4",
	"Variant 6": "S5z5ngRk7",
	Product: "IhtjFU4Lt",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, title, width, ...props }) => {
	return {
		...props,
		jbNAxJiAi: title ?? props.jbNAxJiAi ?? "Product",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "IhtjFU4Lt",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		jbNAxJiAi: jbNAxJiAi2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "IhtjFU4Lt",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1cmcmiq",
							className2,
							classNames,
						)}
						data-framer-name={"Product"}
						layoutDependency={layoutDependency}
						layoutId={"IhtjFU4Lt"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-c1b219e1-f175-48e0-870c-d1ed2360074b, rgb(237, 237, 237))",
							borderBottomLeftRadius: 30,
							borderBottomRightRadius: 30,
							borderTopLeftRadius: 30,
							borderTopRightRadius: 30,
							...style,
						}}
						{...addPropertyOverrides(
							{
								f3PPmXtq4: {
									"data-framer-name": "Variant 3",
								},
								gikqy4egp: {
									"data-framer-name": "Design system",
								},
								S5z5ngRk7: {
									"data-framer-name": "Variant 6",
								},
								SVGlsm2J4: {
									"data-framer-name": "Variant 5",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<SVG
							className={"framer-liy6by"}
							data-framer-name={"laptop-phone-sync"}
							layout={"position"}
							layoutDependency={layoutDependency}
							layoutId={"lU6NRPXTt"}
							opacity={1}
							svg={
								'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 14 14"><path d="M 11.054 5.687 C 11.442 5.687 11.834 5.687 12.102 5.723 C 12.388 5.762 12.663 5.849 12.886 6.072 C 13.109 6.295 13.196 6.57 13.235 6.857 C 13.271 7.124 13.271 7.458 13.271 7.846 L 13.271 10.237 C 13.271 10.625 13.271 10.959 13.235 11.227 C 13.196 11.514 13.109 11.788 12.886 12.011 C 12.663 12.234 12.388 12.321 12.102 12.36 C 11.834 12.396 11.5 12.396 11.112 12.396 C 10.724 12.396 10.333 12.396 10.065 12.36 C 9.778 12.321 9.503 12.234 9.28 12.011 C 9.057 11.788 8.97 11.514 8.932 11.227 C 8.896 10.959 8.896 10.625 8.896 10.237 L 8.896 7.846 C 8.896 7.458 8.896 7.124 8.932 6.857 C 8.97 6.57 9.057 6.295 9.28 6.072 C 9.503 5.849 9.778 5.762 10.065 5.723 C 10.333 5.687 10.667 5.687 11.054 5.687 Z" fill="rgb(99, 99, 99)"></path><path d="M 8.021 10.063 L 1.565 10.063 L 0.823 11.313 C 0.818 11.321 0.814 11.328 0.81 11.336 C 0.55 11.841 0.938 12.396 1.468 12.396 L 8.021 12.396 Z" fill="rgb(99, 99, 99)"></path><path d="M 5.219 1.605 L 9.365 1.605 C 10.025 1.605 10.565 1.605 10.992 1.662 C 11.437 1.722 11.824 1.852 12.132 2.16 C 12.44 2.469 12.57 2.855 12.63 3.301 C 12.687 3.727 12.687 4.267 12.687 4.928 L 12.687 4.96 C 12.522 4.907 12.363 4.876 12.218 4.857 C 11.891 4.813 11.41 4.813 11.054 4.813 C 10.698 4.813 10.275 4.813 9.948 4.857 C 9.565 4.909 9.074 5.041 8.661 5.454 C 8.248 5.867 8.116 6.358 8.064 6.741 C 8.021 7.067 8.021 7.452 8.021 7.808 L 8.021 9.188 L 1.896 9.188 L 1.896 4.928 C 1.896 4.267 1.896 3.727 1.953 3.301 C 2.013 2.855 2.143 2.469 2.451 2.16 C 2.759 1.852 3.146 1.722 3.591 1.662 C 4.018 1.605 4.558 1.605 5.219 1.605 Z" fill="rgb(99, 99, 99)" opacity="0.4"></path></svg>'
							}
							svgContentId={9610893746}
							withExternalLayout={true}
						/>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-daf1ru"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"oQMcfHGFQ"}
							style={{
								"--extracted-r6o4lv": "rgb(99, 99, 99)",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							text={jbNAxJiAi2}
							variants={{
								f3PPmXtq4: {
									"--extracted-r6o4lv":
										"var(--token-bcb61851-9cde-420d-a28c-691ae35dc7a7, rgb(99, 99, 99))",
								},
								gikqy4egp: {
									"--extracted-r6o4lv":
										"var(--token-bcb61851-9cde-420d-a28c-691ae35dc7a7, rgb(99, 99, 99))",
								},
								S5z5ngRk7: {
									"--extracted-r6o4lv":
										"var(--token-97cc7486-4632-40e1-a749-4aa2bfb08ba3, rgb(171, 171, 171))",
								},
								SVGlsm2J4: {
									"--extracted-r6o4lv":
										"var(--token-97cc7486-4632-40e1-a749-4aa2bfb08ba3, rgb(171, 171, 171))",
								},
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
							{...addPropertyOverrides(
								{
									f3PPmXtq4: {
										children: (
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-lq42z8"}
													data-styles-preset={"octs4y9CP"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-bcb61851-9cde-420d-a28c-691ae35dc7a7, rgb(99, 99, 99)))",
													}}
												>
													{"Brand"}
												</motion.p>
											</React.Fragment>
										),
										text: void 0,
									},
									gikqy4egp: {
										children: (
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-lq42z8"}
													data-styles-preset={"octs4y9CP"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-bcb61851-9cde-420d-a28c-691ae35dc7a7, rgb(99, 99, 99)))",
													}}
												>
													{"Design system"}
												</motion.p>
											</React.Fragment>
										),
										text: void 0,
									},
									S5z5ngRk7: {
										children: (
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-lq42z8"}
													data-styles-preset={"octs4y9CP"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-97cc7486-4632-40e1-a749-4aa2bfb08ba3, rgb(171, 171, 171)))",
													}}
												>
													{"Design system"}
												</motion.p>
											</React.Fragment>
										),
										text: void 0,
									},
									SVGlsm2J4: {
										children: (
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-lq42z8"}
													data-styles-preset={"octs4y9CP"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-97cc7486-4632-40e1-a749-4aa2bfb08ba3, rgb(171, 171, 171)))",
													}}
												>
													{"Design system"}
												</motion.p>
											</React.Fragment>
										),
										text: void 0,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-lq42z8"}
									data-styles-preset={"octs4y9CP"}
									dir={"auto"}
									style={{
										"--framer-text-color":
											"var(--extracted-r6o4lv, rgb(99, 99, 99))",
									}}
								>
									{"Product"}
								</motion.p>
							</React.Fragment>
						</RichText>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-EIRiU.framer-1k88n6i, .framer-EIRiU .framer-1k88n6i { display: block; }",
	".framer-EIRiU.framer-1cmcmiq { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 4px; position: relative; width: 87px; will-change: var(--framer-will-change-override, transform); }",
	".framer-EIRiU .framer-liy6by { flex: none; height: 14px; position: relative; width: 14px; }",
	".framer-EIRiU .framer-daf1ru { flex: none; height: auto; max-width: 75%; position: relative; white-space: pre-wrap; width: auto; word-break: break-word; word-wrap: break-word; }",
	".framer-EIRiU.framer-v-1swtu2w.framer-1cmcmiq, .framer-EIRiU.framer-v-ondg8q.framer-1cmcmiq, .framer-EIRiU.framer-v-i72elh.framer-1cmcmiq { width: 129px; }",
	".framer-EIRiU.framer-v-1swtu2w .framer-daf1ru, .framer-EIRiU.framer-v-ondg8q .framer-daf1ru, .framer-EIRiU.framer-v-i72elh .framer-daf1ru { flex: 1 0 0px; width: 1px; }",
	".framer-EIRiU.framer-v-1nu797j.framer-1cmcmiq { width: 83px; }",
	...css,
];
var FramerNjbueEOlj = withCSS(Component, css2, "framer-EIRiU");
var stdin_default = FramerNjbueEOlj;
FramerNjbueEOlj.displayName = "Skill Labels";
FramerNjbueEOlj.defaultProps = {
	height: 25,
	width: 87,
};
addPropertyControls(FramerNjbueEOlj, {
	variant: {
		options: ["IhtjFU4Lt", "gikqy4egp", "f3PPmXtq4", "SVGlsm2J4", "S5z5ngRk7"],
		optionTitles: [
			"Product",
			"Design system",
			"Variant 3",
			"Variant 5",
			"Variant 6",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
	jbNAxJiAi: {
		defaultValue: "Product",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	onjbNAxJiAiChange: {
		changes: "jbNAxJiAi",
		type: ControlType.ChangeHandler,
	},
});
addFonts(
	FramerNjbueEOlj,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:skill-labels
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"fbc126bea31ebbe6cf64cc6db71380905aa865df749edb6fe0a120a118d79a8c"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders SkillLabelsFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"fbc126bea31ebbe6cf64cc6db71380905aa865df749edb6fe0a120a118d79a8c"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var skill_labels_default = ComponentWithRoot;
export { skill_labels_default as default };
