// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project fbc126bea31ebbe6 "Untitled", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * experiences?: {company: string, role: string, period: string, startYear: number, endYear: number, description: string, tags: string[], isCurrent: boolean, id: number, logo: {src: string, srcSet?: string, alt?: string}, logoSvg: string[] // Experiences
 * rulerSettings?: {start: number, end: number, pixelsPerYear: number, tickColor: string, tickColorActive: string, yearColor: string, yearColorActive: string, yearFontSize: number, yearSpacing: number, rulerYearGap: number, tickSpacing: number, highlightLineWidth: number // Ruler Settings
 * layout&Spacing?: {isMobileView: boolean, outerPadding: number, rulerCardGap: number, cardHeight: number, cardSpacing: number, cardBorderRadius: number, containerBorderRadius: number, expandedFlex: number, collapsedFlex: number, cardPadding: number, periodMarginBottom: number, companyMarginBottom: number, descriptionMarginTop: number, tagsMarginTop: number, logoSize: number, logoMarginBottom: number, logoBorderRadius: number, tagPadding: string, tagBorderRadius: number, showTags: boolean, mobileRulerWidth: number, mobileCollapsedHeight: number, mobileExpandedHeight: number // Layout & Spacing
 * colors?: {background: string, cardBackground: string, cardBackgroundExpanded: string, border: string, borderExpanded: string, logoBackground: string, logoBorderColor: string, logoBorderColorActive: string, logoTheme: 'light' | 'dark' // Colors
 * defaultCardColors?: {text: string, subtext: string, periodColor: string, logoColorLight: string, logoColorDark: string // Default Card Colors
 * expandedCardColors?: {text: string, subtext: string, periodColor: string, descriptionColor: string, tagTextColor: string, tagBorderColor: string, tagBackgroundColor: string, logoColor: string // Expanded Card Colors
 * typography?: {company: undefined, role: undefined, period: undefined, description: undefined, tag: undefined // Typography
 * liveIndicator?: {show: boolean, color: string, size: number // Live Indicator
 * animation?: {duration: number // Animation
}} Props

 */
import { Timeline } from "./chunks/chunk-577DGWYL.js";
import { routes } from "./chunks/chunk-2F3PHDTH.js";

// virtual:timeline
import { Fragment } from "react";
import { ContextProviders } from "unframer";
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"fbc126bea31ebbe6cf64cc6db71380905aa865df749edb6fe0a120a118d79a8c"
			}
			locale={locale}
			locales={locales}
		>
			<Timeline {...rest} />
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders TimelineFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"fbc126bea31ebbe6cf64cc6db71380905aa865df749edb6fe0a120a118d79a8c"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={Timeline}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, Timeline);
var timeline_default = ComponentWithRoot;
export { timeline_default as default };
