// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project fbc126bea31ebbe6 "Untitled", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * title?: string // Title
 * onOlZgGaaROCHange?: undefined // onOlZgGaaROCHange
 * cardNumber?: string // Card Number
 * onzlZzX8eIdChange?: undefined // onzlZzX8eIdChange
 * subtext?: string // Subtext
 * onNXUEAP0hUCHange?: undefined // onNXUEAP0hUCHange
 * points?: string // Points
 * onjfQECfO6TCHange?: undefined // onjfQECfO6TCHange
}} Props

 */
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-4KFXLS6S.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-7G5KBBVY.js";
import { className, css, fonts } from "./chunks/chunk-MCFUM3XF.js";
import { routes } from "./chunks/chunk-2F3PHDTH.js";

// virtual:values-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/dhXItvlAItvZ4VC1hYi4/bP3jmIadzB4SNBrnDjfp/WwAgXVlkt.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var enabledGestures = {
	fg7GobUs3: {
		hover: true,
	},
};
var serializationHash = "framer-Dub4f";
var variantClassNames = {
	fg7GobUs3: "framer-v-1dmwn3d",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({
	cardNumber,
	height,
	id,
	points,
	subtext,
	title,
	width,
	...props
}) => {
	return {
		...props,
		jfQEcfO6T:
			points ??
			props.jfQEcfO6T ??
			"\u2713 Problem statement def\n\u2713 Feature prioritization\n\u2713 North Star Metric",
		NXUEAp0hU:
			subtext ?? props.NXUEAp0hU ?? "Aligning user needs to\nbusiness goals.",
		OlZgGaaRO: title ?? props.OlZgGaaRO ?? "Strategic",
		zlZzX8eId: cardNumber ?? props.zlZzX8eId ?? "01",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		OlZgGaaRO: OlZgGaaRO2,
		zlZzX8eId: zlZzX8eId2,
		NXUEAp0hU: NXUEAp0hU2,
		jfQEcfO6T: jfQEcfO6T2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "fg7GobUs3",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className3, className, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1dmwn3d",
							className4,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"fg7GobUs3"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								"fg7GobUs3-hover": {
									"data-framer-name": void 0,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-16jr351"}
							layoutDependency={layoutDependency}
							layoutId={"Cl1OgRsfd"}
							style={{
								backgroundColor:
									"var(--token-732029c9-e563-420b-b3e8-807c94fb9d56, rgb(255, 255, 255))",
								borderBottomLeftRadius: 10,
								borderBottomRightRadius: 10,
								borderTopLeftRadius: 10,
								borderTopRightRadius: 10,
							}}
							variants={{
								"fg7GobUs3-hover": {
									borderBottomLeftRadius: 0,
									borderBottomRightRadius: 0,
								},
							}}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-766bcn"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"cukGbdJSx"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={OlZgGaaRO2}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1muwkq9"}
										data-styles-preset={"G8z5IMrxF"}
										dir={"auto"}
									>
										{"Strategic"}
									</motion.p>
								</React.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-9j1x1y"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"HgSCYgVHc"}
								style={{
									"--extracted-r6o4lv": "rgb(99, 99, 99)",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={zlZzX8eId2}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1vpqesh"}
										data-styles-preset={"eO0w7qcNn"}
										dir={"auto"}
										style={{
											"--framer-text-alignment": "right",
											"--framer-text-color":
												"var(--extracted-r6o4lv, rgb(99, 99, 99))",
										}}
									>
										{"01"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
						<motion.div
							className={"framer-1hsxvym"}
							layoutDependency={layoutDependency}
							layoutId={"e9jDylqMc"}
							style={{
								backgroundColor:
									"var(--token-732029c9-e563-420b-b3e8-807c94fb9d56, rgb(255, 255, 255))",
								borderBottomLeftRadius: 10,
								borderBottomRightRadius: 10,
								borderTopLeftRadius: 10,
								borderTopRightRadius: 10,
							}}
							variants={{
								"fg7GobUs3-hover": {
									borderTopLeftRadius: 0,
									borderTopRightRadius: 0,
								},
							}}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1pj3xve"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"LfPq2Nu9M"}
								style={{
									"--extracted-r6o4lv": "rgb(99, 99, 99)",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={NXUEAp0hU2}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-fjetpu"}
										data-styles-preset={"FIucEdDai"}
										dir={"auto"}
										style={{
											"--framer-text-alignment": "right",
											"--framer-text-color":
												"var(--extracted-r6o4lv, rgb(99, 99, 99))",
										}}
									>
										{"Aligning user needs to"}
										<motion.br />
										{"business goals."}
									</motion.p>
								</React.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-ifqlxn"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"do6XK_QaN"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={jfQEcfO6T2}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-fjetpu"}
										data-styles-preset={"FIucEdDai"}
										dir={"auto"}
										style={{
											"--framer-text-alignment": "left",
										}}
									>
										{"\u2713 Problem statement def"}
										<motion.br />
										{"\u2713 Feature prioritization"}
										<motion.br />
										{"\u2713 North Star Metric"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-Dub4f.framer-1r73kfj, .framer-Dub4f .framer-1r73kfj { display: block; }",
	".framer-Dub4f.framer-1dmwn3d { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: 390px; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 273px; }",
	".framer-Dub4f .framer-16jr351 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 28px; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-Dub4f .framer-766bcn { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-Dub4f .framer-9j1x1y { flex: none; height: auto; position: absolute; right: 10px; top: 10px; white-space: pre; width: auto; z-index: 1; }",
	".framer-Dub4f .framer-1hsxvym { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; height: 1px; justify-content: space-between; overflow: var(--overflow-clip-fallback, clip); padding: 28px; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-Dub4f .framer-1pj3xve, .framer-Dub4f .framer-ifqlxn { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-Dub4f.framer-v-1dmwn3d.hover.framer-1dmwn3d { gap: 0px; }",
	...css3,
	...css,
	...css2,
];
var FramerWwAgXVlkt = withCSS(Component, css4, "framer-Dub4f");
var stdin_default = FramerWwAgXVlkt;
FramerWwAgXVlkt.displayName = "Values Card";
FramerWwAgXVlkt.defaultProps = {
	height: 390,
	width: 272,
};
addPropertyControls(FramerWwAgXVlkt, {
	OlZgGaaRO: {
		defaultValue: "Strategic",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	onOlZgGaaROChange: {
		changes: "OlZgGaaRO",
		type: ControlType.ChangeHandler,
	},
	zlZzX8eId: {
		defaultValue: "01",
		displayTextArea: false,
		title: "Card Number",
		type: ControlType.String,
	},
	onzlZzX8eIdChange: {
		changes: "zlZzX8eId",
		type: ControlType.ChangeHandler,
	},
	NXUEAp0hU: {
		defaultValue: "Aligning user needs to\nbusiness goals.",
		displayTextArea: true,
		title: "Subtext",
		type: ControlType.String,
	},
	onNXUEAp0hUChange: {
		changes: "NXUEAp0hU",
		type: ControlType.ChangeHandler,
	},
	jfQEcfO6T: {
		defaultValue:
			"\u2713 Problem statement def\n\u2713 Feature prioritization\n\u2713 North Star Metric",
		displayTextArea: true,
		title: "Points",
		type: ControlType.String,
	},
	onjfQEcfO6TChange: {
		changes: "jfQEcfO6T",
		type: ControlType.ChangeHandler,
	},
});
addFonts(
	FramerWwAgXVlkt,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:values-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"fbc126bea31ebbe6cf64cc6db71380905aa865df749edb6fe0a120a118d79a8c"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ValuesCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"fbc126bea31ebbe6cf64cc6db71380905aa865df749edb6fe0a120a118d79a8c"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var values_card_default = ComponentWithRoot;
export { values_card_default as default };
