// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project fbc126bea31ebbe6 "Untitled", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * enableAnimation?: boolean // Enable Animation
 * showBubbleLive?: boolean // Show Bubble Live
 * hoverMessages?: {text: string[] // Hover Messages
 * messageFontSize?: number // Message Font Size
 * enableBlink?: boolean // Enable Blink
 * blinkInterval?: number // Blink Interval
 * logoSize?: number // Logo Size
 * logoColor?: string // Logo Color
 * animationDuration?: number // Animation Duration
 * moveDistance?: number // Move Distance
 * direction?: 'Horizontal' | 'Vertical' | 'Both' // Direction
 * buttonText?: string // Button Text
 * buttonFont?: undefined // Button Font
 * buttonColor?: string // Button Color
 * buttonTextColor?: string // Button Text Color
 * buttonPadding?: number // Button Padding
 * buttonOffsetX?: number // Button Offset X
 * buttonOffsetY?: number // Button Offset Y
 * textSize?: number // Text Size
}} Props

 */
import { WalkingLogo } from "./chunks/chunk-VZ5YNITE.js";
import { routes } from "./chunks/chunk-2F3PHDTH.js";

// virtual:walking-logo
import { Fragment } from "react";
import { ContextProviders } from "unframer";
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"fbc126bea31ebbe6cf64cc6db71380905aa865df749edb6fe0a120a118d79a8c"
			}
			locale={locale}
			locales={locales}
		>
			<WalkingLogo {...rest} />
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders WalkingLogoFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"fbc126bea31ebbe6cf64cc6db71380905aa865df749edb6fe0a120a118d79a8c"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={WalkingLogo}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, WalkingLogo);
var walking_logo_default = ComponentWithRoot;
export { walking_logo_default as default };
